<iodissee chk="26294061">
<entete>
<ifichier>
<nomfich nom="waiting">
</nomfich>
<modif date="15/01/2012" user="xiaofa zhao" site="COMMON">
</modif>
</ifichier>
<ioutil nom="ime2" version="8.0.0.0" dateexe="25/09/2011">
</ioutil>
</entete>
<precel>
</precel>
<cel>
<debut poscol=17 poslig=1 destc=17 destl=2 ident=10>
<comment>Waiting
</comment>
</debut>
<act poscol=17 poslig=2 destc=17 destl=3 ident=11>
<Calcul>
<Attente val="2">
</Attente>
</Calcul>
</act>
<result poscol=17 poslig=4 ident=13>
</result>
<act poscol=17 poslig=3 destc=17 destl=4 ident=14>
<comment>for test
</comment>
<Operateur>
<Affichage>
<Paragraphe>
<TexteLibre>
<Texte>Plese Press YES
</Texte>
</TexteLibre>
</Paragraphe>
</Affichage>
</Operateur>
<Operateur>
<Validation nom="OK">
</Validation>
</Operateur>
</act>
</cel>
</iodissee>
