<userserv>
<codeserv nom="DecodeVehicule">
<code numero=1 long=17>
<comment>17 octets + 1 checksum
</comment>
<partcode>
<comment>caractere1 = vehicule
</comment>
<equa>
<descr>TEST_VL
</descr>
<posval pos=1>0
</posval>
</equa>
<equa>
<descr>X1
</descr>
<posval pos=1>1
</posval>
</equa>
<equa>
<descr>U6
</descr>
<posval pos=1>2
</posval>
</equa>
<equa>
<descr>U64
</descr>
<posval pos=1>3
</posval>
</equa>
<equa>
<descr>S2
</descr>
<descr>S23p
</descr>
<posval pos=1>4
</posval>
</equa>
<equa>
<descr>S2
</descr>
<descr>S25p
</descr>
<posval pos=1>5
</posval>
</equa>
<equa>
<descr>T1
</descr>
<descr>T16
</descr>
<posval pos=1>6
</posval>
</equa>
<equa>
<descr>S8
</descr>
<descr>S83p
</descr>
<posval pos=1>7
</posval>
</equa>
<equa>
<descr>S8
</descr>
<descr>S85p
</descr>
<posval pos=1>8
</posval>
</equa>
<equa>
<descr>M49
</descr>
<posval pos=1>9
</posval>
</equa>
<equa>
<descr>N5
</descr>
<descr>N53p
</descr>
<posval pos=1>A
</posval>
</equa>
<equa>
<descr>N5
</descr>
<descr>N55p
</descr>
<posval pos=1>B
</posval>
</equa>
<equa>
<descr>N6
</descr>
<descr>N63p
</descr>
<posval pos=1>C
</posval>
</equa>
<equa>
<descr>N6
</descr>
<descr>N65p
</descr>
<posval pos=1>D
</posval>
</equa>
<equa>
<descr>X2
</descr>
<posval pos=1>E
</posval>
</equa>
<equa>
<descr>U7
</descr>
<posval pos=1>F
</posval>
</equa>
<equa>
<descr>T1
</descr>
<descr>T13p
</descr>
<posval pos=1>G
</posval>
</equa>
<equa>
<descr>T1
</descr>
<descr>T15p
</descr>
<posval pos=1>H
</posval>
</equa>
<equa>
<descr>D9
</descr>
<posval pos=1>J
</posval>
</equa>
<equa>
<descr>Z8
</descr>
<posval pos=1>K
</posval>
</equa>
<equa>
<descr>X5
</descr>
<posval pos=1>L
</posval>
</equa>
<equa>
<descr>X4
</descr>
<posval pos=1>M
</posval>
</equa>
<equa>
<descr>T5
</descr>
<descr>T53p
</descr>
<posval pos=1>N
</posval>
</equa>
<equa>
<descr>T5
</descr>
<descr>T55p
</descr>
<posval pos=1>P
</posval>
</equa>
<equa>
<descr>VEH_BID
</descr>
<posval pos=1>Z
</posval>
</equa>
</partcode>
<partcode>
<comment>Caracteres 2 et 3 = Injection
</comment>
<equa>
<descr>INJ
</descr>
<descr>MM8P
</descr>
<posval pos=2>1
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>SL96
</descr>
<posval pos=2>2
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>MA3.1
</descr>
<posval pos=2>3
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>MP5.2
</descr>
<posval pos=2>4
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>EPICJ5
</descr>
<posval pos=2>5
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>VP20
</descr>
<posval pos=2>6
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>MM1AP
</descr>
<posval pos=2>7
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>MA1.7
</descr>
<posval pos=2>8
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>MP7.0
</descr>
<posval pos=2>9
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>MP7.2
</descr>
<posval pos=2>A
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>MP7.3
</descr>
<posval pos=2>B
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>MP3.2F
</descr>
<posval pos=2>C
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>MP5.1.1
</descr>
<posval pos=2>D
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>VP20_2
</descr>
<posval pos=2>E
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>Sagem_Elec
</descr>
<posval pos=2>F
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>EDC15
</descr>
<posval pos=2>G
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>DCN2
</descr>
<posval pos=2>H
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>MM48P
</descr>
<posval pos=2>J
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>MM4MP
</descr>
<posval pos=2>K
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>AS4
</descr>
<posval pos=2>L
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>ME74
</descr>
<posval pos=2>M
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>S2000
</descr>
<posval pos=2>N
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>M7.4
</descr>
<posval pos=2>Q
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>EDC15_Teleco
</descr>
<posval pos=2>R
</posval>
</equa>
<equa>
<descr>INJ
</descr>
<descr>MM48P_TELE
</descr>
<posval pos=2>S
</posval>
</equa>
<equa>
<descr>ind_2800
</descr>
<posval pos=3>1
</posval>
</equa>
<equa>
<descr>ind_2000
</descr>
<posval pos=3>2
</posval>
</equa>
<equa>
<descr>ind_3000
</descr>
<posval pos=3>3
</posval>
</equa>
<equa>
<descr>ind_4000
</descr>
<posval pos=3>4
</posval>
</equa>
<equa>
<descr>ind_3001
</descr>
<posval pos=3>5
</posval>
</equa>
<equa>
<descr>ind_4001
</descr>
<posval pos=3>6
</posval>
</equa>
<equa>
<descr>ind_6800
</descr>
<posval pos=3>7
</posval>
</equa>
<equa>
<descr>ind_6000
</descr>
<posval pos=3>8
</posval>
</equa>
<equa>
<descr>ind_6001
</descr>
<posval pos=3>9
</posval>
</equa>
<equa>
<descr>ind_A000
</descr>
<posval pos=3>A
</posval>
</equa>
<equa>
<descr>ind_1800
</descr>
<posval pos=3>B
</posval>
</equa>
<equa>
<descr>ind_1000
</descr>
<posval pos=3>C
</posval>
</equa>
<equa>
<descr>ind_5000
</descr>
<posval pos=3>D
</posval>
</equa>
<equa>
<descr>ind_7000
</descr>
<posval pos=3>E
</posval>
</equa>
<equa>
<descr>ind_7800
</descr>
<posval pos=3>F
</posval>
</equa>
<equa>
<descr>ind_8000
</descr>
<posval pos=3>G
</posval>
</equa>
<equa>
<descr>ind_8800
</descr>
<posval pos=3>H
</posval>
</equa>
<equa>
<descr>ind_7001
</descr>
<posval pos=3>J
</posval>
</equa>
<equa>
<descr>ind_8001
</descr>
<posval pos=3>K
</posval>
</equa>
<equa>
<descr>ind_9000
</descr>
<posval pos=3>L
</posval>
</equa>
<equa>
<descr>GPL_fly
</descr>
<posval pos=3>M
</posval>
</equa>
<equa>
<descr>L3
</descr>
<posval pos=3>R
</posval>
</equa>
<equa>
<descr>L4
</descr>
<posval pos=3>S
</posval>
</equa>
<equa>
<descr>120_GR
</descr>
<posval pos=3>T
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 4 = ABS/ASR
</comment>
<equa>
<descr>ABS
</descr>
<descr>TEVES
</descr>
<posval pos=4>2
</posval>
</equa>
<equa>
<descr>ABS
</descr>
<descr>MKivGi
</descr>
<posval pos=4>3
</posval>
</equa>
<equa>
<descr>ABS
</descr>
<descr>MK20E
</descr>
<posval pos=4>4
</posval>
</equa>
<equa>
<descr>ABS
</descr>
<descr>ABS53
</descr>
<posval pos=4>5
</posval>
</equa>
<equa>
<descr>ABS
</descr>
<descr>MK20E_REF
</descr>
<posval pos=4>6
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 5 = BVA
</comment>
<equa>
<descr>BVA
</descr>
<descr>4HP20
</descr>
<posval pos=5>1
</posval>
</equa>
<equa>
<descr>BVA
</descr>
<descr>AL4
</descr>
<posval pos=5>2
</posval>
</equa>
<equa>
<descr>BVA
</descr>
<descr>BVA_MB3
</descr>
<posval pos=5>3
</posval>
</equa>
<equa>
<descr>AL4_SHIFT_LOCK
</descr>
<descr>BVA
</descr>
<descr>AL4
</descr>
<posval pos=5>4
</posval>
</equa>
<equa>
<descr>BVA
</descr>
<descr>4HP20_XU10
</descr>
<posval pos=5>5
</posval>
</equa>
<equa>
<descr>BVA
</descr>
<descr>4HP20_ES9
</descr>
<posval pos=5>6
</posval>
</equa>
<equa>
<descr>BVM
</descr>
<descr>BVM_LONGUE
</descr>
<posval pos=5>7
</posval>
</equa>
<equa>
<descr>BVM
</descr>
<descr>BVM_COURTE
</descr>
<posval pos=5>8
</posval>
</equa>
<equa>
<descr>BVA
</descr>
<descr>AL4
</descr>
<descr>TA2000
</descr>
<posval pos=5>A
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 6 = suspension / adac + DAA
</comment>
<equa>
<descr>SUSP
</descr>
<descr>NIPPO
</descr>
<descr>NIPPO_0B
</descr>
<posval pos=6>1
</posval>
</equa>
<equa>
<descr>SUSP
</descr>
<descr>HYD
</descr>
<posval pos=6>2
</posval>
</equa>
<equa>
<descr>SUSP
</descr>
<descr>MECA
</descr>
<posval pos=6>3
</posval>
</equa>
<equa>
<descr>SUSP
</descr>
<descr>ACTIVA
</descr>
<posval pos=6>4
</posval>
</equa>
<equa>
<descr>SUSP
</descr>
<descr>HYD
</descr>
<descr>HYD_TABLE5
</descr>
<posval pos=6>5
</posval>
</equa>
<equa>
<descr>SUSP
</descr>
<descr>ACTIVA
</descr>
<descr>ACTIVA_TABLE1
</descr>
<posval pos=6>6
</posval>
</equa>
<equa>
<descr>SUSP
</descr>
<descr>ACTIVA
</descr>
<descr>ACTIVA_TABLE2
</descr>
<posval pos=6>7
</posval>
</equa>
<equa>
<descr>SUSP
</descr>
<descr>NIPPO
</descr>
<descr>NIPPO_0A
</descr>
<posval pos=6>8
</posval>
</equa>
<equa>
<descr>SUSP
</descr>
<descr>NIPPO
</descr>
<descr>NIPPO_0C
</descr>
<posval pos=6>9
</posval>
</equa>
<equa>
<descr>SUSP
</descr>
<descr>NIPPO
</descr>
<descr>NIPPO_0A
</descr>
<descr>DAA
</descr>
<descr>DAAZF
</descr>
<posval pos=6>A
</posval>
</equa>
<equa>
<descr>SUSP
</descr>
<descr>NIPPO
</descr>
<descr>NIPPO_0B
</descr>
<descr>DAA
</descr>
<descr>DAAZF
</descr>
<posval pos=6>B
</posval>
</equa>
<equa>
<descr>SUSP
</descr>
<descr>NIPPO
</descr>
<descr>NIPPO_0C
</descr>
<descr>DAA
</descr>
<descr>DAAZF
</descr>
<posval pos=6>C
</posval>
</equa>
<equa>
<descr>DAA
</descr>
<descr>DAAZF
</descr>
<posval pos=6>D
</posval>
</equa>
<equa>
<descr>DIRECTION_DROITE
</descr>
<posval pos=6>E
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 7 = AIRBAG
</comment>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_AC4
</descr>
<descr>SEUL
</descr>
<posval pos=7>1
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_AC4
</descr>
<descr>PASSAGER
</descr>
<posval pos=7>2
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_AC4
</descr>
<descr>LATERAL
</descr>
<descr>PASSAGER
</descr>
<posval pos=7>3
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_AC4
</descr>
<descr>LATERAL
</descr>
<descr>SEUL
</descr>
<posval pos=7>4
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>TEMIC
</descr>
<descr>SEUL
</descr>
<posval pos=7>5
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>TEMIC
</descr>
<descr>PASSAGER
</descr>
<posval pos=7>6
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>TEMIC
</descr>
<descr>LATERAL
</descr>
<descr>PASSAGER
</descr>
<posval pos=7>7
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>TEMIC
</descr>
<descr>PASSAGER
</descr>
<descr>INHIB_PASSAGER
</descr>
<posval pos=7>8
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_EC5
</descr>
<descr>SEUL
</descr>
<posval pos=7>9
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_EC5
</descr>
<descr>PASSAGER
</descr>
<posval pos=7>A
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_EC5
</descr>
<descr>LATERAL
</descr>
<descr>PASSAGER
</descr>
<posval pos=7>B
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_EC5
</descr>
<descr>LATERAL
</descr>
<descr>SEUL
</descr>
<posval pos=7>C
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_TRW
</descr>
<descr>SEUL
</descr>
<posval pos=7>D
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_TRW
</descr>
<descr>PASSAGER
</descr>
<posval pos=7>E
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_TRW
</descr>
<descr>LATERAL
</descr>
<descr>PASSAGER
</descr>
<posval pos=7>F
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_TRW
</descr>
<descr>LATERAL
</descr>
<descr>SEUL
</descr>
<posval pos=7>G
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_AC4_1
</descr>
<descr>SEUL
</descr>
<posval pos=7>H
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_AC4_1
</descr>
<descr>PASSAGER
</descr>
<posval pos=7>J
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_AC4_1
</descr>
<descr>PASSAGER
</descr>
<descr>LATERAL
</descr>
<posval pos=7>K
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_AC4_1
</descr>
<descr>INHIB_PASSAGER
</descr>
<posval pos=7>L
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>SAC_AC4_1
</descr>
<descr>INHIB_PASSAGER
</descr>
<descr>LATERAL
</descr>
<posval pos=7>M
</posval>
</equa>
<equa>
<descr>AIRBAG
</descr>
<descr>TEMIC
</descr>
<descr>PASSAGER
</descr>
<descr>INHIB_PASSAGER
</descr>
<descr>LATERAL
</descr>
<posval pos=7>N
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 8 = REFRI
</comment>
<equa>
<descr>REFRI
</descr>
<descr>CLI_D80
</descr>
<posval pos=8>1
</posval>
</equa>
<equa>
<descr>REFRI
</descr>
<descr>Clim_BEHR_806
</descr>
<posval pos=8>2
</posval>
</equa>
<equa>
<descr>REFRI
</descr>
<descr>CLI_220
</descr>
<posval pos=8>3
</posval>
</equa>
<equa>
<descr>REFRI
</descr>
<descr>Clim_BEHR_T1
</descr>
<posval pos=8>4
</posval>
</equa>
<equa>
<descr>REFRI
</descr>
<descr>CLIM_TT
</descr>
<posval pos=8>6
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 9 = RETRO / SIEGE
</comment>
<equa>
<descr>RETRO_SIEGE
</descr>
<descr>BITRON
</descr>
<posval pos=9>1
</posval>
</equa>
<equa>
<descr>RETRO_SIEGE
</descr>
<descr>INDEXX1
</descr>
<posval pos=9>2
</posval>
</equa>
<equa>
<descr>CHAUF_A0
</descr>
<posval pos=9>3
</posval>
</equa>
<equa>
<descr>CHAUF_A1
</descr>
<posval pos=9>4
</posval>
</equa>
<equa>
<descr>CHAUF_A2
</descr>
<posval pos=9>5
</posval>
</equa>
<equa>
<descr>CHAUF_A3
</descr>
<posval pos=9>6
</posval>
</equa>
<equa>
<descr>CHAUF_A4
</descr>
<posval pos=9>7
</posval>
</equa>
<equa>
<descr>CHAUF_A5
</descr>
<posval pos=9>8
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 10 = ALARME / SUPCO
</comment>
<equa>
<descr>ALARME
</descr>
<posval pos=10>1
</posval>
</equa>
<equa>
<descr>AL_SUPCO
</descr>
<descr>ALARME
</descr>
<descr>SUPCO
</descr>
<posval pos=10>2
</posval>
</equa>
<equa>
<descr>SUPCO
</descr>
<posval pos=10>3
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 11 = DAA D8
</comment>
<appl>
<pour>
<descr>D8
</descr>
</pour>
</appl>
<equa>
<descr>DAA
</descr>
<descr>DAAZF
</descr>
<posval pos=11>1
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 11 = FRIC T1
</comment>
<appl>
<pour>
<descr>T1
</descr>
</pour>
</appl>
<equa>
<descr>FRIC_0
</descr>
<posval pos=11>4
</posval>
</equa>
<equa>
<descr>FRIC_A
</descr>
<posval pos=11>5
</posval>
</equa>
<equa>
<descr>FRIC_A0
</descr>
<posval pos=11>6
</posval>
</equa>
<equa>
<descr>FRIC_B1
</descr>
<posval pos=11>7
</posval>
</equa>
<equa>
<descr>FRIC_B2
</descr>
<posval pos=11>8
</posval>
</equa>
<equa>
<descr>FRIC_C
</descr>
<posval pos=11>9
</posval>
</equa>
<equa>
<descr>FRIC_C0
</descr>
<posval pos=11>A
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 11 = config 3 BSI
</comment>
<appl>
<pour>
<descr>BSI_SIE_D9
</descr>
<descr>D9
</descr>
</pour>
</appl>
<equa>
<descr>OPTION11
</descr>
<posval pos=11>2
</posval>
</equa>
<equa>
<descr>OPTION12
</descr>
<posval pos=11>3
</posval>
</equa>
<equa>
<descr>OPTION13
</descr>
<posval pos=11>5
</posval>
</equa>
<equa>
<descr>OPTION14
</descr>
<posval pos=11>9
</posval>
</equa>
<equa>
<descr>OPTION15
</descr>
<posval pos=11>H
</posval>
</equa>
<equa>
<descr>OPTION12
</descr>
<descr>OPTION15
</descr>
<posval pos=11>K
</posval>
</equa>
<equa>
<descr>OPTION12
</descr>
<descr>OPTION13
</descr>
<posval pos=11>7
</posval>
</equa>
<equa>
<descr>OPTION13
</descr>
<descr>OPTION15
</descr>
<posval pos=11>M
</posval>
</equa>
<equa>
<descr>OPTION13
</descr>
<descr>OPTION14
</descr>
<posval pos=11>D
</posval>
</equa>
<equa>
<descr>OPTION12
</descr>
<descr>OPTION14
</descr>
<posval pos=11>B
</posval>
</equa>
<equa>
<descr>OPTION15
</descr>
<descr>OPTION14
</descr>
<posval pos=11>S
</posval>
</equa>
<equa>
<descr>OPTION11
</descr>
<descr>OPTION12
</descr>
<posval pos=11>4
</posval>
</equa>
<equa>
<descr>OPTION11
</descr>
<descr>OPTION13
</descr>
<posval pos=11>6
</posval>
</equa>
<equa>
<descr>OPTION11
</descr>
<descr>OPTION14
</descr>
<posval pos=11>A
</posval>
</equa>
<equa>
<descr>OPTION11
</descr>
<descr>OPTION15
</descr>
<posval pos=11>J
</posval>
</equa>
<equa>
<descr>OPTION14
</descr>
<descr>OPTION15
</descr>
<descr>OPTION13
</descr>
<posval pos=11>W
</posval>
</equa>
<equa>
<descr>OPTION14
</descr>
<descr>OPTION12
</descr>
<descr>OPTION15
</descr>
<posval pos=11>U
</posval>
</equa>
<equa>
<descr>OPTION15
</descr>
<descr>OPTION12
</descr>
<descr>OPTION13
</descr>
<posval pos=11>P
</posval>
</equa>
<equa>
<descr>OPTION14
</descr>
<descr>OPTION12
</descr>
<descr>OPTION13
</descr>
<posval pos=11>F
</posval>
</equa>
<equa>
<descr>OPTION11
</descr>
<descr>OPTION12
</descr>
<descr>OPTION13
</descr>
<posval pos=11>8
</posval>
</equa>
<equa>
<descr>OPTION11
</descr>
<descr>OPTION12
</descr>
<descr>OPTION14
</descr>
<posval pos=11>C
</posval>
</equa>
<equa>
<descr>OPTION11
</descr>
<descr>OPTION12
</descr>
<descr>OPTION15
</descr>
<posval pos=11>L
</posval>
</equa>
<equa>
<descr>OPTION11
</descr>
<descr>OPTION13
</descr>
<descr>OPTION14
</descr>
<posval pos=11>E
</posval>
</equa>
<equa>
<descr>OPTION11
</descr>
<descr>OPTION13
</descr>
<descr>OPTION15
</descr>
<posval pos=11>N
</posval>
</equa>
<equa>
<descr>OPTION11
</descr>
<descr>OPTION14
</descr>
<descr>OPTION15
</descr>
<posval pos=11>T
</posval>
</equa>
<equa>
<descr>OPTION15
</descr>
<descr>OPTION12
</descr>
<descr>OPTION13
</descr>
<descr>OPTION14
</descr>
<posval pos=11>Y
</posval>
</equa>
<equa>
<descr>OPTION11
</descr>
<descr>OPTION12
</descr>
<descr>OPTION13
</descr>
<descr>OPTION14
</descr>
<posval pos=11>G
</posval>
</equa>
<equa>
<descr>OPTION11
</descr>
<descr>OPTION12
</descr>
<descr>OPTION13
</descr>
<descr>OPTION15
</descr>
<posval pos=11>R
</posval>
</equa>
<equa>
<descr>OPTION11
</descr>
<descr>OPTION12
</descr>
<descr>OPTION14
</descr>
<descr>OPTION15
</descr>
<posval pos=11>V
</posval>
</equa>
<equa>
<descr>OPTION11
</descr>
<descr>OPTION13
</descr>
<descr>OPTION14
</descr>
<descr>OPTION15
</descr>
<posval pos=11>X
</posval>
</equa>
<equa>
<descr>OPTION11
</descr>
<descr>OPTION12
</descr>
<descr>OPTION13
</descr>
<descr>OPTION14
</descr>
<descr>OPTION15
</descr>
<posval pos=11>Z
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 12 = Tanspondeur / BSI /CPH
</comment>
<equa>
<descr>CPH_TEXTON
</descr>
<descr>CPH
</descr>
<descr>CPH_TEXT1
</descr>
<posval pos=12>1
</posval>
</equa>
<equa>
<descr>CPH_TEXTON
</descr>
<descr>CPH
</descr>
<descr>CPH_TEXT2
</descr>
<posval pos=12>2
</posval>
</equa>
<equa>
<descr>CPH_TEXTON
</descr>
<descr>CPH
</descr>
<descr>CPH_TEXT3
</descr>
<posval pos=12>3
</posval>
</equa>
<equa>
<descr>BSI_SIE
</descr>
<descr>BSI
</descr>
<descr>BSI_SIEB1
</descr>
<posval pos=12>4
</posval>
</equa>
<equa>
<descr>BSI_SIE
</descr>
<descr>BSI
</descr>
<descr>BSI_SIEB2
</descr>
<posval pos=12>5
</posval>
</equa>
<equa>
<descr>BSI_SIE
</descr>
<descr>BSI
</descr>
<descr>BSI_SIEB4_T16
</descr>
<descr>TOIT_T1
</descr>
<posval pos=12>6
</posval>
</equa>
<equa>
<descr>BSI_SIE
</descr>
<descr>BSI
</descr>
<descr>BSI_SIEB4
</descr>
<posval pos=12>7
</posval>
</equa>
<equa>
<descr>TRANSPON_SIEMENS
</descr>
<descr>ADC
</descr>
<posval pos=12>8
</posval>
</equa>
<equa>
<descr>TRA_VALEO
</descr>
<descr>ADC
</descr>
<posval pos=12>9
</posval>
</equa>
<equa>
<descr>CPH_TEXTON_CR
</descr>
<descr>CPH
</descr>
<descr>CPH_TEXCR1
</descr>
<posval pos=12>A
</posval>
</equa>
<equa>
<descr>CPH_TEXTON_CR
</descr>
<descr>CPH
</descr>
<descr>CPH_TEXCR2
</descr>
<posval pos=12>B
</posval>
</equa>
<equa>
<descr>CPH_TEXTON_CR
</descr>
<descr>CPH
</descr>
<descr>CPH_TEXCR3
</descr>
<posval pos=12>C
</posval>
</equa>
<equa>
<descr>BSI_SIE
</descr>
<descr>BSI_SIE_D9
</descr>
<descr>BSI
</descr>
<descr>BSI_SIE_D9_B2
</descr>
<posval pos=12>D
</posval>
</equa>
<equa>
<descr>BSI_SIE
</descr>
<descr>BSI_SIE_D9
</descr>
<descr>BSI
</descr>
<descr>BSI_SIE_D9_B2-
</descr>
<posval pos=12>E
</posval>
</equa>
<equa>
<descr>BSI_SIE
</descr>
<descr>BSI_SIEB1
</descr>
<descr>BSI_SIE_D9
</descr>
<descr>BSI
</descr>
<descr>BSI_SIE_D9_B3
</descr>
<posval pos=12>F
</posval>
</equa>
<equa>
<descr>BSI_SIE
</descr>
<descr>BSI_SIE_D9
</descr>
<descr>BSI
</descr>
<descr>BSI_SIE_D9_B3-
</descr>
<posval pos=12>G
</posval>
</equa>
<equa>
<descr>BSI_SIE
</descr>
<descr>BSI_SIE_D9
</descr>
<descr>BSI
</descr>
<descr>BSI_SIE_D9_B4
</descr>
<posval pos=12>H
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 13 = nbre de cles pour transpondeur SIEMENS
</comment>
<appl>
<pour>
<descr>TRANSPON_SIEMENS
</descr>
<descr>ADC
</descr>
</pour>
<pour>
<descr>TRA_VALEO
</descr>
<descr>ADC
</descr>
</pour>
</appl>
<equa>
<descr>NbCle2
</descr>
<posval pos=13>1
</posval>
</equa>
<equa>
<descr>NbCle3
</descr>
<posval pos=13>2
</posval>
</equa>
<equa>
<descr>NbCle2
</descr>
<posval pos=13>3
</posval>
</equa>
<equa>
<descr>NbCle3
</descr>
<posval pos=13>4
</posval>
</equa>
<equa>
<descr>NbCle2
</descr>
<posval pos=13>5
</posval>
</equa>
<equa>
<descr>NbCle3
</descr>
<posval pos=13>6
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 13 = nbre de cles et de plips
</comment>
<appl>
<pour>
<descr>CPH
</descr>
</pour>
<pour>
<descr>BSI
</descr>
</pour>
</appl>
<equa>
<descr>NbCle2
</descr>
<posval pos=13>1
</posval>
</equa>
<equa>
<descr>NbCle3
</descr>
<posval pos=13>2
</posval>
</equa>
<equa>
<descr>NbCle2
</descr>
<descr>AvecPlip
</descr>
<descr>NbPlip1
</descr>
<posval pos=13>3
</posval>
</equa>
<equa>
<descr>NbCle3
</descr>
<descr>AvecPlip
</descr>
<descr>NbPlip1
</descr>
<posval pos=13>4
</posval>
</equa>
<equa>
<descr>NbCle2
</descr>
<descr>AvecPlip
</descr>
<descr>NbPlip2
</descr>
<posval pos=13>5
</posval>
</equa>
<equa>
<descr>NbCle3
</descr>
<descr>AvecPlip
</descr>
<descr>NbPlip2
</descr>
<posval pos=13>6
</posval>
</equa>
<equa>
<descr>TestLigneK
</descr>
<posval pos=13>Z
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 14 = config BSI SIEMENS / CPH Texton
</comment>
<appl>
<pour>
<descr>BSI_SIE
</descr>
</pour>
<pour>
<descr>BSI_SIE_D9
</descr>
</pour>
<pour>
<descr>CPH
</descr>
</pour>
<pour>
<descr>TRA_VALEO
</descr>
</pour>
<pour>
<descr>TRANSPON_SIEMENS
</descr>
</pour>
</appl>
<equa>
<descr>OPTION1
</descr>
<posval pos=14>2
</posval>
</equa>
<equa>
<descr>OPTION2
</descr>
<posval pos=14>3
</posval>
</equa>
<equa>
<descr>OPTION3
</descr>
<posval pos=14>5
</posval>
</equa>
<equa>
<descr>OPTION4
</descr>
<posval pos=14>9
</posval>
</equa>
<equa>
<descr>OPTION5
</descr>
<posval pos=14>H
</posval>
</equa>
<equa>
<descr>OPTION2
</descr>
<descr>OPTION5
</descr>
<posval pos=14>K
</posval>
</equa>
<equa>
<descr>OPTION2
</descr>
<descr>OPTION3
</descr>
<posval pos=14>7
</posval>
</equa>
<equa>
<descr>OPTION3
</descr>
<descr>OPTION5
</descr>
<posval pos=14>M
</posval>
</equa>
<equa>
<descr>OPTION3
</descr>
<descr>OPTION4
</descr>
<posval pos=14>D
</posval>
</equa>
<equa>
<descr>OPTION2
</descr>
<descr>OPTION4
</descr>
<posval pos=14>B
</posval>
</equa>
<equa>
<descr>OPTION5
</descr>
<descr>OPTION4
</descr>
<posval pos=14>S
</posval>
</equa>
<equa>
<descr>OPTION1
</descr>
<descr>OPTION2
</descr>
<posval pos=14>4
</posval>
</equa>
<equa>
<descr>OPTION1
</descr>
<descr>OPTION3
</descr>
<posval pos=14>6
</posval>
</equa>
<equa>
<descr>OPTION1
</descr>
<descr>OPTION4
</descr>
<posval pos=14>A
</posval>
</equa>
<equa>
<descr>OPTION1
</descr>
<descr>OPTION5
</descr>
<posval pos=14>J
</posval>
</equa>
<equa>
<descr>OPTION4
</descr>
<descr>OPTION5
</descr>
<descr>OPTION3
</descr>
<posval pos=14>W
</posval>
</equa>
<equa>
<descr>OPTION4
</descr>
<descr>OPTION2
</descr>
<descr>OPTION5
</descr>
<posval pos=14>U
</posval>
</equa>
<equa>
<descr>OPTION5
</descr>
<descr>OPTION2
</descr>
<descr>OPTION3
</descr>
<posval pos=14>P
</posval>
</equa>
<equa>
<descr>OPTION4
</descr>
<descr>OPTION2
</descr>
<descr>OPTION3
</descr>
<posval pos=14>F
</posval>
</equa>
<equa>
<descr>OPTION1
</descr>
<descr>OPTION2
</descr>
<descr>OPTION3
</descr>
<posval pos=14>8
</posval>
</equa>
<equa>
<descr>OPTION1
</descr>
<descr>OPTION2
</descr>
<descr>OPTION4
</descr>
<posval pos=14>C
</posval>
</equa>
<equa>
<descr>OPTION1
</descr>
<descr>OPTION2
</descr>
<descr>OPTION5
</descr>
<posval pos=14>L
</posval>
</equa>
<equa>
<descr>OPTION1
</descr>
<descr>OPTION3
</descr>
<descr>OPTION4
</descr>
<posval pos=14>E
</posval>
</equa>
<equa>
<descr>OPTION1
</descr>
<descr>OPTION3
</descr>
<descr>OPTION5
</descr>
<posval pos=14>N
</posval>
</equa>
<equa>
<descr>OPTION1
</descr>
<descr>OPTION4
</descr>
<descr>OPTION5
</descr>
<posval pos=14>T
</posval>
</equa>
<equa>
<descr>OPTION5
</descr>
<descr>OPTION2
</descr>
<descr>OPTION3
</descr>
<descr>OPTION4
</descr>
<posval pos=14>Y
</posval>
</equa>
<equa>
<descr>OPTION1
</descr>
<descr>OPTION2
</descr>
<descr>OPTION3
</descr>
<descr>OPTION4
</descr>
<posval pos=14>G
</posval>
</equa>
<equa>
<descr>OPTION1
</descr>
<descr>OPTION2
</descr>
<descr>OPTION3
</descr>
<descr>OPTION5
</descr>
<posval pos=14>R
</posval>
</equa>
<equa>
<descr>OPTION1
</descr>
<descr>OPTION2
</descr>
<descr>OPTION4
</descr>
<descr>OPTION5
</descr>
<posval pos=14>V
</posval>
</equa>
<equa>
<descr>OPTION1
</descr>
<descr>OPTION3
</descr>
<descr>OPTION4
</descr>
<descr>OPTION5
</descr>
<posval pos=14>X
</posval>
</equa>
<equa>
<descr>OPTION1
</descr>
<descr>OPTION2
</descr>
<descr>OPTION3
</descr>
<descr>OPTION4
</descr>
<descr>OPTION5
</descr>
<posval pos=14>Z
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 15 = config 2 BSI
</comment>
<appl>
<pour>
<descr>BSI_SIE
</descr>
</pour>
<pour>
<descr>BSI_SIE_D9
</descr>
</pour>
</appl>
<equa>
<descr>OPTION6
</descr>
<posval pos=15>2
</posval>
</equa>
<equa>
<descr>OPTION7
</descr>
<posval pos=15>3
</posval>
</equa>
<equa>
<descr>OPTION8
</descr>
<posval pos=15>5
</posval>
</equa>
<equa>
<descr>OPTION9
</descr>
<posval pos=15>9
</posval>
</equa>
<equa>
<descr>OPTION10
</descr>
<posval pos=15>H
</posval>
</equa>
<equa>
<descr>OPTION7
</descr>
<descr>OPTION10
</descr>
<posval pos=15>K
</posval>
</equa>
<equa>
<descr>OPTION7
</descr>
<descr>OPTION8
</descr>
<posval pos=15>7
</posval>
</equa>
<equa>
<descr>OPTION8
</descr>
<descr>OPTION10
</descr>
<posval pos=15>M
</posval>
</equa>
<equa>
<descr>OPTION8
</descr>
<descr>OPTION9
</descr>
<posval pos=15>D
</posval>
</equa>
<equa>
<descr>OPTION7
</descr>
<descr>OPTION9
</descr>
<posval pos=15>B
</posval>
</equa>
<equa>
<descr>OPTION10
</descr>
<descr>OPTION9
</descr>
<posval pos=15>S
</posval>
</equa>
<equa>
<descr>OPTION6
</descr>
<descr>OPTION7
</descr>
<posval pos=15>4
</posval>
</equa>
<equa>
<descr>OPTION6
</descr>
<descr>OPTION8
</descr>
<posval pos=15>6
</posval>
</equa>
<equa>
<descr>OPTION6
</descr>
<descr>OPTION9
</descr>
<posval pos=15>A
</posval>
</equa>
<equa>
<descr>OPTION6
</descr>
<descr>OPTION10
</descr>
<posval pos=15>J
</posval>
</equa>
<equa>
<descr>OPTION9
</descr>
<descr>OPTION10
</descr>
<descr>OPTION8
</descr>
<posval pos=15>W
</posval>
</equa>
<equa>
<descr>OPTION9
</descr>
<descr>OPTION7
</descr>
<descr>OPTION10
</descr>
<posval pos=15>U
</posval>
</equa>
<equa>
<descr>OPTION10
</descr>
<descr>OPTION7
</descr>
<descr>OPTION8
</descr>
<posval pos=15>P
</posval>
</equa>
<equa>
<descr>OPTION9
</descr>
<descr>OPTION7
</descr>
<descr>OPTION8
</descr>
<posval pos=15>F
</posval>
</equa>
<equa>
<descr>OPTION6
</descr>
<descr>OPTION7
</descr>
<descr>OPTION8
</descr>
<posval pos=15>8
</posval>
</equa>
<equa>
<descr>OPTION6
</descr>
<descr>OPTION7
</descr>
<descr>OPTION9
</descr>
<posval pos=15>C
</posval>
</equa>
<equa>
<descr>OPTION6
</descr>
<descr>OPTION7
</descr>
<descr>OPTION10
</descr>
<posval pos=15>L
</posval>
</equa>
<equa>
<descr>OPTION6
</descr>
<descr>OPTION8
</descr>
<descr>OPTION9
</descr>
<posval pos=15>E
</posval>
</equa>
<equa>
<descr>OPTION6
</descr>
<descr>OPTION8
</descr>
<descr>OPTION10
</descr>
<posval pos=15>N
</posval>
</equa>
<equa>
<descr>OPTION6
</descr>
<descr>OPTION9
</descr>
<descr>OPTION10
</descr>
<posval pos=15>T
</posval>
</equa>
<equa>
<descr>OPTION10
</descr>
<descr>OPTION7
</descr>
<descr>OPTION8
</descr>
<descr>OPTION9
</descr>
<posval pos=15>Y
</posval>
</equa>
<equa>
<descr>OPTION6
</descr>
<descr>OPTION7
</descr>
<descr>OPTION8
</descr>
<descr>OPTION9
</descr>
<posval pos=15>G
</posval>
</equa>
<equa>
<descr>OPTION6
</descr>
<descr>OPTION7
</descr>
<descr>OPTION8
</descr>
<descr>OPTION10
</descr>
<posval pos=15>R
</posval>
</equa>
<equa>
<descr>OPTION6
</descr>
<descr>OPTION7
</descr>
<descr>OPTION9
</descr>
<descr>OPTION10
</descr>
<posval pos=15>V
</posval>
</equa>
<equa>
<descr>OPTION6
</descr>
<descr>OPTION8
</descr>
<descr>OPTION9
</descr>
<descr>OPTION10
</descr>
<posval pos=15>X
</posval>
</equa>
<equa>
<descr>OPTION6
</descr>
<descr>OPTION7
</descr>
<descr>OPTION8
</descr>
<descr>OPTION9
</descr>
<descr>OPTION10
</descr>
<posval pos=15>Z
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 16 = confort T1 ou T16
</comment>
<equa>
<descr>LV_SANS_SEQUENTIEL
</descr>
<posval pos=16>1
</posval>
</equa>
<equa>
<descr>NAV
</descr>
<posval pos=16>2
</posval>
</equa>
<equa>
<descr>CD
</descr>
<posval pos=16>3
</posval>
</equa>
<equa>
<descr>NAV
</descr>
<descr>CD
</descr>
<posval pos=16>4
</posval>
</equa>
<equa>
<descr>LV_SEQUENTIEL_D
</descr>
<posval pos=16>9
</posval>
</equa>
<equa>
<descr>NAV
</descr>
<descr>LV_SEQUENTIEL_D
</descr>
<posval pos=16>A
</posval>
</equa>
<equa>
<descr>CD
</descr>
<descr>LV_SEQUENTIEL_D
</descr>
<posval pos=16>B
</posval>
</equa>
<equa>
<descr>NAV
</descr>
<descr>CD
</descr>
<descr>LV_SEQUENTIEL_D
</descr>
<posval pos=16>C
</posval>
</equa>
<equa>
<descr>LV_SEQUENTIEL_G
</descr>
<posval pos=16>H
</posval>
</equa>
<equa>
<descr>NAV
</descr>
<descr>LV_SEQUENTIEL_G
</descr>
<posval pos=16>J
</posval>
</equa>
<equa>
<descr>CD
</descr>
<descr>LV_SEQUENTIEL_G
</descr>
<posval pos=16>K
</posval>
</equa>
<equa>
<descr>NAV
</descr>
<descr>CD
</descr>
<descr>LV_SEQUENTIEL_G
</descr>
<posval pos=16>L
</posval>
</equa>
<equa>
<descr>LV_SEQUENTIEL_D
</descr>
<descr>LV_SEQUENTIEL_G
</descr>
<posval pos=16>S
</posval>
</equa>
<equa>
<descr>NAV
</descr>
<descr>LV_SEQUENTIEL_D
</descr>
<descr>LV_SEQUENTIEL_G
</descr>
<posval pos=16>T
</posval>
</equa>
<equa>
<descr>CD
</descr>
<descr>LV_SEQUENTIEL_D
</descr>
<descr>LV_SEQUENTIEL_G
</descr>
<posval pos=16>U
</posval>
</equa>
<equa>
<descr>NAV
</descr>
<descr>CD
</descr>
<descr>LV_SEQUENTIEL_D
</descr>
<descr>LV_SEQUENTIEL_G
</descr>
<posval pos=16>V
</posval>
</equa>
</partcode>
<partcode>
<comment>Caractere 16 specifique en fonction du code VL
</comment>
<appl>
<pour>
<descr>X1
</descr>
</pour>
</appl>
<equa>
<descr>TestLigneK
</descr>
<posval pos=16>Z
</posval>
</equa>
</partcode>
<partcode>
<comment>Caractere 17 = Classe alternateurs
</comment>
<equa>
<descr>CLASSE7
</descr>
<posval pos=17>1
</posval>
</equa>
<equa>
<descr>CLASSE8
</descr>
<posval pos=17>2
</posval>
</equa>
<equa>
<descr>CLASSE9
</descr>
<posval pos=17>4
</posval>
</equa>
<equa>
<descr>CLASSE12
</descr>
<posval pos=17>5
</posval>
</equa>
<equa>
<descr>CLASSE15
</descr>
<posval pos=17>6
</posval>
</equa>
</partcode>
<partcode>
<comment>caractere 17 = config 3 BSI
</comment>
<appl>
<pour>
<descr>BSI_SIE_D9
</descr>
</pour>
</appl>
<equa>
<descr>OPTION16
</descr>
<posval pos=17>2
</posval>
</equa>
<equa>
<descr>OPTION17
</descr>
<posval pos=17>3
</posval>
</equa>
<equa>
<descr>OPTION18
</descr>
<posval pos=17>5
</posval>
</equa>
<equa>
<descr>OPTION19
</descr>
<posval pos=17>9
</posval>
</equa>
<equa>
<descr>OPTION20
</descr>
<posval pos=17>H
</posval>
</equa>
<equa>
<descr>OPTION17
</descr>
<descr>OPTION20
</descr>
<posval pos=17>K
</posval>
</equa>
<equa>
<descr>OPTION17
</descr>
<descr>OPTION18
</descr>
<posval pos=17>7
</posval>
</equa>
<equa>
<descr>OPTION18
</descr>
<descr>OPTION20
</descr>
<posval pos=17>M
</posval>
</equa>
<equa>
<descr>OPTION18
</descr>
<descr>OPTION19
</descr>
<posval pos=17>D
</posval>
</equa>
<equa>
<descr>OPTION17
</descr>
<descr>OPTION19
</descr>
<posval pos=17>B
</posval>
</equa>
<equa>
<descr>OPTION20
</descr>
<descr>OPTION19
</descr>
<posval pos=17>S
</posval>
</equa>
<equa>
<descr>OPTION16
</descr>
<descr>OPTION17
</descr>
<posval pos=17>4
</posval>
</equa>
<equa>
<descr>OPTION16
</descr>
<descr>OPTION18
</descr>
<posval pos=17>6
</posval>
</equa>
<equa>
<descr>OPTION16
</descr>
<descr>OPTION19
</descr>
<posval pos=17>A
</posval>
</equa>
<equa>
<descr>OPTION16
</descr>
<descr>OPTION20
</descr>
<posval pos=17>J
</posval>
</equa>
<equa>
<descr>OPTION19
</descr>
<descr>OPTION20
</descr>
<descr>OPTION18
</descr>
<posval pos=17>W
</posval>
</equa>
<equa>
<descr>OPTION19
</descr>
<descr>OPTION17
</descr>
<descr>OPTION20
</descr>
<posval pos=17>U
</posval>
</equa>
<equa>
<descr>OPTION20
</descr>
<descr>OPTION17
</descr>
<descr>OPTION18
</descr>
<posval pos=17>P
</posval>
</equa>
<equa>
<descr>OPTION19
</descr>
<descr>OPTION17
</descr>
<descr>OPTION18
</descr>
<posval pos=17>F
</posval>
</equa>
<equa>
<descr>OPTION16
</descr>
<descr>OPTION17
</descr>
<descr>OPTION18
</descr>
<posval pos=17>8
</posval>
</equa>
<equa>
<descr>OPTION16
</descr>
<descr>OPTION17
</descr>
<descr>OPTION19
</descr>
<posval pos=17>C
</posval>
</equa>
<equa>
<descr>OPTION16
</descr>
<descr>OPTION17
</descr>
<descr>OPTION20
</descr>
<posval pos=17>L
</posval>
</equa>
<equa>
<descr>OPTION16
</descr>
<descr>OPTION18
</descr>
<descr>OPTION19
</descr>
<posval pos=17>E
</posval>
</equa>
<equa>
<descr>OPTION16
</descr>
<descr>OPTION18
</descr>
<descr>OPTION20
</descr>
<posval pos=17>N
</posval>
</equa>
<equa>
<descr>OPTION16
</descr>
<descr>OPTION19
</descr>
<descr>OPTION20
</descr>
<posval pos=17>T
</posval>
</equa>
<equa>
<descr>OPTION20
</descr>
<descr>OPTION17
</descr>
<descr>OPTION18
</descr>
<descr>OPTION19
</descr>
<posval pos=17>Y
</posval>
</equa>
<equa>
<descr>OPTION16
</descr>
<descr>OPTION17
</descr>
<descr>OPTION18
</descr>
<descr>OPTION19
</descr>
<posval pos=17>G
</posval>
</equa>
<equa>
<descr>OPTION16
</descr>
<descr>OPTION17
</descr>
<descr>OPTION18
</descr>
<descr>OPTION20
</descr>
<posval pos=17>R
</posval>
</equa>
<equa>
<descr>OPTION16
</descr>
<descr>OPTION17
</descr>
<descr>OPTION19
</descr>
<descr>OPTION20
</descr>
<posval pos=17>V
</posval>
</equa>
<equa>
<descr>OPTION16
</descr>
<descr>OPTION18
</descr>
<descr>OPTION19
</descr>
<descr>OPTION20
</descr>
<posval pos=17>X
</posval>
</equa>
<equa>
<descr>OPTION16
</descr>
<descr>OPTION17
</descr>
<descr>OPTION18
</descr>
<descr>OPTION19
</descr>
<descr>OPTION20
</descr>
<posval pos=17>Z
</posval>
</equa>
</partcode>
</code>
</codeserv>
<codegene nom="DecodeGenerique">
<comment>Ancien codage
</comment>
<code_ entete="" long=18 checksum="Modulo39">
<partcode_ colonne=1>
<equa_ valeur="A">
<descr>A-COMPLETER
</descr>
</equa_>
</partcode_>
</code_>
<comment>Definition code 39 carac ODISSEE
</comment>
<code_ entete="B" long=39 checksum="Modulo39">
<comment>Colonne 1 = Entete
</comment>
<partcode_ colonne=1>
<equa_ valeur="B">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_NV_CODE
</descr>
<descr>ENTETE_B
</descr>
</equa_>
</partcode_>
<comment>Colonne 2 = Vehicules
</comment>
<partcode_ colonne=2>
<equa_ valeur=2>
<descr>S2
</descr>
</equa_>
<equa_ valeur=3>
<descr>S8
</descr>
</equa_>
<equa_ valeur=4>
<descr>N5
</descr>
</equa_>
<equa_ valeur=5>
<descr>T1_MUX
</descr>
</equa_>
<equa_ valeur=7>
<descr>T5
</descr>
</equa_>
<equa_ valeur=8>
<descr>D9
</descr>
</equa_>
<equa_ valeur=9>
<descr>M49
</descr>
</equa_>
<equa_ valeur="A">
<descr>X2
</descr>
</equa_>
<equa_ valeur="B">
<descr>X4
</descr>
</equa_>
<equa_ valeur="C">
<descr>Y4
</descr>
</equa_>
<equa_ valeur="D">
<descr>Z8
</descr>
</equa_>
<equa_ valeur="E">
<descr>N68
</descr>
</equa_>
<equa_ valeur="F">
<descr>N7
</descr>
</equa_>
<equa_ valeur="G">
<descr>V
</descr>
</equa_>
<equa_ valeur="H">
<descr>A8
</descr>
</equa_>
<equa_ valeur="J">
<descr>A6
</descr>
</equa_>
<equa_ valeur="K">
<descr>M59
</descr>
</equa_>
<equa_ valeur="L">
<descr>N68_MUX
</descr>
</equa_>
<equa_ valeur="M">
<descr>A42
</descr>
</equa_>
<equa_ valeur="N">
<descr>T5
</descr>
<descr>ENTREPRISE
</descr>
</equa_>
<equa_ valeur="P">
<descr>A08
</descr>
</equa_>
<equa_ valeur="Q">
<descr>T21
</descr>
</equa_>
<equa_ valeur="R">
<descr>N78
</descr>
</equa_>
<equa_ valeur="S">
<descr>T3
</descr>
</equa_>
</partcode_>
<comment>Colonne 3 = Injections
</comment>
<partcode_ colonne=3>
<equa_ valeur="1">
<descr>INJ
</descr>
<descr>MM8P
</descr>
</equa_>
<equa_ valeur="2">
<descr>INJ
</descr>
<descr>ESSENCE
</descr>
<descr>SAGEM_2000A
</descr>
</equa_>
<equa_ valeur="3">
<descr>INJ
</descr>
<descr>M7.4.4
</descr>
<descr>ESSENCE
</descr>
</equa_>
<equa_ valeur="4">
<descr>ESSENCE
</descr>
<descr>INJ
</descr>
<descr>ME745
</descr>
</equa_>
<equa_ valeur="5">
<descr>INJ
</descr>
<descr>ESSENCE
</descr>
<descr>MM6LP
</descr>
<descr>EW10
</descr>
</equa_>
<equa_ valeur="6">
<descr>INJ
</descr>
<descr>ESSENCE
</descr>
<descr>MM6LP
</descr>
<descr>ET3
</descr>
</equa_>
<equa_ valeur="7">
<descr>INJ
</descr>
<descr>MM1AP
</descr>
</equa_>
<equa_ valeur="8">
<descr>INJ
</descr>
<descr>MA1.7
</descr>
</equa_>
<equa_ valeur="9">
<descr>INJ
</descr>
<descr>CMM_TU5JP4_GNV
</descr>
</equa_>
<equa_ valeur="A">
<descr>INJ
</descr>
<descr>MP7.2
</descr>
</equa_>
<equa_ valeur="B">
<descr>INJ
</descr>
<descr>MP7.3
</descr>
</equa_>
<equa_ valeur="C">
<descr>INJ
</descr>
<descr>SID803
</descr>
<descr>HDI
</descr>
</equa_>
<equa_ valeur="D">
<descr>INJ
</descr>
<descr>SID804
</descr>
<descr>HDI
</descr>
</equa_>
<equa_ valeur="E">
<descr>INJ
</descr>
<descr>EDC16
</descr>
<descr>DV6
</descr>
<descr>HDI
</descr>
</equa_>
<equa_ valeur="F">
<descr>INJ
</descr>
<descr>Sagem_Elec
</descr>
</equa_>
<equa_ valeur="G">
<descr>INJ
</descr>
<descr>EDC16
</descr>
<descr>DV4
</descr>
<descr>HDI
</descr>
</equa_>
<equa_ valeur="H">
<descr>INJ
</descr>
<descr>DCN2
</descr>
</equa_>
<equa_ valeur="J">
<descr>INJ
</descr>
<descr>MM48P
</descr>
<descr>ESSENCE
</descr>
</equa_>
<equa_ valeur="K">
<descr>INJ
</descr>
<descr>MM4MP
</descr>
<descr>ESSENCE
</descr>
</equa_>
<equa_ valeur="L">
<descr>INJ
</descr>
<descr>AS4
</descr>
</equa_>
<equa_ valeur="M">
<descr>INJ
</descr>
<descr>ME74
</descr>
<descr>ME746
</descr>
<descr>ESSENCE
</descr>
</equa_>
<equa_ valeur="N">
<descr>INJ
</descr>
<descr>S2000
</descr>
<descr>ESSENCE
</descr>
</equa_>
<equa_ valeur="P">
<descr>INJ
</descr>
<descr>SIRIUS81
</descr>
<descr>ESSENCE
</descr>
</equa_>
<equa_ valeur="Q">
<descr>INJ
</descr>
<descr>M7.4
</descr>
<descr>ESSENCE
</descr>
<descr>ME744
</descr>
</equa_>
<equa_ valeur="R">
<descr>INJ
</descr>
<descr>EDC15_Teleco
</descr>
<descr>HDI
</descr>
</equa_>
<equa_ valeur="S">
<descr>INJ
</descr>
<descr>MM48P_TELE
</descr>
<descr>ESSENCE
</descr>
</equa_>
<equa_ valeur="T">
<descr>INJ
</descr>
<descr>SID801
</descr>
<descr>HDI
</descr>
</equa_>
<equa_ valeur="U">
<descr>INJ
</descr>
<descr>MM5NR
</descr>
<descr>ESSENCE
</descr>
</equa_>
<equa_ valeur="V">
<descr>INJ
</descr>
<descr>SID802
</descr>
<descr>HDI
</descr>
</equa_>
<equa_ valeur="W">
<descr>INJ
</descr>
<descr>DELPHI_C6
</descr>
<descr>HDI
</descr>
</equa_>
</partcode_>
<comment>Colonne 4 = Moteurs
</comment>
<partcode_ colonne=4>
<equa_ valeur="1">
<descr>ind_2800
</descr>
</equa_>
<equa_ valeur="2">
<descr>ind_2000
</descr>
</equa_>
<equa_ valeur="4">
<descr>ind_4000
</descr>
</equa_>
<equa_ valeur="5">
<descr>EW10A
</descr>
</equa_>
<equa_ valeur="6">
<descr>ind_4001
</descr>
</equa_>
<equa_ valeur="7">
<descr>J4S
</descr>
</equa_>
<equa_ valeur="A">
<descr>ind_A000
</descr>
</equa_>
<equa_ valeur="B">
<descr>ind_1800
</descr>
</equa_>
<equa_ valeur="C">
<descr>ind_1000
</descr>
</equa_>
<equa_ valeur="D">
<descr>ind_5000
</descr>
</equa_>
<equa_ valeur="J">
<descr>GNV
</descr>
</equa_>
<equa_ valeur="K">
<descr>COMP_GAZ
</descr>
</equa_>
<equa_ valeur="L">
<descr>TED4_FAP
</descr>
</equa_>
<equa_ valeur="M">
<descr>GPL_brc
</descr>
</equa_>
<equa_ valeur="N">
<descr>TD
</descr>
</equa_>
<equa_ valeur="P">
<descr>ATED
</descr>
</equa_>
<equa_ valeur="Q">
<descr>TED4
</descr>
</equa_>
<equa_ valeur="R">
<descr>B800
</descr>
</equa_>
<equa_ valeur="S">
<descr>EW6
</descr>
</equa_>
<equa_ valeur="T">
<descr>PAPILLON_MOTORISE
</descr>
</equa_>
<equa_ valeur="U">
<descr>TU1
</descr>
</equa_>
<equa_ valeur="V">
<descr>ATED
</descr>
<descr>FAP2
</descr>
</equa_>
<equa_ valeur="W">
<descr>TED4
</descr>
<descr>FAP2
</descr>
</equa_>
</partcode_>
<comment>Colonne 5 = ABS/ASR
</comment>
<partcode_ colonne=5>
<equa_ valeur="3">
<descr>ABS
</descr>
<descr>MKivGi
</descr>
</equa_>
<equa_ valeur="4">
<descr>ABS
</descr>
<descr>MK20E
</descr>
</equa_>
<equa_ valeur="5">
<descr>ABS
</descr>
<descr>ABS53
</descr>
</equa_>
<equa_ valeur="6">
<descr>ABS
</descr>
<descr>MK20E_REF
</descr>
</equa_>
<equa_ valeur="7">
<descr>ABS
</descr>
<descr>ABS53
</descr>
</equa_>
<equa_ valeur="8">
<descr>ABS
</descr>
<descr>ABS53
</descr>
</equa_>
<equa_ valeur="9">
<descr>ABS
</descr>
<descr>ABS53
</descr>
</equa_>
<equa_ valeur="A">
<descr>ESP
</descr>
<descr>CDS
</descr>
</equa_>
<equa_ valeur="B">
<descr>MK60
</descr>
<descr>ABS
</descr>
</equa_>
<equa_ valeur="C">
<descr>MK60
</descr>
<descr>ABS
</descr>
<descr>ASR
</descr>
</equa_>
<equa_ valeur="D">
<descr>MK60
</descr>
<descr>ESP
</descr>
</equa_>
<equa_ valeur="E">
<descr>ABS
</descr>
<descr>BOSCH8X
</descr>
<descr>ABS_MUX
</descr>
</equa_>
<equa_ valeur="F">
<descr>ESP_57
</descr>
<descr>ESP
</descr>
<descr>CDS
</descr>
</equa_>
<equa_ valeur="G">
<descr>ABS
</descr>
<descr>ABS_MUX
</descr>
<descr>MK70
</descr>
</equa_>
<equa_ valeur="H">
<descr>ESP_8
</descr>
<descr>ESP
</descr>
<descr>CDS
</descr>
</equa_>
</partcode_>
<comment>Colonne 6 = BV
</comment>
<partcode_ colonne=6>
<equa_ valeur="1">
<descr>BVA
</descr>
<descr>4HP20
</descr>
</equa_>
<equa_ valeur="2">
<descr>BVA
</descr>
<descr>AL4
</descr>
</equa_>
<equa_ valeur="3">
<descr>BVA
</descr>
<descr>BVA_MB3
</descr>
</equa_>
<equa_ valeur="4">
<descr>BVA
</descr>
<descr>AL4
</descr>
<descr>AL4_SHIFT_LOCK
</descr>
</equa_>
<equa_ valeur="6">
<descr>BVA
</descr>
<descr>4HP20_ES9
</descr>
</equa_>
<equa_ valeur="7">
<descr>BVM_LONGUE
</descr>
<descr>BVM
</descr>
</equa_>
<equa_ valeur="8">
<descr>BVM_COURTE
</descr>
<descr>BVM
</descr>
</equa_>
<equa_ valeur="9">
<descr>BVA
</descr>
<descr>EGS2000
</descr>
</equa_>
<equa_ valeur="A">
<descr>BVA
</descr>
<descr>TA2000
</descr>
</equa_>
<equa_ valeur="B">
<descr>BVA
</descr>
<descr>EGS_TELE
</descr>
</equa_>
<equa_ valeur="C">
<descr>BVA
</descr>
<descr>TA_TELE
</descr>
</equa_>
<equa_ valeur="D">
<descr>BVMP
</descr>
<descr>BVM
</descr>
</equa_>
<equa_ valeur="E">
<descr>BVM
</descr>
<descr>MA5.N
</descr>
<descr>BVM_LONGUE
</descr>
</equa_>
<equa_ valeur="F">
<descr>BVM
</descr>
<descr>MA5.S
</descr>
<descr>BVM_COURTE
</descr>
</equa_>
</partcode_>
<comment>Colonne 7 = SUSP/ADAC
</comment>
<partcode_ colonne=7>
<equa_ valeur="1">
<descr>SUSP
</descr>
<descr>NIPPO
</descr>
</equa_>
<equa_ valeur="2">
<descr>SUSP
</descr>
<descr>HYD
</descr>
</equa_>
<equa_ valeur="3">
<descr>SUSP
</descr>
<descr>MECA
</descr>
</equa_>
<equa_ valeur="4">
<descr>SUSP
</descr>
<descr>ACTIVA
</descr>
</equa_>
<equa_ valeur="5">
<descr>SUSP
</descr>
<descr>HYD
</descr>
<descr>HYD_TABLE5
</descr>
</equa_>
<equa_ valeur="6">
<descr>SUSP
</descr>
<descr>ACTIVA
</descr>
<descr>ACTIVA_TABLE1
</descr>
</equa_>
<equa_ valeur="7">
<descr>SUSP
</descr>
<descr>ACTIVA
</descr>
<descr>ACTIVA_TABLE2
</descr>
</equa_>
<equa_ valeur="8">
<descr>DAA
</descr>
<descr>DAAZF
</descr>
<descr>SUSP
</descr>
<descr>NIPPO
</descr>
</equa_>
<equa_ valeur="9">
<descr>DAA
</descr>
<descr>DAAZF
</descr>
</equa_>
<equa_ valeur="A">
<descr>SUSP
</descr>
<descr>DENSO
</descr>
</equa_>
<equa_ valeur="B">
<descr>SUSP
</descr>
<descr>NHC_BASE
</descr>
</equa_>
<equa_ valeur="C">
<descr>SUSP
</descr>
<descr>NHC_HYD
</descr>
</equa_>
<equa_ valeur="D">
<descr>SUSP
</descr>
<descr>NHC_H_DAV_CDSP
</descr>
</equa_>
<equa_ valeur="E">
<descr>GEP
</descr>
</equa_>
<equa_ valeur="F">
<descr>DAE
</descr>
<descr>DAE_LOI_1
</descr>
</equa_>
<equa_ valeur="G">
<descr>DAE
</descr>
<descr>DAE_LOI_2
</descr>
</equa_>
<equa_ valeur="H">
<descr>DAE
</descr>
<descr>DAE_LOI_3
</descr>
</equa_>
<equa_ valeur="J">
<descr>DAE
</descr>
<descr>DAE_LOI_4
</descr>
</equa_>
<equa_ valeur="K">
<descr>DAE
</descr>
<descr>DAE_LOI_5
</descr>
</equa_>
<equa_ valeur="L">
<descr>SUSP
</descr>
<descr>SUSP_RENFORCE
</descr>
</equa_>
</partcode_>
<comment>Colonne 8 = AIRBAG
</comment>
<partcode_ colonne=8>
<equa_ valeur="2">
<descr>AIRBAG
</descr>
<descr>TEMIC
</descr>
</equa_>
<equa_ valeur="3">
<descr>AIRBAG
</descr>
<descr>SAC_EC5
</descr>
</equa_>
<equa_ valeur="4">
<descr>AIRBAG
</descr>
<descr>SAC_TRW
</descr>
</equa_>
<equa_ valeur="5">
<descr>AIRBAG
</descr>
<descr>SAC_AC4_1
</descr>
</equa_>
<equa_ valeur="6">
<descr>AIRBAG
</descr>
<descr>ABF_ABFL
</descr>
</equa_>
<equa_ valeur="7">
<descr>AIRBAG
</descr>
<descr>AIRBAG_SIEMENS
</descr>
</equa_>
<equa_ valeur="8">
<descr>AIRBAG
</descr>
<descr>ACU
</descr>
</equa_>
<equa_ valeur="9">
<descr>AIRBAG
</descr>
<descr>ACU_SANS_PYRO
</descr>
</equa_>
<equa_ valeur="A">
<descr>AIRBAG
</descr>
<descr>ACU_AVEC_PYRO
</descr>
</equa_>
</partcode_>
<comment>Colonne 9 = BSI
</comment>
<partcode_ colonne=9>
<equa_ valeur="1">
<descr>BSI
</descr>
<descr>SS_CONFORMITE
</descr>
<descr>BSI_SIE
</descr>
</equa_>
<equa_ valeur="2">
<descr>BSI
</descr>
<descr>SS_CONFORMITE
</descr>
<descr>BSI_VALEO
</descr>
</equa_>
<equa_ valeur="3">
<descr>BSI
</descr>
<descr>BSI_SAGEM
</descr>
</equa_>
<equa_ valeur="4">
<descr>BSI
</descr>
<descr>BSI_SIE
</descr>
<descr>BSI_SIEB1
</descr>
</equa_>
<equa_ valeur="5">
<descr>BSI
</descr>
<descr>BSI_SIE
</descr>
<descr>BSI_SIEB2
</descr>
</equa_>
<equa_ valeur="6">
<descr>BSI
</descr>
<descr>BSI_SIE
</descr>
<descr>BSI_SIEB4_T16
</descr>
</equa_>
<equa_ valeur="7">
<descr>BSI
</descr>
<descr>BSI_SIE
</descr>
<descr>BSI_SIEB4
</descr>
</equa_>
<equa_ valeur="8">
<descr>TRANSPON_SIEMENS
</descr>
<descr>ADC
</descr>
</equa_>
<equa_ valeur="9">
<descr>TRA_VALEO
</descr>
<descr>ADC
</descr>
</equa_>
<equa_ valeur="A">
<descr>CPH
</descr>
<descr>CPH_TEXTON_CR
</descr>
<descr>CPH_TEXCR1
</descr>
</equa_>
<equa_ valeur="B">
<descr>CPH
</descr>
<descr>CPH_TEXTON_CR
</descr>
<descr>CPH_TEXCR2
</descr>
</equa_>
<equa_ valeur="C">
<descr>CPH
</descr>
<descr>CPH_TEXCR3
</descr>
<descr>CPH_TEXTON_CR
</descr>
</equa_>
<equa_ valeur="D">
<descr>CPH
</descr>
<descr>CPH_TEXT1
</descr>
<descr>CPH_TEXTON
</descr>
</equa_>
<equa_ valeur="E">
<descr>CPH
</descr>
<descr>CPH_TEXT2
</descr>
<descr>CPH_TEXTON
</descr>
</equa_>
<equa_ valeur="F">
<descr>CPH
</descr>
<descr>CPH_TEXT3
</descr>
<descr>CPH_TEXTON
</descr>
</equa_>
<equa_ valeur="G">
<descr>BSI
</descr>
<descr>BSI_VALEO
</descr>
<descr>BSI_VAL_B1
</descr>
</equa_>
<equa_ valeur="H">
<descr>BSI
</descr>
<descr>BSI_VALEO
</descr>
<descr>BSI_VAL_B2
</descr>
</equa_>
<equa_ valeur="J">
<descr>BSI
</descr>
<descr>BSI_VALEO
</descr>
<descr>BSI_VAL_B3
</descr>
</equa_>
<equa_ valeur="K">
<descr>BSI
</descr>
<descr>BSI_VALEO
</descr>
<descr>BSI_VAL_B4
</descr>
</equa_>
<equa_ valeur="L">
<descr>BSI
</descr>
<descr>BSI_VALEO
</descr>
<descr>BSI_VAL_B5
</descr>
</equa_>
<equa_ valeur="M">
<descr>BSI
</descr>
<descr>BSI_VALEO
</descr>
<descr>BSI_VALEO_LIGHT
</descr>
<descr>SS_CONFORMITE
</descr>
</equa_>
<equa_ valeur="N">
<descr>BSI
</descr>
<descr>BSI_NIVEAU_MOYEN
</descr>
</equa_>
</partcode_>
<comment>Colonne 10 = DEV DE PNEU
</comment>
<partcode_ colonne=10>
<equa_ valeur="1">
<descr>1975
</descr>
</equa_>
<equa_ valeur="2">
<descr>2025
</descr>
</equa_>
<equa_ valeur="3">
<descr>2007
</descr>
</equa_>
<equa_ valeur="4">
<descr>1935
</descr>
</equa_>
<equa_ valeur="5">
<descr>1960
</descr>
</equa_>
<equa_ valeur="6">
<descr>1910
</descr>
</equa_>
<equa_ valeur="7">
<descr>1930
</descr>
</equa_>
<equa_ valeur="8">
<descr>1941
</descr>
</equa_>
<equa_ valeur="9">
<descr>1946
</descr>
</equa_>
<equa_ valeur="A">
<descr>1990
</descr>
</equa_>
<equa_ valeur="B">
<descr>2016
</descr>
</equa_>
<equa_ valeur="C">
<descr>1793
</descr>
<descr>1795
</descr>
</equa_>
<equa_ valeur="D">
<descr>1839
</descr>
<descr>1835
</descr>
</equa_>
<equa_ valeur="E">
<descr>1775
</descr>
</equa_>
<equa_ valeur="F">
<descr>1920
</descr>
</equa_>
<equa_ valeur="G">
<descr>1780
</descr>
</equa_>
<equa_ valeur="H">
<descr>1800
</descr>
</equa_>
<equa_ valeur="J">
<descr>1820
</descr>
</equa_>
<equa_ valeur="K">
<descr>1895
</descr>
</equa_>
</partcode_>
<comment>Colonne 11 = AUTORADIO
</comment>
<partcode_ colonne=11>
<equa_ valeur="1">
<descr>RADIO
</descr>
<descr>RB2
</descr>
</equa_>
<equa_ valeur="2">
<descr>RADIO
</descr>
<descr>RM2
</descr>
</equa_>
<equa_ valeur="3">
<descr>RADIO
</descr>
<descr>RD2
</descr>
</equa_>
<equa_ valeur="4">
<descr>RADIO
</descr>
<descr>RB1
</descr>
</equa_>
<equa_ valeur="5">
<descr>RADIO
</descr>
<descr>RD1
</descr>
</equa_>
<equa_ valeur="6">
<descr>RADIO
</descr>
<descr>RT2
</descr>
</equa_>
<equa_ valeur="7">
<descr>RADIO
</descr>
<descr>RB3
</descr>
</equa_>
<equa_ valeur="8">
<descr>RADIO
</descr>
<descr>RD3
</descr>
</equa_>
</partcode_>
<comment>Colonne 12 = PAYS
</comment>
<partcode_ colonne=12>
<equa_ valeur="1">
<descr>EUROPE_OCCIDENTALE
</descr>
</equa_>
<equa_ valeur="2">
<descr>AMERIQUE_LATINE
</descr>
</equa_>
<equa_ valeur="3">
<descr>ASIE
</descr>
</equa_>
<equa_ valeur="4">
<descr>ARABIE
</descr>
</equa_>
<equa_ valeur="5">
<descr>JAPON
</descr>
</equa_>
<equa_ valeur="6">
<descr>CHINE
</descr>
</equa_>
<equa_ valeur="7">
<descr>EUROPE_DE_L_EST
</descr>
</equa_>
<equa_ valeur="8">
<descr>MERCOSUR
</descr>
</equa_>
<equa_ valeur="9">
<descr>AUSTRALIE
</descr>
</equa_>
</partcode_>
<comment>Colonne 13 = ALARME/SUPCO
</comment>
<partcode_ colonne=13>
<equa_ valeur="1">
<descr>ALARME
</descr>
</equa_>
<equa_ valeur="2">
<descr>ALARME
</descr>
<descr>AL_SUPCO
</descr>
<descr>SUPCO
</descr>
</equa_>
<equa_ valeur="3">
<descr>AL_SUPCO
</descr>
<descr>SUPCO
</descr>
</equa_>
<equa_ valeur="4">
<descr>ALARME
</descr>
<descr>ALARME_SUISSE
</descr>
</equa_>
<equa_ valeur="5">
<descr>ALARME
</descr>
<descr>ALARME_SUISSE
</descr>
<descr>ALARME_S_SC
</descr>
<descr>SUPCO
</descr>
</equa_>
<equa_ valeur="6">
<descr>ALARME
</descr>
<descr>ALARME_BELGE
</descr>
</equa_>
<equa_ valeur="7">
<descr>ALARME
</descr>
<descr>ALARME_BELGE
</descr>
<descr>SUPCO
</descr>
</equa_>
</partcode_>
<comment>Colonne 14 = DEPOLLUTION
</comment>
<partcode_ colonne=14>
<equa_ valeur="1">
<descr>L3
</descr>
</equa_>
<equa_ valeur="2">
<descr>L4
</descr>
</equa_>
<equa_ valeur="3">
<descr>L5
</descr>
</equa_>
<equa_ valeur="4">
<descr>W4
</descr>
</equa_>
<equa_ valeur="5">
<descr>W3
</descr>
</equa_>
<equa_ valeur="6">
<descr>L4_INF
</descr>
</equa_>
<equa_ valeur="7">
<descr>K
</descr>
</equa_>
<equa_ valeur="8">
<descr>IFL5
</descr>
</equa_>
<equa_ valeur="9">
<descr>US94
</descr>
</equa_>
</partcode_>
<comment>Colonne 15 = FRIC
</comment>
<partcode_ colonne=15>
<equa_ valeur="1">
<descr>FRIC
</descr>
<descr>FRIC_D9
</descr>
</equa_>
<equa_ valeur="2">
<descr>FRIC
</descr>
<descr>FRIC_0
</descr>
</equa_>
<equa_ valeur="3">
<descr>FRIC
</descr>
<descr>FRIC_A
</descr>
</equa_>
<equa_ valeur="4">
<descr>FRIC
</descr>
<descr>FRIC_A0
</descr>
</equa_>
<equa_ valeur="5">
<descr>FRIC
</descr>
<descr>FRIC_B1
</descr>
</equa_>
<equa_ valeur="6">
<descr>FRIC
</descr>
<descr>FRIC_B2
</descr>
</equa_>
<equa_ valeur="7">
<descr>FRIC
</descr>
<descr>FRIC_C
</descr>
</equa_>
<equa_ valeur="8">
<descr>FRIC
</descr>
<descr>FRIC_C0
</descr>
</equa_>
<equa_ valeur="9">
<descr>FRIC
</descr>
<descr>FRIC_B3
</descr>
</equa_>
</partcode_>
<comment>Colonne 16 = ALTERNATEUR
</comment>
<partcode_ colonne=16>
<equa_ valeur="1">
<descr>CLASSE7
</descr>
</equa_>
<equa_ valeur="2">
<descr>CLASSE8
</descr>
</equa_>
<equa_ valeur="3">
<descr>CLASSE9
</descr>
</equa_>
<equa_ valeur="4">
<descr>CLASSE12
</descr>
</equa_>
<equa_ valeur="5">
<descr>CLASSE15
</descr>
</equa_>
<equa_ valeur="6">
<descr>CLASSE6
</descr>
</equa_>
<equa_ valeur="7">
<descr>CLASSE8+
</descr>
</equa_>
</partcode_>
<comment>Colonne 17 = TYPE AIR-BAG
</comment>
<partcode_ colonne=17>
<equa_ valeur="1">
<descr>AIRBAG
</descr>
<descr>CONDUCTEUR
</descr>
<descr>SEUL
</descr>
<descr>TEL3ALL
</descr>
</equa_>
<equa_ valeur="2">
<descr>AIRBAG
</descr>
<descr>CONDUCTEUR
</descr>
<descr>PASSAGER
</descr>
<descr>TEL4ALL
</descr>
</equa_>
<equa_ valeur="3">
<descr>AIRBAG
</descr>
<descr>CONDUCTEUR
</descr>
<descr>PASSAGER
</descr>
<descr>INHIB_PASSAGER
</descr>
<descr>TEL4INHIB
</descr>
</equa_>
<equa_ valeur="4">
<descr>AIRBAG
</descr>
<descr>CONDUCTEUR
</descr>
<descr>PASSAGER
</descr>
<descr>LATERAL
</descr>
<descr>TEL4ALL
</descr>
</equa_>
<equa_ valeur="5">
<descr>AIRBAG
</descr>
<descr>CONDUCTEUR
</descr>
<descr>PASSAGER
</descr>
<descr>LATERAL
</descr>
<descr>INHIB_PASSAGER
</descr>
<descr>TEL4INHIB
</descr>
</equa_>
<equa_ valeur="6">
<descr>AIRBAG
</descr>
<descr>CONDUCTEUR
</descr>
<descr>LATERAL
</descr>
<descr>TEL3ALL
</descr>
</equa_>
<equa_ valeur="7">
<descr>AIRBAG
</descr>
<descr>CONDUCTEUR
</descr>
<descr>PASSAGER
</descr>
<descr>LATERAL
</descr>
<descr>RID
</descr>
<descr>INHIB_PASSAGER
</descr>
</equa_>
<equa_ valeur="8">
<descr>AIRBAG
</descr>
<descr>CONDUCTEUR
</descr>
<descr>PASSAGER
</descr>
<descr>LATERAL
</descr>
<descr>RID
</descr>
<descr>INHIB_PASSAGER
</descr>
<descr>AIRBAG_GENOUX
</descr>
</equa_>
<equa_ valeur="9">
<descr>AIRBAG
</descr>
<descr>CONDUCTEUR
</descr>
<descr>PASSAGER
</descr>
<descr>LATERAL
</descr>
<descr>RID
</descr>
<descr>AIRBAG_GENOUX
</descr>
</equa_>
</partcode_>
<comment>Colonne 18 = CHAUF ADD
</comment>
<partcode_ colonne=18>
<equa_ valeur="0">
<descr>CHAUF_A0
</descr>
</equa_>
<equa_ valeur="1">
<descr>CHAUF_ADD
</descr>
<descr>CHAUF_A1
</descr>
</equa_>
<equa_ valeur="2">
<descr>CHAUF_ADD
</descr>
<descr>CHAUF_A2
</descr>
</equa_>
<equa_ valeur="3">
<descr>CHAUF_ADD
</descr>
<descr>CHAUF_A3
</descr>
</equa_>
<equa_ valeur="4">
<descr>CHAUF_ADD
</descr>
<descr>CHAUF_A4
</descr>
</equa_>
<equa_ valeur="5">
<descr>CHAUF_ADD
</descr>
<descr>CHAUF_A5
</descr>
</equa_>
</partcode_>
<comment>Colonne 19 = NBRE DE CLES
</comment>
<partcode_ colonne=19>
<equa_ valeur="1">
<descr>NbCle2
</descr>
</equa_>
<equa_ valeur="2">
<descr>NbCle3
</descr>
</equa_>
<equa_ valeur="3">
<descr>NbCle2
</descr>
<descr>AvecPlip
</descr>
<descr>NbPlip1
</descr>
<descr>AvecAncienPlip
</descr>
</equa_>
<equa_ valeur="4">
<descr>NbCle3
</descr>
<descr>AvecPlip
</descr>
<descr>NbPlip1
</descr>
</equa_>
<equa_ valeur="5">
<descr>NbCle2
</descr>
<descr>AvecPlip
</descr>
<descr>NbPlip2
</descr>
<descr>AvecAncienPlip
</descr>
</equa_>
<equa_ valeur="6">
<descr>NbCle3
</descr>
<descr>AvecPlip
</descr>
<descr>NbPlip2
</descr>
</equa_>
<equa_ valeur="7">
<descr>NbCle2
</descr>
<descr>AvecPlip
</descr>
<descr>NbPlip1
</descr>
<descr>AvecNouveauPlip
</descr>
</equa_>
<equa_ valeur="8">
<descr>NbCle2
</descr>
<descr>AvecPlip
</descr>
<descr>NbPlip2
</descr>
<descr>AvecNouveauPlip
</descr>
</equa_>
</partcode_>
<comment>Colonne 20 = CARROSSERIE
</comment>
<partcode_ colonne=20>
<equa_ valeur="1">
<descr>BERL_5_PORTES
</descr>
<descr>0A
</descr>
</equa_>
<equa_ valeur="2">
<descr>BREAK
</descr>
<descr>0B
</descr>
</equa_>
<equa_ valeur="3">
<descr>COUPE
</descr>
<descr>0C
</descr>
</equa_>
<equa_ valeur="4">
<descr>BERL_3_PORTES
</descr>
</equa_>
<equa_ valeur="5">
<descr>CABRIOLET
</descr>
</equa_>
<equa_ valeur="6">
<descr>UTILITAIRE
</descr>
</equa_>
<equa_ valeur="7">
<descr>MONOSPACE_FAM
</descr>
</equa_>
</partcode_>
<comment>Colonne 21 = Refri
</comment>
<partcode_ colonne=21>
<equa_ valeur="0">
<descr>NO REFRI
</descr>
</equa_>
<equa_ valeur="1">
<descr>REFRI
</descr>
<descr>REFRI_RF
</descr>
</equa_>
<equa_ valeur="2">
<descr>REFRI
</descr>
<descr>REFRI_RFTD
</descr>
</equa_>
<equa_ valeur="3">
<descr>REFRI
</descr>
<descr>REFRI_RFTDV
</descr>
</equa_>
<equa_ valeur="4">
<descr>REFRI
</descr>
<descr>REFRI_RF
</descr>
<descr>Gd_Froid
</descr>
</equa_>
<equa_ valeur="5">
<descr>REFRI
</descr>
<descr>Gd_Froid
</descr>
<descr>REFRI_RFTDV
</descr>
</equa_>
<equa_ valeur="6">
<descr>REFRI
</descr>
<descr>REFRI_RFTD
</descr>
<descr>Gd_Froid
</descr>
</equa_>
<equa_ valeur="7">
<descr>REFRI
</descr>
<descr>Gd_Froid
</descr>
</equa_>
<equa_ valeur="8">
<descr>REFRI
</descr>
<descr>REFRI_RFTA
</descr>
</equa_>
<equa_ valeur="9">
<descr>REFRI
</descr>
<descr>REFRI_RFTA
</descr>
<descr>Gd_Froid
</descr>
</equa_>
</partcode_>
<comment>Colonne 22 = SIEGE/AAS/CATALYSEUR
</comment>
<partcode_ colonne=22>
<equa_ valeur="1">
<descr>RETRO_SIEGE
</descr>
<descr>BITRON
</descr>
</equa_>
<equa_ valeur="2">
<descr>CATALYSEUR_PALLADIUM
</descr>
</equa_>
<equa_ valeur="3">
<descr>AAS
</descr>
</equa_>
<equa_ valeur="4">
<descr>AAS
</descr>
<descr>RETRO_SIEGE
</descr>
<descr>BITRON
</descr>
</equa_>
<equa_ valeur="5">
<descr>RETRO_SIEGE
</descr>
<descr>BITRON
</descr>
<descr>CATALYSEUR_PALLADIUM
</descr>
</equa_>
<equa_ valeur="6">
<descr>AAS
</descr>
<descr>CATALYSEUR_PALLADIUM
</descr>
</equa_>
<equa_ valeur="7">
<descr>AAS
</descr>
<descr>RETRO_SIEGE
</descr>
<descr>BITRON
</descr>
<descr>CATALYSEUR_PALLADIUM
</descr>
</equa_>
</partcode_>
<comment>Colonne 23 = NAV
</comment>
<partcode_ colonne=23>
<equa_ valeur="1">
<descr>NAV
</descr>
</equa_>
<equa_ valeur="2">
<descr>NAV
</descr>
<descr>CD
</descr>
</equa_>
<equa_ valeur="3">
<descr>CD
</descr>
</equa_>
<equa_ valeur="4">
<descr>TELEMATIQUE
</descr>
<descr>Telematique_1
</descr>
</equa_>
<equa_ valeur="5">
<descr>TELEMATIQUE
</descr>
<descr>Telematique_2
</descr>
</equa_>
<equa_ valeur="6">
<descr>TELEMATIQUE
</descr>
<descr>Telematique_3
</descr>
</equa_>
<equa_ valeur="7">
<descr>TELEMATIQUE
</descr>
<descr>Telematique_1
</descr>
<descr>CD
</descr>
</equa_>
<equa_ valeur="8">
<descr>TELEMATIQUE
</descr>
<descr>Telematique_2
</descr>
<descr>CD
</descr>
</equa_>
<equa_ valeur="9">
<descr>TELEMATIQUE
</descr>
<descr>Telematique_3
</descr>
<descr>CD
</descr>
</equa_>
</partcode_>
<comment>Colonne 24 = ECRAN
</comment>
<partcode_ colonne=24>
<equa_ valeur="1">
<descr>AFFICHEUR
</descr>
<descr>A
</descr>
<descr>ECMULT
</descr>
</equa_>
<equa_ valeur="2">
<descr>AFFICHEUR
</descr>
<descr>B
</descr>
<descr>ECMULT
</descr>
</equa_>
<equa_ valeur="3">
<descr>AFFICHEUR
</descr>
<descr>C
</descr>
<descr>ECMULT
</descr>
</equa_>
<equa_ valeur="4">
<descr>AFFICHEUR
</descr>
<descr>D
</descr>
<descr>ECMULT
</descr>
</equa_>
<equa_ valeur="5">
<descr>AFFICHEUR
</descr>
<descr>ECRAN_16_9
</descr>
</equa_>
</partcode_>
<comment>Colonne 25 = Variantes S2/S8
</comment>
<partcode_ colonne=25>
<appl>
<pour>
<descr>S2
</descr>
</pour>
<pour>
<descr>S8
</descr>
</pour>
</appl>
<equa_ valeur="2">
<descr>PAPILLON_MOTORISE
</descr>
</equa_>
</partcode_>
<comment>Colonne 25 = TABLE AUTORADIO pour T5/D9-2001
</comment>
<partcode_ colonne=25>
<appl>
<pour>
<descr>T5
</descr>
</pour>
<pour>
<descr>D9
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>EMF_T_EXT
</descr>
</equa_>
<equa_ valeur="2">
<descr>EMF_ODB
</descr>
</equa_>
<equa_ valeur="3">
<descr>EMF_T_EXT
</descr>
<descr>EMF_ODB
</descr>
</equa_>
<equa_ valeur="4">
<descr>ASSERVISSEMENT_VIT
</descr>
</equa_>
<equa_ valeur="5">
<descr>ASSERVISSEMENT_VIT
</descr>
<descr>EMF_T_EXT
</descr>
</equa_>
<equa_ valeur="6">
<descr>ASSERVISSEMENT_VIT
</descr>
<descr>EMF_ODB
</descr>
</equa_>
<equa_ valeur="7">
<descr>ASSERVISSEMENT_VIT
</descr>
<descr>EMF_ODB
</descr>
<descr>EMF_T_EXT
</descr>
</equa_>
</partcode_>
<comment>Colonne 25 = AUTORADIO pour T1 MUX, T3
</comment>
<partcode_ colonne=25>
<appl>
<pour>
<descr>T1_MUX
</descr>
</pour>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>T3
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>EMF_T_EXT
</descr>
</equa_>
<equa_ valeur="2">
<descr>EMF_ODB
</descr>
</equa_>
<equa_ valeur="3">
<descr>EMF_T_EXT
</descr>
<descr>EMF_ODB
</descr>
</equa_>
<equa_ valeur="4">
<descr>ASSERVISSEMENT_VIT
</descr>
</equa_>
<equa_ valeur="5">
<descr>ASSERVISSEMENT_VIT
</descr>
<descr>EMF_T_EXT
</descr>
</equa_>
<equa_ valeur="6">
<descr>ASSERVISSEMENT_VIT
</descr>
<descr>EMF_ODB
</descr>
</equa_>
<equa_ valeur="7">
<descr>ASSERVISSEMENT_VIT
</descr>
<descr>EMF_ODB
</descr>
<descr>EMF_T_EXT
</descr>
</equa_>
</partcode_>
<comment>Colonne 25 = AUTORADIO pour N68_MUX et M59
</comment>
<partcode_ colonne=25>
<appl>
<pour>
<descr>N68_MUX
</descr>
</pour>
<pour>
<descr>M59
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>T_Ext
</descr>
</equa_>
<equa_ valeur="2">
<descr>ODB
</descr>
</equa_>
<equa_ valeur="3">
<descr>T_Ext
</descr>
<descr>ODB
</descr>
</equa_>
<equa_ valeur="4">
<descr>ASSERVISSEMENT_VIT
</descr>
</equa_>
<equa_ valeur="5">
<descr>ASSERVISSEMENT_VIT
</descr>
<descr>T_Ext
</descr>
</equa_>
<equa_ valeur="6">
<descr>ASSERVISSEMENT_VIT
</descr>
<descr>ODB
</descr>
</equa_>
<equa_ valeur="7">
<descr>ASSERVISSEMENT_VIT
</descr>
<descr>ODB
</descr>
<descr>T_Ext
</descr>
</equa_>
</partcode_>
<comment>Colonne 25 = TABLE AUTO/RADIO pour Z8
</comment>
<partcode_ colonne=25>
<appl>
<pour>
<descr>Z8
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ASSERVISSEMENT_VIT
</descr>
</equa_>
<equa_ valeur="2">
<descr>4HautParleur
</descr>
</equa_>
<equa_ valeur="3">
<descr>4HautParleur
</descr>
<descr>ASSERVISSEMENT_VIT
</descr>
</equa_>
<equa_ valeur="4">
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="5">
<descr>ASSERVISSEMENT_VIT
</descr>
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="6">
<descr>4HautParleur
</descr>
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="7">
<descr>4HautParleur
</descr>
<descr>HIFI
</descr>
<descr>ASSERVISSEMENT_VIT
</descr>
</equa_>
</partcode_>
<comment>Colonne 25 = TABLE AUTO/RADIO pour N68 M49
</comment>
<partcode_ colonne=25>
<appl>
<pour>
<descr>N68
</descr>
</pour>
<pour>
<descr>M49
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ACTIVE_FADER
</descr>
</equa_>
<equa_ valeur="2">
<descr>ASSERVISSEMENT_VIT
</descr>
</equa_>
<equa_ valeur="3">
<descr>ACTIVE_FADER
</descr>
<descr>ASSERVISSEMENT_VIT
</descr>
</equa_>
</partcode_>
<comment>Colonne 25 = TABLE AUTO/RADIO pour X4
</comment>
<partcode_ colonne=25>
<appl>
<pour>
<descr>X4
</descr>
</pour>
<pour>
<descr>X41
</descr>
</pour>
<pour>
<descr>X42
</descr>
</pour>
</appl>
<equa_ valeur="4">
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="5">
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="6">
<descr>HIFI
</descr>
<descr>CD
</descr>
</equa_>
<equa_ valeur="7">
<descr>HIFI
</descr>
<descr>CD
</descr>
</equa_>
</partcode_>
<comment>Colonne 25 = TABLE AUTO/RADIO pour N7
</comment>
<partcode_ colonne=25>
<appl>
<pour>
<descr>N7
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ACTIVE_FADER
</descr>
</equa_>
<equa_ valeur="2">
<descr>ASSERVISSEMENT_VIT
</descr>
</equa_>
<equa_ valeur="3">
<descr>ACTIVE_FADER
</descr>
<descr>ASSERVISSEMENT_VIT
</descr>
</equa_>
<equa_ valeur="4">
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="5">
<descr>ACTIVE_FADER
</descr>
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="6">
<descr>ASSERVISSEMENT_VIT
</descr>
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="7">
<descr>ACTIVE_FADER
</descr>
<descr>ASSERVISSEMENT_VIT
</descr>
<descr>HIFI
</descr>
</equa_>
</partcode_>
<comment>Colonne 25 = AUTORADIO pour V
</comment>
<partcode_ colonne=25>
<appl>
<pour>
<descr>V
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ASSERVISSEMENT_VIT
</descr>
</equa_>
<equa_ valeur="3">
<descr>ASSERVISSEMENT_VIT
</descr>
</equa_>
<equa_ valeur="4">
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="5">
<descr>ASSERVISSEMENT_VIT
</descr>
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="6">
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="7">
<descr>HIFI
</descr>
<descr>ASSERVISSEMENT_VIT
</descr>
</equa_>
</partcode_>
<comment>Colonne 25 = AUTORADIO/EMF pour A8
</comment>
<partcode_ colonne=25>
<appl>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>A08
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>EMF_T_EXT
</descr>
</equa_>
<equa_ valeur="3">
<descr>EMF_T_EXT
</descr>
</equa_>
<equa_ valeur="4">
<descr>ASSERVISSEMENT_VIT
</descr>
</equa_>
<equa_ valeur="5">
<descr>ASSERVISSEMENT_VIT
</descr>
<descr>EMF_T_EXT
</descr>
</equa_>
<equa_ valeur="6">
<descr>ASSERVISSEMENT_VIT
</descr>
</equa_>
<equa_ valeur="7">
<descr>ASSERVISSEMENT_VIT
</descr>
<descr>EMF_T_EXT
</descr>
</equa_>
</partcode_>
<comment>Colonne 26 = AUTORADIO pour T5/D9-2001
</comment>
<partcode_ colonne=26>
<appl>
<pour>
<descr>T5
</descr>
</pour>
<pour>
<descr>D9
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ACTIVE_FADER
</descr>
</equa_>
<equa_ valeur="2">
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="3">
<descr>ACTIVE_FADER
</descr>
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="4">
<descr>POLICE
</descr>
</equa_>
<equa_ valeur="5">
<descr>ACTIVE_FADER
</descr>
<descr>POLICE
</descr>
</equa_>
<equa_ valeur="6">
<descr>HIFI
</descr>
<descr>POLICE
</descr>
</equa_>
<equa_ valeur="7">
<descr>ACTIVE_FADER
</descr>
<descr>HIFI
</descr>
<descr>POLICE
</descr>
</equa_>
</partcode_>
<comment>Colonne 26 = AUTORADIO pour T1 MUX, T3
</comment>
<partcode_ colonne=26>
<appl>
<pour>
<descr>T1_MUX
</descr>
</pour>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>T3
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ACTIVE_FADER
</descr>
</equa_>
<equa_ valeur="2">
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="3">
<descr>ACTIVE_FADER
</descr>
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="4">
<descr>POLICE
</descr>
</equa_>
<equa_ valeur="5">
<descr>ACTIVE_FADER
</descr>
<descr>POLICE
</descr>
</equa_>
<equa_ valeur="6">
<descr>HIFI
</descr>
<descr>POLICE
</descr>
</equa_>
<equa_ valeur="7">
<descr>ACTIVE_FADER
</descr>
<descr>HIFI
</descr>
<descr>POLICE
</descr>
</equa_>
</partcode_>
<comment>Colonne 26 = AUTORADIO pour N68_MUX
</comment>
<partcode_ colonne=26>
<appl>
<pour>
<descr>N68_MUX
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ACTIVE_FADER
</descr>
</equa_>
<equa_ valeur="2">
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="3">
<descr>ACTIVE_FADER
</descr>
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="4">
<descr>CP1H
</descr>
</equa_>
<equa_ valeur="5">
<descr>ACTIVE_FADER
</descr>
<descr>CP1H
</descr>
</equa_>
<equa_ valeur="6">
<descr>HIFI
</descr>
<descr>CP1H
</descr>
</equa_>
<equa_ valeur="7">
<descr>ACTIVE_FADER
</descr>
<descr>HIFI
</descr>
<descr>CP1H
</descr>
</equa_>
</partcode_>
<comment>Colonne 26 = AUTORADIO pour M59
</comment>
<partcode_ colonne=26>
<appl>
<pour>
<descr>M59
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ACTIVE_FADER
</descr>
</equa_>
<equa_ valeur="2">
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="3">
<descr>ACTIVE_FADER
</descr>
<descr>HIFI
</descr>
</equa_>
<equa_ valeur="4">
<descr>LOI_VOLUME_1
</descr>
</equa_>
<equa_ valeur="5">
<descr>ACTIVE_FADER
</descr>
<descr>LOI_VOLUME_1
</descr>
</equa_>
<equa_ valeur="6">
<descr>HIFI
</descr>
<descr>LOI_VOLUME_1
</descr>
</equa_>
<equa_ valeur="7">
<descr>ACTIVE_FADER
</descr>
<descr>HIFI
</descr>
<descr>LOI_VOLUME_1
</descr>
</equa_>
</partcode_>
<comment>Colonne 26 = COMBINE pour Z8
</comment>
<partcode_ colonne=26>
<appl>
<pour>
<descr>Z8
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>INDICATEUR_MAINTENANCE
</descr>
</equa_>
<equa_ valeur="2">
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="3">
<descr>INDICATEUR_MAINTENANCE
</descr>
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="4">
<descr>TEMOIN_BVA
</descr>
</equa_>
<equa_ valeur="5">
<descr>INDICATEUR_MAINTENANCE
</descr>
<descr>TEMOIN_BVA
</descr>
</equa_>
<equa_ valeur="6">
<descr>NIVEAU_HUILE
</descr>
<descr>TEMOIN_BVA
</descr>
</equa_>
<equa_ valeur="7">
<descr>INDICATEUR_MAINTENANCE
</descr>
<descr>NIVEAU_HUILE
</descr>
<descr>TEMOIN_BVA
</descr>
</equa_>
</partcode_>
<comment>Colonne 26 = COMBINE1 pour N68 M49
</comment>
<partcode_ colonne=26>
<appl>
<pour>
<descr>N68
</descr>
</pour>
<pour>
<descr>M49
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="2">
<descr>MILES
</descr>
</equa_>
<equa_ valeur="3">
<descr>MILES
</descr>
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="4">
<descr>A-COMPLETER
</descr>
</equa_>
<equa_ valeur="5">
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="6">
<descr>MILES
</descr>
</equa_>
<equa_ valeur="7">
<descr>MILES
</descr>
<descr>NIVEAU_HUILE
</descr>
</equa_>
</partcode_>
<comment>Colonne 26 = COMBINE1 pour N7
</comment>
<partcode_ colonne=26>
<appl>
<pour>
<descr>N7
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="2">
<descr>TEMOIN_ABS
</descr>
</equa_>
<equa_ valeur="3">
<descr>TEMOIN_ABS
</descr>
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="4">
<descr>MAINTENANCE_SEVERE
</descr>
</equa_>
<equa_ valeur="5">
<descr>MAINTENANCE_SEVERE
</descr>
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="6">
<descr>MAINTENANCE_SEVERE
</descr>
<descr>TEMOIN_ABS
</descr>
</equa_>
<equa_ valeur="7">
<descr>MAINTENANCE_SEVERE
</descr>
<descr>TEMOIN_ABS
</descr>
<descr>NIVEAU_HUILE
</descr>
</equa_>
</partcode_>
<comment>Colonne 26 = AUTORADIO pour A8
</comment>
<partcode_ colonne=26>
<appl>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>A08
</descr>
</pour>
</appl>
<equa_ valeur="4">
<descr>POLICE
</descr>
</equa_>
<equa_ valeur="5">
<descr>POLICE
</descr>
</equa_>
<equa_ valeur="6">
<descr>POLICE
</descr>
</equa_>
<equa_ valeur="7">
<descr>POLICE
</descr>
</equa_>
</partcode_>
<comment>Colonne 27 = CONF BSI1 T5/D9-2001
</comment>
<partcode_ colonne=27>
<appl>
<pour>
<descr>T5
</descr>
</pour>
<pour>
<descr>D9
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>SS_INHIB_AIRBAG
</descr>
</equa_>
<equa_ valeur="2">
<descr>POMPE_A_AIR
</descr>
</equa_>
<equa_ valeur="3">
<descr>POMPE_A_AIR
</descr>
<descr>SS_INHIB_AIRBAG
</descr>
</equa_>
<equa_ valeur="4">
<descr>CONDA_EN_ROULANT
</descr>
</equa_>
<equa_ valeur="5">
<descr>CONDA_EN_ROULANT
</descr>
<descr>SS_INHIB_AIRBAG
</descr>
</equa_>
<equa_ valeur="6">
<descr>CONDA_EN_ROULANT
</descr>
<descr>POMPE_A_AIR
</descr>
</equa_>
<equa_ valeur="7">
<descr>CONDA_EN_ROULANT
</descr>
<descr>POMPE_A_AIR
</descr>
<descr>SS_INHIB_AIRBAG
</descr>
</equa_>
</partcode_>
<comment>Colonne 27 = CONF BSI1 T1 MUX, T3
</comment>
<partcode_ colonne=27>
<appl>
<pour>
<descr>T1_MUX
</descr>
</pour>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>T3
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>OUBLI_SON_CEINTURE
</descr>
</equa_>
<equa_ valeur="2">
<descr>LV_SEQUENTIEL_D
</descr>
</equa_>
<equa_ valeur="3">
<descr>LV_SEQUENTIEL_D
</descr>
<descr>OUBLI_SON_CEINTURE
</descr>
</equa_>
<equa_ valeur="4">
<descr>LV_SEQUENTIEL_G
</descr>
</equa_>
<equa_ valeur="5">
<descr>LV_SEQUENTIEL_G
</descr>
<descr>OUBLI_SON_CEINTURE
</descr>
</equa_>
<equa_ valeur="6">
<descr>LV_SEQUENTIEL_G
</descr>
<descr>LV_SEQUENTIEL_D
</descr>
</equa_>
<equa_ valeur="7">
<descr>LV_SEQUENTIEL_G
</descr>
<descr>LV_SEQUENTIEL_D
</descr>
<descr>OUBLI_SON_CEINTURE
</descr>
</equa_>
</partcode_>
<comment>Colonne 27 = CONF BSI1 Z8
</comment>
<partcode_ colonne=27>
<appl>
<pour>
<descr>Z8
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>HOMOLOGATION
</descr>
</equa_>
<equa_ valeur="2">
<descr>SUPCO
</descr>
</equa_>
<equa_ valeur="3">
<descr>HOMOLOGATION
</descr>
<descr>SUPCO
</descr>
</equa_>
<equa_ valeur="4">
<descr>ALARME
</descr>
</equa_>
<equa_ valeur="5">
<descr>HOMOLOGATION
</descr>
<descr>ALARME
</descr>
</equa_>
<equa_ valeur="6">
<descr>SUPCO
</descr>
<descr>ALARME
</descr>
</equa_>
<equa_ valeur="7">
<descr>HOMOLOGATION
</descr>
<descr>SUPCO
</descr>
<descr>ALARME
</descr>
</equa_>
</partcode_>
<comment>Colonne 27 = COMBINE2 pour N68 M49
</comment>
<partcode_ colonne=27>
<appl>
<pour>
<descr>N68
</descr>
</pour>
<pour>
<descr>M49
</descr>
</pour>
</appl>
<equa_ valeur="2">
<descr>RESERVOIR_DIESEL
</descr>
</equa_>
<equa_ valeur="3">
<descr>RESERVOIR_DIESEL
</descr>
</equa_>
<equa_ valeur="4">
<descr>TEMOIN_ABS
</descr>
</equa_>
<equa_ valeur="5">
<descr>TEMOIN_ABS
</descr>
</equa_>
<equa_ valeur="6">
<descr>TEMOIN_ABS
</descr>
<descr>RESERVOIR_DIESEL
</descr>
</equa_>
<equa_ valeur="7">
<descr>TEMOIN_ABS
</descr>
<descr>RESERVOIR_DIESEL
</descr>
</equa_>
</partcode_>
<comment>Colonne 27 = COMBINE2 pour N7
</comment>
<partcode_ colonne=27>
<appl>
<pour>
<descr>N7
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>10000_Km
</descr>
</equa_>
<equa_ valeur="2">
<descr>12500_Km
</descr>
</equa_>
<equa_ valeur="3">
<descr>10000_Km
</descr>
<descr>12500_Km
</descr>
</equa_>
<equa_ valeur="4">
<descr>15000_Km
</descr>
</equa_>
<equa_ valeur="5">
<descr>15000_Km
</descr>
<descr>10000_Km
</descr>
</equa_>
<equa_ valeur="6">
<descr>15000_Km
</descr>
<descr>12500_Km
</descr>
</equa_>
<equa_ valeur="7">
<descr>15000_Km
</descr>
<descr>12500_Km
</descr>
<descr>10000_Km
</descr>
</equa_>
</partcode_>
<comment>Colonne 27 = CONF BSI1 pour X4
</comment>
<partcode_ colonne=27>
<appl>
<pour>
<descr>X4
</descr>
</pour>
<pour>
<descr>X41
</descr>
</pour>
<pour>
<descr>X42
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>SUPCO
</descr>
</equa_>
<equa_ valeur="2">
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="3">
<descr>LAVE_PROJECTEUR
</descr>
<descr>SUPCO
</descr>
</equa_>
<equa_ valeur="4">
<descr>ECLAIRAGE_AUTOMATIQUE
</descr>
</equa_>
<equa_ valeur="5">
<descr>ECLAIRAGE_AUTOMATIQUE
</descr>
<descr>SUPCO
</descr>
</equa_>
<equa_ valeur="6">
<descr>ECLAIRAGE_AUTOMATIQUE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="7">
<descr>ECLAIRAGE_AUTOMATIQUE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
<descr>SUPCO
</descr>
</equa_>
</partcode_>
<comment>Colonne 27 = CONF BSI pour V
</comment>
<partcode_ colonne=27>
<appl>
<pour>
<descr>V
</descr>
</pour>
</appl>
<equa_ valeur="2">
<descr>LV_ANTIPINC
</descr>
</equa_>
<equa_ valeur="4">
<descr>PLC
</descr>
</equa_>
<equa_ valeur="6">
<descr>PLC
</descr>
<descr>LV_ANTIPINC
</descr>
</equa_>
<equa_ valeur="7">
<descr>PLC
</descr>
<descr>LV_ANTIPINC
</descr>
</equa_>
</partcode_>
<comment>Colonne 27 = CONF BSI1 pour N68MUX
</comment>
<partcode_ colonne=27>
<appl>
<pour>
<descr>N68_MUX
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>RVV2
</descr>
</equa_>
<equa_ valeur="2">
<descr>LIMITEUR_VITESSE
</descr>
</equa_>
<equa_ valeur="3">
<descr>LIMITEUR_VITESSE
</descr>
<descr>RVV2
</descr>
</equa_>
<equa_ valeur="4">
<descr>REGULATION_VITESSE
</descr>
</equa_>
<equa_ valeur="5">
<descr>REGULATION_VITESSE
</descr>
<descr>RVV2
</descr>
</equa_>
<equa_ valeur="6">
<descr>LIMITEUR_VITESSE
</descr>
<descr>REGULATION_VITESSE
</descr>
</equa_>
<equa_ valeur="7">
<descr>LIMITEUR_VITESSE
</descr>
<descr>REGULATION_VITESSE
</descr>
<descr>RVV2
</descr>
</equa_>
</partcode_>
<comment>Colonne 27 = CONF BSI1 pour M59
</comment>
<partcode_ colonne=27>
<appl>
<pour>
<descr>M59
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="2">
<descr>VOYANT_ABS_PASSIF
</descr>
</equa_>
<equa_ valeur="3">
<descr>VOYANT_ABS_PASSIF
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="4">
<descr>REGULATION_VITESSE
</descr>
</equa_>
<equa_ valeur="5">
<descr>REGULATION_VITESSE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="6">
<descr>VOYANT_ABS_PASSIF
</descr>
<descr>REGULATION_VITESSE
</descr>
</equa_>
<equa_ valeur="7">
<descr>VOYANT_ABS_PASSIF
</descr>
<descr>REGULATION_VITESSE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
</partcode_>
<comment>Colonne 27 = CONF BSI1 A8
</comment>
<partcode_ colonne=27>
<appl>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>A08
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>SECU_ENFANT
</descr>
</equa_>
<equa_ valeur="3">
<descr>SECU_ENFANT
</descr>
</equa_>
<equa_ valeur="4">
<descr>LV_SEQUENTIEL
</descr>
<descr>LV_SEQUENTIEL_G
</descr>
<descr>LV_SEQUENTIEL_D
</descr>
</equa_>
<equa_ valeur="5">
<descr>SECU_ENFANT
</descr>
<descr>LV_SEQUENTIEL
</descr>
<descr>LV_SEQUENTIEL_D
</descr>
<descr>LV_SEQUENTIEL_G
</descr>
</equa_>
<equa_ valeur="6">
<descr>LV_SEQUENTIEL
</descr>
<descr>LV_SEQUENTIEL_G
</descr>
<descr>LV_SEQUENTIEL_D
</descr>
</equa_>
<equa_ valeur="7">
<descr>LV_SEQUENTIEL
</descr>
<descr>LV_SEQUENTIEL_G
</descr>
<descr>LV_SEQUENTIEL_D
</descr>
<descr>SECU_ENFANT
</descr>
</equa_>
</partcode_>
<comment>Colonne 28 = CONF BSI2 T5/D9-2001
</comment>
<partcode_ colonne=28>
<appl>
<pour>
<descr>T5
</descr>
</pour>
<pour>
<descr>D9
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>DIRECTION_DROITE
</descr>
</equa_>
<equa_ valeur="2">
<descr>ECLAIRAGE_AUTOMATIQUE
</descr>
</equa_>
<equa_ valeur="3">
<descr>DIRECTION_DROITE
</descr>
<descr>ECLAIRAGE_AUTOMATIQUE
</descr>
</equa_>
<equa_ valeur="4">
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="5">
<descr>DIRECTION_DROITE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="6">
<descr>ECLAIRAGE_AUTOMATIQUE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="7">
<descr>DIRECTION_DROITE
</descr>
<descr>ECLAIRAGE_AUTOMATIQUE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
</partcode_>
<comment>Colonne 28 = CONF BSI2 T1 MUX, A8 et T3
</comment>
<partcode_ colonne=28>
<appl>
<pour>
<descr>T1_MUX
</descr>
</pour>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>A08
</descr>
</pour>
<pour>
<descr>T3
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>DIRECTION_DROITE
</descr>
</equa_>
<equa_ valeur="2">
<descr>POMPE_A_AIR
</descr>
</equa_>
<equa_ valeur="3">
<descr>DIRECTION_DROITE
</descr>
<descr>POMPE_A_AIR
</descr>
</equa_>
<equa_ valeur="4">
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="5">
<descr>DIRECTION_DROITE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="6">
<descr>POMPE_A_AIR
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="7">
<descr>DIRECTION_DROITE
</descr>
<descr>POMPE_A_AIR
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
</partcode_>
<comment>Colonne 28 = CONF BSI2 N68_MUX et M59
</comment>
<partcode_ colonne=28>
<appl>
<pour>
<descr>N68_MUX
</descr>
</pour>
<pour>
<descr>M59
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>DIRECTION_DROITE
</descr>
</equa_>
<equa_ valeur="2">
<descr>POMPE_A_AIR
</descr>
</equa_>
<equa_ valeur="3">
<descr>DIRECTION_DROITE
</descr>
<descr>POMPE_A_AIR
</descr>
</equa_>
<equa_ valeur="4">
<descr>NIVEAU_EAU
</descr>
</equa_>
<equa_ valeur="5">
<descr>DIRECTION_DROITE
</descr>
<descr>NIVEAU_EAU
</descr>
</equa_>
<equa_ valeur="6">
<descr>POMPE_A_AIR
</descr>
<descr>NIVEAU_EAU
</descr>
</equa_>
<equa_ valeur="7">
<descr>DIRECTION_DROITE
</descr>
<descr>POMPE_A_AIR
</descr>
<descr>NIVEAU_EAU
</descr>
</equa_>
</partcode_>
<comment>Colonne 28 = CONF BSI2 Z8
</comment>
<partcode_ colonne=28>
<appl>
<pour>
<descr>Z8
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>DIRECTION_DROITE
</descr>
</equa_>
<equa_ valeur="2">
<descr>ECLAIRAGE_AUTOMATIQUE
</descr>
</equa_>
<equa_ valeur="3">
<descr>DIRECTION_DROITE
</descr>
<descr>ECLAIRAGE_AUTOMATIQUE
</descr>
</equa_>
<equa_ valeur="4">
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="5">
<descr>DIRECTION_DROITE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="6">
<descr>ECLAIRAGE_AUTOMATIQUE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="7">
<descr>DIRECTION_DROITE
</descr>
<descr>ECLAIRAGE_AUTOMATIQUE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
</partcode_>
<comment>Colonne 28 = CONF BSI2 pour V
</comment>
<partcode_ colonne=28>
<appl>
<pour>
<descr>V
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>DIRECTION_DROITE
</descr>
</equa_>
<equa_ valeur="2">
<descr>ECLAIRAGE_AUTOMATIQUE
</descr>
</equa_>
<equa_ valeur="3">
<descr>DIRECTION_DROITE
</descr>
<descr>ECLAIRAGE_AUTOMATIQUE
</descr>
</equa_>
<equa_ valeur="4">
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="5">
<descr>DIRECTION_DROITE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="6">
<descr>ECLAIRAGE_AUTOMATIQUE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="7">
<descr>DIRECTION_DROITE
</descr>
<descr>ECLAIRAGE_AUTOMATIQUE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
</partcode_>
<comment>Colonne 28 = CONF BSI1 N68 M49
</comment>
<partcode_ colonne=28>
<appl>
<pour>
<descr>N68
</descr>
</pour>
<pour>
<descr>M49
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ALARME
</descr>
</equa_>
<equa_ valeur="2">
<descr>ALARME_SUISSE
</descr>
</equa_>
<equa_ valeur="3">
<descr>ALARME
</descr>
<descr>ALARME_SUISSE
</descr>
</equa_>
<equa_ valeur="4">
<descr>SIN_EOBD
</descr>
</equa_>
<equa_ valeur="5">
<descr>ALARME
</descr>
</equa_>
<equa_ valeur="6">
<descr>ALARME_SUISSE
</descr>
</equa_>
<equa_ valeur="7">
<descr>ALARME
</descr>
<descr>ALARME_SUISSE
</descr>
</equa_>
</partcode_>
<comment>Colonne 28 = COMBINE3 pour N7
</comment>
<partcode_ colonne=28>
<appl>
<pour>
<descr>N7
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>20000_Km
</descr>
</equa_>
<equa_ valeur="2">
<descr>6_mois
</descr>
</equa_>
<equa_ valeur="3">
<descr>6_mois
</descr>
<descr>20000_Km
</descr>
</equa_>
<equa_ valeur="4">
<descr>12_mois
</descr>
</equa_>
<equa_ valeur="5">
<descr>12_mois
</descr>
<descr>20000_Km
</descr>
</equa_>
<equa_ valeur="6">
<descr>12_mois
</descr>
<descr>6_mois
</descr>
</equa_>
<equa_ valeur="7">
<descr>12_mois
</descr>
<descr>6_mois
</descr>
<descr>20000_Km
</descr>
</equa_>
</partcode_>
<comment>Colonne 28 = CONF BSI2 pour X4
</comment>
<partcode_ colonne=28>
<appl>
<pour>
<descr>X4
</descr>
</pour>
<pour>
<descr>X41
</descr>
</pour>
<pour>
<descr>X42
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>DIRECTION_DROITE
</descr>
</equa_>
<equa_ valeur="2">
<descr>BVA
</descr>
</equa_>
<equa_ valeur="3">
<descr>BVA
</descr>
<descr>DIRECTION_DROITE
</descr>
</equa_>
<equa_ valeur="4">
<descr>CDS
</descr>
</equa_>
<equa_ valeur="5">
<descr>CDS
</descr>
<descr>DIRECTION_DROITE
</descr>
</equa_>
<equa_ valeur="6">
<descr>CDS
</descr>
<descr>BVA
</descr>
</equa_>
<equa_ valeur="7">
<descr>BVA
</descr>
<descr>CDS
</descr>
<descr>DIRECTION_DROITE
</descr>
</equa_>
</partcode_>
<comment>Colonne 29 = Conf CPH S2/S8
</comment>
<partcode_ colonne=29>
<appl>
<pour>
<descr>S2
</descr>
</pour>
<pour>
<descr>S8
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>LED_1Hz
</descr>
</equa_>
<equa_ valeur="2">
<descr>CLIGNOTANTS
</descr>
</equa_>
<equa_ valeur="3">
<descr>LED_1Hz
</descr>
<descr>CLIGNOTANTS
</descr>
</equa_>
<equa_ valeur="4">
<descr>PIOUP
</descr>
</equa_>
<equa_ valeur="5">
<descr>LED_1Hz
</descr>
<descr>PIOUP
</descr>
</equa_>
<equa_ valeur="6">
<descr>CLIGNOTANTS
</descr>
<descr>PIOUP
</descr>
</equa_>
<equa_ valeur="7">
<descr>LED_1Hz
</descr>
<descr>CLIGNOTANTS
</descr>
<descr>PIOUP
</descr>
</equa_>
</partcode_>
<comment>Colonne 29 = CONF BSI3 T5/D9-2001
</comment>
<partcode_ colonne=29>
<appl>
<pour>
<descr>T5
</descr>
</pour>
<pour>
<descr>D9
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ANTIBROUILLARD_AV
</descr>
</equa_>
<equa_ valeur="2">
<descr>COMMANDE_RADIO_VOLANT
</descr>
</equa_>
<equa_ valeur="3">
<descr>ANTIBROUILLARD_AV
</descr>
<descr>COMMANDE_RADIO_VOLANT
</descr>
</equa_>
<equa_ valeur="4">
<descr>REGULATION_VITESSE
</descr>
</equa_>
<equa_ valeur="5">
<descr>REGULATION_VITESSE
</descr>
<descr>ANTIBROUILLARD_AV
</descr>
</equa_>
<equa_ valeur="6">
<descr>REGULATION_VITESSE
</descr>
<descr>COMMANDE_RADIO_VOLANT
</descr>
</equa_>
<equa_ valeur="7">
<descr>REGULATION_VITESSE
</descr>
<descr>ANTIBROUILLARD_AV
</descr>
<descr>COMMANDE_RADIO_VOLANT
</descr>
</equa_>
</partcode_>
<comment>Colonne 29 = CONF BSI3 T1 MUX, T3
</comment>
<partcode_ colonne=29>
<appl>
<pour>
<descr>T1_MUX
</descr>
</pour>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>T3
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ANTIBROUILLARD_AV
</descr>
</equa_>
<equa_ valeur="2">
<descr>T_Ext
</descr>
</equa_>
<equa_ valeur="3">
<descr>ANTIBROUILLARD_AV
</descr>
<descr>T_Ext
</descr>
</equa_>
<equa_ valeur="4">
<descr>REGULATION_VITESSE
</descr>
</equa_>
<equa_ valeur="5">
<descr>REGULATION_VITESSE
</descr>
<descr>ANTIBROUILLARD_AV
</descr>
</equa_>
<equa_ valeur="6">
<descr>REGULATION_VITESSE
</descr>
<descr>T_Ext
</descr>
</equa_>
<equa_ valeur="7">
<descr>REGULATION_VITESSE
</descr>
<descr>ANTIBROUILLARD_AV
</descr>
<descr>T_Ext
</descr>
</equa_>
</partcode_>
<comment>Colonne 29 = CONF BSI3 N68_MUX
</comment>
<partcode_ colonne=29>
<appl>
<pour>
<descr>N68_MUX
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ANTIBROUILLARD_AV
</descr>
</equa_>
<equa_ valeur="2">
<descr>COMBINE_LVV
</descr>
</equa_>
<equa_ valeur="3">
<descr>ANTIBROUILLARD_AV
</descr>
<descr>COMBINE_LVV
</descr>
</equa_>
<equa_ valeur="4">
<descr>A-COMPLETER
</descr>
</equa_>
<equa_ valeur="5">
<descr>ANTIBROUILLARD_AV
</descr>
</equa_>
<equa_ valeur="6">
<descr>COMBINE_LVV
</descr>
</equa_>
<equa_ valeur="7">
<descr>ANTIBROUILLARD_AV
</descr>
<descr>COMBINE_LVV
</descr>
</equa_>
</partcode_>
<comment>Colonne 29 = CONF BSI3 M59
</comment>
<partcode_ colonne=29>
<appl>
<pour>
<descr>M59
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ANTIBROUILLARD_AV
</descr>
</equa_>
<equa_ valeur="2">
<descr>EV_AR_BIMOTEUR
</descr>
</equa_>
<equa_ valeur="3">
<descr>ANTIBROUILLARD_AV
</descr>
<descr>EV_AR_BIMOTEUR
</descr>
</equa_>
<equa_ valeur="4">
<descr>MODULO_TOP
</descr>
</equa_>
<equa_ valeur="5">
<descr>ANTIBROUILLARD_AV
</descr>
<descr>MODULO_TOP
</descr>
</equa_>
<equa_ valeur="6">
<descr>EV_AR_BIMOTEUR
</descr>
<descr>MODULO_TOP
</descr>
</equa_>
<equa_ valeur="7">
<descr>ANTIBROUILLARD_AV
</descr>
<descr>EV_AR_BIMOTEUR
</descr>
<descr>MODULO_TOP
</descr>
</equa_>
</partcode_>
<comment>Colonne 29 = CONF BSI3 pour V
</comment>
<partcode_ colonne=29>
<appl>
<pour>
<descr>V
</descr>
</pour>
</appl>
<equa_ valeur="4">
<descr>PRETENSIONNEUR
</descr>
</equa_>
<equa_ valeur="5">
<descr>PRETENSIONNEUR
</descr>
</equa_>
<equa_ valeur="6">
<descr>PRETENSIONNEUR
</descr>
</equa_>
<equa_ valeur="7">
<descr>PRETENSIONNEUR
</descr>
</equa_>
</partcode_>
<comment>Colonne 29 = CONF BSI3 Z8
</comment>
<partcode_ colonne=29>
<appl>
<pour>
<descr>Z8
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>BATTERIE_DUAL
</descr>
</equa_>
<equa_ valeur="2">
<descr>ESP
</descr>
</equa_>
<equa_ valeur="3">
<descr>BATTERIE_DUAL
</descr>
<descr>ESP
</descr>
</equa_>
<equa_ valeur="4">
<descr>BVA
</descr>
</equa_>
<equa_ valeur="5">
<descr>BATTERIE_DUAL
</descr>
<descr>BVA
</descr>
</equa_>
<equa_ valeur="6">
<descr>ESP
</descr>
<descr>BVA
</descr>
</equa_>
<equa_ valeur="7">
<descr>BATTERIE_DUAL
</descr>
<descr>ESP
</descr>
<descr>BVA
</descr>
</equa_>
</partcode_>
<comment>Colonne 29 = CONF BSI2 N68 M49
</comment>
<partcode_ colonne=29>
<appl>
<pour>
<descr>N68
</descr>
</pour>
<pour>
<descr>M49
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="2">
<descr>A-COMPLETER
</descr>
</equa_>
<equa_ valeur="3">
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="4">
<descr>ALERTE_SURVITESSE
</descr>
</equa_>
<equa_ valeur="5">
<descr>ALERTE_SURVITESSE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="6">
<descr>ALERTE_SURVITESSE
</descr>
</equa_>
<equa_ valeur="7">
<descr>ALERTE_SURVITESSE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
</partcode_>
<comment>Colonne 29 = CONF BSI2 N7
</comment>
<partcode_ colonne=29>
<appl>
<pour>
<descr>N7
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="2">
<descr>CAPTEUR_PLUIE
</descr>
</equa_>
<equa_ valeur="3">
<descr>LAVE_PROJECTEUR
</descr>
<descr>CAPTEUR_PLUIE
</descr>
</equa_>
<equa_ valeur="4">
<descr>ALERTE_SURVITESSE
</descr>
</equa_>
<equa_ valeur="5">
<descr>ALERTE_SURVITESSE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
</equa_>
<equa_ valeur="6">
<descr>ALERTE_SURVITESSE
</descr>
<descr>CAPTEUR_PLUIE
</descr>
</equa_>
<equa_ valeur="7">
<descr>ALERTE_SURVITESSE
</descr>
<descr>LAVE_PROJECTEUR
</descr>
<descr>CAPTEUR_PLUIE
</descr>
</equa_>
</partcode_>
<comment>colonne 29 = CONF BSI3 pour X4
</comment>
<partcode_ colonne=29>
<appl>
<pour>
<descr>X4
</descr>
</pour>
<pour>
<descr>X41
</descr>
</pour>
<pour>
<descr>X42
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>DETECTION_SOUS_GONFLAGE
</descr>
</equa_>
<equa_ valeur="2">
<descr>CONDA_EN_ROULANT
</descr>
</equa_>
<equa_ valeur="3">
<descr>DETECTION_SOUS_GONFLAGE
</descr>
<descr>CONDA_EN_ROULANT
</descr>
</equa_>
<equa_ valeur="4">
<descr>MODE_PANIQUE
</descr>
</equa_>
<equa_ valeur="5">
<descr>MODE_PANIQUE
</descr>
<descr>DETECTION_SOUS_GONFLAGE
</descr>
</equa_>
<equa_ valeur="6">
<descr>MODE_PANIQUE
</descr>
<descr>CONDA_EN_ROULANT
</descr>
</equa_>
<equa_ valeur="7">
<descr>MODE_PANIQUE
</descr>
<descr>CONDA_EN_ROULANT
</descr>
<descr>DETECTION_SOUS_GONFLAGE
</descr>
</equa_>
</partcode_>
<comment>Colonne 29 = CONF BSI3 A8
</comment>
<partcode_ colonne=29>
<appl>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>A08
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ANTIBROUILLARD_AV
</descr>
</equa_>
<equa_ valeur="3">
<descr>ANTIBROUILLARD_AV
</descr>
</equa_>
<equa_ valeur="4">
<descr>REGULATION_VITESSE
</descr>
</equa_>
<equa_ valeur="5">
<descr>REGULATION_VITESSE
</descr>
<descr>ANTIBROUILLARD_AV
</descr>
</equa_>
<equa_ valeur="6">
<descr>REGULATION_VITESSE
</descr>
</equa_>
<equa_ valeur="7">
<descr>REGULATION_VITESSE
</descr>
<descr>ANTIBROUILLARD_AV
</descr>
</equa_>
</partcode_>
<comment>Colonne 30 = Conf CPH S2/S8
</comment>
<partcode_ colonne=30>
<appl>
<pour>
<descr>S2
</descr>
</pour>
<pour>
<descr>S8
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>LED_ALARME
</descr>
</equa_>
</partcode_>
<comment>Colonne 30 = CONF BSI4 T5/D9-2001
</comment>
<partcode_ colonne=30>
<appl>
<pour>
<descr>T5
</descr>
</pour>
<pour>
<descr>D9
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>SURVITESSE
</descr>
</equa_>
<equa_ valeur="2">
<descr>FEU_DIURNE
</descr>
</equa_>
<equa_ valeur="3">
<descr>SURVITESSE
</descr>
<descr>FEU_DIURNE
</descr>
</equa_>
<equa_ valeur="4">
<descr>PAS_EV_AR
</descr>
</equa_>
<equa_ valeur="5">
<descr>SURVITESSE
</descr>
<descr>PAS_EV_AR
</descr>
</equa_>
<equa_ valeur="6">
<descr>FEU_DIURNE
</descr>
<descr>PAS_EV_AR
</descr>
</equa_>
<equa_ valeur="7">
<descr>SURVITESSE
</descr>
<descr>FEU_DIURNE
</descr>
<descr>PAS_EV_AR
</descr>
</equa_>
</partcode_>
<comment>Colonne 30 = CONF BSI4 T1 MUX, A8 et T3
</comment>
<partcode_ colonne=30>
<appl>
<pour>
<descr>T1_MUX
</descr>
</pour>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>A08
</descr>
</pour>
<pour>
<descr>T3
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>SURVITESSE
</descr>
</equa_>
<equa_ valeur="2">
<descr>FEU_DIURNE
</descr>
</equa_>
<equa_ valeur="3">
<descr>SURVITESSE
</descr>
<descr>FEU_DIURNE
</descr>
</equa_>
<equa_ valeur="4">
<descr>MAINTENANCE_SEVERE
</descr>
</equa_>
<equa_ valeur="5">
<descr>SURVITESSE
</descr>
<descr>MAINTENANCE_SEVERE
</descr>
</equa_>
<equa_ valeur="6">
<descr>FEU_DIURNE
</descr>
<descr>MAINTENANCE_SEVERE
</descr>
</equa_>
<equa_ valeur="7">
<descr>SURVITESSE
</descr>
<descr>FEU_DIURNE
</descr>
<descr>MAINTENANCE_SEVERE
</descr>
</equa_>
</partcode_>
<comment>Colonne 30 = CONF BSI4 N68_MUX
</comment>
<partcode_ colonne=30>
<appl>
<pour>
<descr>N68_MUX
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>RUSSIE
</descr>
</equa_>
<equa_ valeur="2">
<descr>FEU_DIURNE
</descr>
</equa_>
<equa_ valeur="3">
<descr>RUSSIE
</descr>
<descr>FEU_DIURNE
</descr>
</equa_>
<equa_ valeur="4">
<descr>MAINTENANCE_SEVERE
</descr>
</equa_>
<equa_ valeur="5">
<descr>RUSSIE
</descr>
<descr>MAINTENANCE_SEVERE
</descr>
</equa_>
<equa_ valeur="6">
<descr>FEU_DIURNE
</descr>
<descr>MAINTENANCE_SEVERE
</descr>
</equa_>
<equa_ valeur="7">
<descr>RUSSIE
</descr>
<descr>FEU_DIURNE
</descr>
<descr>MAINTENANCE_SEVERE
</descr>
</equa_>
</partcode_>
<comment>Colonne 30 = CONF BSI4 M59
</comment>
<partcode_ colonne=30>
<appl>
<pour>
<descr>M59
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>A-COMPLETER
</descr>
</equa_>
<equa_ valeur="2">
<descr>FEU_DIURNE
</descr>
</equa_>
<equa_ valeur="3">
<descr>FEU_DIURNE
</descr>
</equa_>
<equa_ valeur="4">
<descr>MAINTENANCE_SEVERE
</descr>
</equa_>
<equa_ valeur="5">
<descr>MAINTENANCE_SEVERE
</descr>
</equa_>
<equa_ valeur="6">
<descr>FEU_DIURNE
</descr>
<descr>MAINTENANCE_SEVERE
</descr>
</equa_>
<equa_ valeur="7">
<descr>FEU_DIURNE
</descr>
<descr>MAINTENANCE_SEVERE
</descr>
</equa_>
</partcode_>
<comment>Colonne 30 = CONF BSI4 Z8
</comment>
<partcode_ colonne=30>
<appl>
<pour>
<descr>Z8
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>SURVITESSE
</descr>
</equa_>
<equa_ valeur="2">
<descr>REHOSTAT_AUTOMATIQUE
</descr>
</equa_>
<equa_ valeur="3">
<descr>SURVITESSE
</descr>
<descr>REHOSTAT_AUTOMATIQUE
</descr>
</equa_>
<equa_ valeur="4">
<descr>DETECTION_SOUS_GONFLAGE
</descr>
</equa_>
<equa_ valeur="5">
<descr>SURVITESSE
</descr>
<descr>DETECTION_SOUS_GONFLAGE
</descr>
</equa_>
<equa_ valeur="6">
<descr>REHOSTAT_AUTOMATIQUE
</descr>
<descr>DETECTION_SOUS_GONFLAGE
</descr>
</equa_>
<equa_ valeur="7">
<descr>SURVITESSE
</descr>
<descr>REHOSTAT_AUTOMATIQUE
</descr>
<descr>DETECTION_SOUS_GONFLAGE
</descr>
</equa_>
</partcode_>
<comment>Colonne 30 = CONF BSI3 N68 M49
</comment>
<partcode_ colonne=30>
<appl>
<pour>
<descr>N68
</descr>
</pour>
<pour>
<descr>M49
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>SUPCO
</descr>
</equa_>
<equa_ valeur="2">
<descr>RECEPTEUR_HF
</descr>
</equa_>
<equa_ valeur="3">
<descr>SUPCO
</descr>
<descr>RECEPTEUR_HF
</descr>
</equa_>
<equa_ valeur="4">
<descr>DIRECTION_DROITE
</descr>
</equa_>
<equa_ valeur="5">
<descr>DIRECTION_DROITE
</descr>
<descr>SUPCO
</descr>
</equa_>
<equa_ valeur="6">
<descr>DIRECTION_DROITE
</descr>
<descr>RECEPTEUR_HF
</descr>
</equa_>
<equa_ valeur="7">
<descr>DIRECTION_DROITE
</descr>
<descr>SUPCO
</descr>
<descr>RECEPTEUR_HF
</descr>
</equa_>
</partcode_>
<comment>Colonne 30 = CONF BSI4 pour V
</comment>
<partcode_ colonne=30>
<appl>
<pour>
<descr>V
</descr>
</pour>
</appl>
<equa_ valeur="2">
<descr>REGULATION_VITESSE
</descr>
</equa_>
<equa_ valeur="3">
<descr>REGULATION_VITESSE
</descr>
</equa_>
<equa_ valeur="4">
<descr>DETECTION_SOUS_GONFLAGE
</descr>
</equa_>
<equa_ valeur="5">
<descr>DETECTION_SOUS_GONFLAGE
</descr>
</equa_>
<equa_ valeur="6">
<descr>DETECTION_SOUS_GONFLAGE
</descr>
<descr>REGULATION_VITESSE
</descr>
</equa_>
<equa_ valeur="7">
<descr>DETECTION_SOUS_GONFLAGE
</descr>
<descr>REGULATION_VITESSE
</descr>
</equa_>
</partcode_>
<comment>Colonne 30 = CONF BSI3 N7
</comment>
<partcode_ colonne=30>
<appl>
<pour>
<descr>N7
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>NCAP
</descr>
</equa_>
<equa_ valeur="2">
<descr>RECEPTEUR_HF
</descr>
</equa_>
<equa_ valeur="3">
<descr>NCAP
</descr>
<descr>RECEPTEUR_HF
</descr>
</equa_>
<equa_ valeur="4">
<descr>DIRECTION_DROITE
</descr>
</equa_>
<equa_ valeur="5">
<descr>DIRECTION_DROITE
</descr>
<descr>NCAP
</descr>
</equa_>
<equa_ valeur="6">
<descr>DIRECTION_DROITE
</descr>
<descr>RECEPTEUR_HF
</descr>
</equa_>
<equa_ valeur="7">
<descr>DIRECTION_DROITE
</descr>
<descr>NCAP
</descr>
<descr>RECEPTEUR_HF
</descr>
</equa_>
</partcode_>
<comment>Colonne 31 = Conf CPH S2/S8
</comment>
<partcode_ colonne=31>
<appl>
<pour>
<descr>S8
</descr>
</pour>
<pour>
<descr>S2
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ALERTE_SURVITESSE
</descr>
</equa_>
<equa_ valeur="2">
<descr>BRUITEUR_PEDALIER
</descr>
</equa_>
<equa_ valeur="3">
<descr>ALERTE_SURVITESSE
</descr>
<descr>BRUITEUR_PEDALIER
</descr>
</equa_>
<equa_ valeur="4">
<descr>PLIP_HF
</descr>
</equa_>
<equa_ valeur="5">
<descr>ALERTE_SURVITESSE
</descr>
<descr>PLIP_HF
</descr>
</equa_>
<equa_ valeur="6">
<descr>BRUITEUR_PEDALIER
</descr>
<descr>PLIP_HF
</descr>
</equa_>
<equa_ valeur="7">
<descr>ALERTE_SURVITESSE
</descr>
<descr>BRUITEUR_PEDALIER
</descr>
<descr>PLIP_HF
</descr>
</equa_>
</partcode_>
<comment>Colonne 31 = CONF BSI5 T5/D9-2001
</comment>
<partcode_ colonne=31>
<appl>
<pour>
<descr>T5
</descr>
</pour>
<pour>
<descr>D9
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>LV_ANTIPINC_AR
</descr>
</equa_>
<equa_ valeur="2">
<descr>LV_AV
</descr>
</equa_>
<equa_ valeur="3">
<descr>LV_ANTIPINC_AR
</descr>
<descr>LV_AV
</descr>
</equa_>
<equa_ valeur="4">
<descr>LV_AV_MUX
</descr>
</equa_>
<equa_ valeur="5">
<descr>LV_AV_MUX
</descr>
<descr>LV_ANTIPINC_AR
</descr>
</equa_>
<equa_ valeur="6">
<descr>LV_AV_MUX
</descr>
<descr>LV_AV
</descr>
</equa_>
<equa_ valeur="7">
<descr>LV_ANTIPINC_AR
</descr>
<descr>LV_AV
</descr>
<descr>LV_AV_MUX
</descr>
</equa_>
</partcode_>
<comment>Colonne 31 = CONF BSI5 T1 MUX, T3
</comment>
<partcode_ colonne=31>
<appl>
<pour>
<descr>T1_MUX
</descr>
</pour>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>T3
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>PRESENCE_ESSUIE_VITRE_AR
</descr>
</equa_>
<equa_ valeur="2">
<descr>LV_AV
</descr>
</equa_>
<equa_ valeur="3">
<descr>LV_AV
</descr>
<descr>PRESENCE_ESSUIE_VITRE_AR
</descr>
</equa_>
<equa_ valeur="4">
<descr>CAPTEUR_LUMINOSITE
</descr>
</equa_>
<equa_ valeur="5">
<descr>CAPTEUR_LUMINOSITE
</descr>
<descr>PRESENCE_ESSUIE_VITRE_AR
</descr>
</equa_>
<equa_ valeur="6">
<descr>CAPTEUR_LUMINOSITE
</descr>
<descr>LV_AV
</descr>
</equa_>
<equa_ valeur="7">
<descr>CAPTEUR_LUMINOSITE
</descr>
<descr>LV_AV
</descr>
<descr>PRESENCE_ESSUIE_VITRE_AR
</descr>
</equa_>
</partcode_>
<comment>Colonne 31 = CONF BSI5 N68_MUX
</comment>
<partcode_ colonne=31>
<appl>
<pour>
<descr>N68_MUX
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>PRESENCE_ESSUIE_VITRE_AR
</descr>
</equa_>
<equa_ valeur="2">
<descr>FENETRE_FEBRERO
</descr>
</equa_>
<equa_ valeur="3">
<descr>PRESENCE_ESSUIE_VITRE_AR
</descr>
<descr>FENETRE_FEBRERO
</descr>
</equa_>
<equa_ valeur="4">
<descr>ESSUIE_VITRE_AR_EN_MA
</descr>
</equa_>
<equa_ valeur="5">
<descr>ESSUIE_VITRE_AR_EN_MA
</descr>
<descr>PRESENCE_ESSUIE_VITRE_AR
</descr>
</equa_>
<equa_ valeur="6">
<descr>ESSUIE_VITRE_AR_EN_MA
</descr>
<descr>FENETRE_FEBRERO
</descr>
</equa_>
<equa_ valeur="7">
<descr>ESSUIE_VITRE_AR_EN_MA
</descr>
<descr>PRESENCE_ESSUIE_VITRE_AR
</descr>
<descr>FENETRE_FEBRERO
</descr>
</equa_>
</partcode_>
<comment>Colonne 31 = CONF BSI5 M59
</comment>
<partcode_ colonne=31>
<appl>
<pour>
<descr>M59
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>PRESENCE_ESSUIE_VITRE_AR
</descr>
</equa_>
<equa_ valeur="2">
<descr>LV_AV
</descr>
</equa_>
<equa_ valeur="3">
<descr>PRESENCE_ESSUIE_VITRE_AR
</descr>
<descr>LV_AV
</descr>
</equa_>
<equa_ valeur="4">
<descr>ESSUIE_VITRE_AR_EN_MA
</descr>
</equa_>
<equa_ valeur="5">
<descr>PRESENCE_ESSUIE_VITRE_AR
</descr>
<descr>ESSUIE_VITRE_AR_EN_MA
</descr>
</equa_>
<equa_ valeur="6">
<descr>ESSUIE_VITRE_AR_EN_MA
</descr>
<descr>LV_AV
</descr>
</equa_>
<equa_ valeur="7">
<descr>PRESENCE_ESSUIE_VITRE_AR
</descr>
<descr>ESSUIE_VITRE_AR_EN_MA
</descr>
<descr>LV_AV
</descr>
</equa_>
</partcode_>
<comment>Colonne 31 = CONF BSI5 pour V
</comment>
<partcode_ colonne=31>
<appl>
<pour>
<descr>V
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>DW12
</descr>
</equa_>
<equa_ valeur="3">
<descr>DW12
</descr>
</equa_>
<equa_ valeur="5">
<descr>DW12
</descr>
</equa_>
<equa_ valeur="7">
<descr>DW12
</descr>
</equa_>
</partcode_>
<comment>Colonne 31 = CONF BSI5 Z8
</comment>
<partcode_ colonne=31>
<appl>
<pour>
<descr>Z8
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>LOI_USURE_HUILE
</descr>
</equa_>
<equa_ valeur="2">
<descr>CONFIG_WARNING_AUTO
</descr>
</equa_>
<equa_ valeur="3">
<descr>LOI_USURE_HUILE
</descr>
<descr>CONFIG_WARNING_AUTO
</descr>
</equa_>
<equa_ valeur="4">
<descr>PRESENCE_RESISTANCE_CHAUFFAGE
</descr>
</equa_>
<equa_ valeur="5">
<descr>LOI_USURE_HUILE
</descr>
<descr>PRESENCE_RESISTANCE_CHAUFFAGE
</descr>
</equa_>
<equa_ valeur="6">
<descr>CONFIG_WARNING_AUTO
</descr>
<descr>PRESENCE_RESISTANCE_CHAUFFAGE
</descr>
</equa_>
<equa_ valeur="7">
<descr>LOI_USURE_HUILE
</descr>
<descr>CONFIG_WARNING_AUTO
</descr>
<descr>PRESENCE_RESISTANCE_CHAUFFAGE
</descr>
</equa_>
</partcode_>
<comment>Colonne 31 = CONF BSI4 N68 M49
</comment>
<partcode_ colonne=31>
<appl>
<pour>
<descr>N68
</descr>
</pour>
<pour>
<descr>M49
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ECM_FRIC
</descr>
</equa_>
<equa_ valeur="2">
<descr>NAV
</descr>
</equa_>
<equa_ valeur="3">
<descr>ECM_FRIC
</descr>
<descr>NAV
</descr>
</equa_>
<equa_ valeur="4">
<descr>JAPON
</descr>
</equa_>
<equa_ valeur="5">
<descr>JAPON
</descr>
<descr>ECM_FRIC
</descr>
</equa_>
<equa_ valeur="6">
<descr>JAPON
</descr>
<descr>NAV
</descr>
</equa_>
<equa_ valeur="7">
<descr>JAPON
</descr>
<descr>NAV
</descr>
<descr>ECM_FRIC
</descr>
</equa_>
</partcode_>
<comment>Colonne 31 = CONF BSI4 N7
</comment>
<partcode_ colonne=31>
<appl>
<pour>
<descr>N7
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>AUTO_ECOLE
</descr>
</equa_>
<equa_ valeur="2">
<descr>LVE
</descr>
</equa_>
<equa_ valeur="3">
<descr>AUTO_ECOLE
</descr>
<descr>LVE
</descr>
</equa_>
<equa_ valeur="4">
<descr>CONDA_EN_ROULANT
</descr>
</equa_>
<equa_ valeur="5">
<descr>CONDA_EN_ROULANT
</descr>
<descr>AUTO_ECOLE
</descr>
</equa_>
<equa_ valeur="6">
<descr>CONDA_EN_ROULANT
</descr>
<descr>LVE
</descr>
</equa_>
<equa_ valeur="7">
<descr>CONDA_EN_ROULANT
</descr>
<descr>LVE
</descr>
<descr>AUTO_ECOLE
</descr>
</equa_>
</partcode_>
<comment>Colonne 31 = CONF BSI5 A8
</comment>
<partcode_ colonne=31>
<appl>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>A08
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>PRESENCE_ESSUIE_VITRE_AR
</descr>
</equa_>
<equa_ valeur="2">
<descr>LV_AV
</descr>
</equa_>
<equa_ valeur="3">
<descr>LV_AV
</descr>
<descr>PRESENCE_ESSUIE_VITRE_AR
</descr>
</equa_>
<equa_ valeur="4">
<descr>LV_ANTIPINC_AR
</descr>
</equa_>
<equa_ valeur="5">
<descr>PRESENCE_ESSUIE_VITRE_AR
</descr>
<descr>LV_ANTIPINC_AR
</descr>
</equa_>
<equa_ valeur="6">
<descr>LV_AV
</descr>
<descr>LV_ANTIPINC_AR
</descr>
</equa_>
<equa_ valeur="7">
<descr>LV_AV
</descr>
<descr>PRESENCE_ESSUIE_VITRE_AR
</descr>
<descr>LV_ANTIPINC_AR
</descr>
</equa_>
</partcode_>
<comment>Colonne 32 - N68&M49 - A supprimer des que possible
</comment>
<partcode_ colonne=32>
<appl>
<pour>
<descr>N68
</descr>
</pour>
<pour>
<descr>M49
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>CLIM_EVAPO_60MM
</descr>
</equa_>
</partcode_>
<comment>Colonne 32 = CONF BSI6 T5/D9-2001
</comment>
<partcode_ colonne=32>
<appl>
<pour>
<descr>T5
</descr>
</pour>
<pour>
<descr>D9
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>LIMITEUR_VITESSE
</descr>
</equa_>
<equa_ valeur="2">
<descr>FAP
</descr>
</equa_>
<equa_ valeur="3">
<descr>LIMITEUR_VITESSE
</descr>
<descr>FAP
</descr>
</equa_>
<equa_ valeur="4">
<descr>MILES
</descr>
</equa_>
<equa_ valeur="5">
<descr>LIMITEUR_VITESSE
</descr>
<descr>MILES
</descr>
</equa_>
<equa_ valeur="6">
<descr>FAP
</descr>
<descr>MILES
</descr>
</equa_>
<equa_ valeur="7">
<descr>LIMITEUR_VITESSE
</descr>
<descr>FAP
</descr>
<descr>MILES
</descr>
</equa_>
</partcode_>
<comment>Colonne 32 = CONF BSI6 T1 MUX, T3
</comment>
<partcode_ colonne=32>
<appl>
<pour>
<descr>T1_MUX
</descr>
</pour>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>T3
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>2DISQUES_2TAMB
</descr>
</equa_>
<equa_ valeur="2">
<descr>FAP
</descr>
</equa_>
<equa_ valeur="3">
<descr>2DISQUES_2TAMB
</descr>
<descr>FAP
</descr>
</equa_>
<equa_ valeur="4">
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="5">
<descr>2DISQUES_2TAMB
</descr>
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="6">
<descr>FAP
</descr>
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="7">
<descr>2DISQUES_2TAMB
</descr>
<descr>FAP
</descr>
<descr>NIVEAU_HUILE
</descr>
</equa_>
</partcode_>
<comment>Colonne 32 = CONF BSI6 N68_MUX
</comment>
<partcode_ colonne=32>
<appl>
<pour>
<descr>N68_MUX
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>LV_AV
</descr>
<descr>MERCOSUR
</descr>
</equa_>
<equa_ valeur="2">
<descr>FAP
</descr>
</equa_>
<equa_ valeur="3">
<descr>LV_AV
</descr>
<descr>MERCOSUR
</descr>
<descr>FAP
</descr>
</equa_>
<equa_ valeur="4">
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="5">
<descr>LV_AV
</descr>
<descr>MERCOSUR
</descr>
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="6">
<descr>FAP
</descr>
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="7">
<descr>LV_AV
</descr>
<descr>MERCOSUR
</descr>
<descr>FAP
</descr>
<descr>NIVEAU_HUILE
</descr>
</equa_>
</partcode_>
<comment>Colonne 32 = CONF BSI6 M59
</comment>
<partcode_ colonne=32>
<appl>
<pour>
<descr>M59
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>A-COMPLETER
</descr>
</equa_>
<equa_ valeur="2">
<descr>FAP
</descr>
</equa_>
<equa_ valeur="3">
<descr>FAP
</descr>
</equa_>
<equa_ valeur="4">
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="5">
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="6">
<descr>FAP
</descr>
<descr>NIVEAU_HUILE
</descr>
</equa_>
<equa_ valeur="7">
<descr>FAP
</descr>
<descr>NIVEAU_HUILE
</descr>
</equa_>
</partcode_>
<comment>Colonne 32 = CONF BSI6 Z8
</comment>
<partcode_ colonne=32>
<appl>
<pour>
<descr>Z8
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>FEU_DIURNE
</descr>
</equa_>
<equa_ valeur="2">
<descr>FAP
</descr>
</equa_>
<equa_ valeur="3">
<descr>FEU_DIURNE
</descr>
<descr>FAP
</descr>
</equa_>
<equa_ valeur="4">
<descr>RETRO_RABATTABLE
</descr>
</equa_>
<equa_ valeur="5">
<descr>FEU_DIURNE
</descr>
<descr>RETRO_RABATTABLE
</descr>
</equa_>
<equa_ valeur="6">
<descr>FAP
</descr>
<descr>RETRO_RABATTABLE
</descr>
</equa_>
<equa_ valeur="7">
<descr>FEU_DIURNE
</descr>
<descr>FAP
</descr>
<descr>RETRO_RABATTABLE
</descr>
</equa_>
</partcode_>
<comment>Colonne 32 = CONF BSI6 pour V
</comment>
<partcode_ colonne=32>
<appl>
<pour>
<descr>V
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>FEU_DIURNE
</descr>
</equa_>
<equa_ valeur="2">
<descr>FAP
</descr>
</equa_>
<equa_ valeur="3">
<descr>FEU_DIURNE
</descr>
<descr>FAP
</descr>
</equa_>
<equa_ valeur="4">
<descr>PRESENCE_CAS
</descr>
</equa_>
<equa_ valeur="5">
<descr>FEU_DIURNE
</descr>
<descr>PRESENCE_CAS
</descr>
</equa_>
<equa_ valeur="6">
<descr>FAP
</descr>
<descr>PRESENCE_CAS
</descr>
</equa_>
<equa_ valeur="7">
<descr>FEU_DIURNE
</descr>
<descr>FAP
</descr>
<descr>PRESENCE_CAS
</descr>
</equa_>
</partcode_>
<comment>Colonne 32 = CONF BSI6 A8
</comment>
<partcode_ colonne=32>
<appl>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>A08
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>2DISQUES_2TAMB
</descr>
</equa_>
<equa_ valeur="2">
<descr>FAP
</descr>
</equa_>
<equa_ valeur="3">
<descr>2DISQUES_2TAMB
</descr>
<descr>FAP
</descr>
</equa_>
<equa_ valeur="5">
<descr>2DISQUES_2TAMB
</descr>
</equa_>
<equa_ valeur="6">
<descr>FAP
</descr>
</equa_>
<equa_ valeur="7">
<descr>2DISQUES_2TAMB
</descr>
<descr>FAP
</descr>
</equa_>
</partcode_>
<comment>Colonne 33 = Conf Transpondeur S2/S8
</comment>
<partcode_ colonne=33>
<appl>
<pour>
<descr>S2
</descr>
</pour>
<pour>
<descr>S8
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>TEMOIN
</descr>
</equa_>
<equa_ valeur="2">
<descr>BRUITEUR
</descr>
</equa_>
<equa_ valeur="3">
<descr>TEMOIN
</descr>
<descr>BRUITEUR
</descr>
</equa_>
<equa_ valeur="4">
<descr>LED
</descr>
</equa_>
<equa_ valeur="5">
<descr>TEMOIN
</descr>
<descr>LED
</descr>
</equa_>
<equa_ valeur="6">
<descr>LED
</descr>
<descr>BRUITEUR
</descr>
</equa_>
<equa_ valeur="7">
<descr>TEMOIN
</descr>
<descr>LED
</descr>
<descr>BRUITEUR
</descr>
</equa_>
</partcode_>
<comment>Colonne 33 = CONF BSI7 T5/D9-2001
</comment>
<partcode_ colonne=33>
<appl>
<pour>
<descr>T5
</descr>
</pour>
<pour>
<descr>D9
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>CONDAMNATION
</descr>
</equa_>
<equa_ valeur="2">
<descr>RETRO_MUX
</descr>
</equa_>
<equa_ valeur="3">
<descr>CONDAMNATION
</descr>
<descr>RETRO_MUX
</descr>
</equa_>
<equa_ valeur="4">
<descr>RETRO_RABATTABLE
</descr>
</equa_>
<equa_ valeur="5">
<descr>RETRO_RABATTABLE
</descr>
<descr>CONDAMNATION
</descr>
</equa_>
<equa_ valeur="6">
<descr>RETRO_RABATTABLE
</descr>
<descr>RETRO_MUX
</descr>
</equa_>
<equa_ valeur="7">
<descr>RETRO_RABATTABLE
</descr>
<descr>RETRO_MUX
</descr>
<descr>CONDAMNATION
</descr>
</equa_>
</partcode_>
<comment>Colonne 33 = CONF BSI7 T1 MUX, T3
</comment>
<partcode_ colonne=33>
<appl>
<pour>
<descr>T1_MUX
</descr>
</pour>
<pour>
<descr>T3
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>CONDAMNATION
</descr>
</equa_>
<equa_ valeur="2">
<descr>CAPTEUR_TEMP_ET_NIV
</descr>
</equa_>
<equa_ valeur="3">
<descr>CONDAMNATION
</descr>
<descr>CAPTEUR_TEMP_ET_NIV
</descr>
</equa_>
<equa_ valeur="4">
<descr>HOMOLOGATION
</descr>
</equa_>
<equa_ valeur="5">
<descr>HOMOLOGATION
</descr>
<descr>CONDAMNATION
</descr>
</equa_>
<equa_ valeur="6">
<descr>HOMOLOGATION
</descr>
<descr>CAPTEUR_TEMP_ET_NIV
</descr>
</equa_>
<equa_ valeur="7">
<descr>HOMOLOGATION
</descr>
<descr>CAPTEUR_TEMP_ET_NIV
</descr>
<descr>CONDAMNATION
</descr>
</equa_>
</partcode_>
<comment>Colonne 33 = CONF BSI7 A8
</comment>
<partcode_ colonne=33>
<appl>
<pour>
<descr>A8
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>CONDAMNATION
</descr>
</equa_>
<equa_ valeur="2">
<descr>INHIB_CONDA_LATEN
</descr>
</equa_>
<equa_ valeur="3">
<descr>CONDAMNATION
</descr>
<descr>INHIB_CONDA_LATEN
</descr>
</equa_>
<equa_ valeur="4">
<descr>SANS_EODB
</descr>
</equa_>
<equa_ valeur="5">
<descr>SANS_EODB
</descr>
<descr>CONDAMNATION
</descr>
</equa_>
<equa_ valeur="6">
<descr>SANS_EODB
</descr>
<descr>INHIB_CONDA_LATEN
</descr>
</equa_>
<equa_ valeur="7">
<descr>SANS_EODB
</descr>
<descr>INHIB_CONDA_LATEN
</descr>
<descr>CONDAMNATION
</descr>
</equa_>
</partcode_>
<comment>Colonne 33 = CONF BSI7 N68_MUX et M59
</comment>
<partcode_ colonne=33>
<appl>
<pour>
<descr>N68_MUX
</descr>
</pour>
<pour>
<descr>M59
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>CONDAMNATION
</descr>
</equa_>
<equa_ valeur="2">
<descr>FENETRE_2_07
</descr>
</equa_>
<equa_ valeur="3">
<descr>CONDAMNATION
</descr>
<descr>FENETRE_2_07
</descr>
</equa_>
<equa_ valeur="4">
<descr>VERROU_PASSAGER
</descr>
</equa_>
<equa_ valeur="5">
<descr>VERROU_PASSAGER
</descr>
<descr>CONDAMNATION
</descr>
</equa_>
<equa_ valeur="6">
<descr>VERROU_PASSAGER
</descr>
<descr>FENETRE_2_07
</descr>
</equa_>
<equa_ valeur="7">
<descr>CONDAMNATION
</descr>
<descr>VERROU_PASSAGER
</descr>
<descr>FENETRE_2_07
</descr>
</equa_>
</partcode_>
<comment>Colonne 33 = CONF BSI6 N68 M49
</comment>
<partcode_ colonne=33>
<appl>
<pour>
<descr>M49
</descr>
</pour>
<pour>
<descr>N68
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ESSUIE_VITRE_AR
</descr>
</equa_>
<equa_ valeur="2">
<descr>ALERTE_OUVRANTS
</descr>
</equa_>
<equa_ valeur="3">
<descr>ALERTE_OUVRANTS
</descr>
<descr>ESSUIE_VITRE_AR
</descr>
</equa_>
<equa_ valeur="4">
<descr>ESSUIE_VITRE_AR_BI_MOTEUR
</descr>
</equa_>
<equa_ valeur="5">
<descr>ESSUIE_VITRE_AR_BI_MOTEUR
</descr>
<descr>ESSUIE_VITRE_AR
</descr>
</equa_>
<equa_ valeur="6">
<descr>ALERTE_OUVRANTS
</descr>
<descr>ESSUIE_VITRE_AR_BI_MOTEUR
</descr>
</equa_>
<equa_ valeur="7">
<descr>ESSUIE_VITRE_AR_BI_MOTEUR
</descr>
<descr>ALERTE_OUVRANTS
</descr>
<descr>ESSUIE_VITRE_AR
</descr>
</equa_>
</partcode_>
<comment>Colonne 33 = CONF BSI7 pour V
</comment>
<partcode_ colonne=33>
<appl>
<pour>
<descr>V
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>ESSUIE_VITRE_AR
</descr>
</equa_>
<equa_ valeur="2">
<descr>ANTIBROUILLARD_AV
</descr>
</equa_>
<equa_ valeur="3">
<descr>ANTIBROUILLARD_AV
</descr>
<descr>ESSUIE_VITRE_AR
</descr>
</equa_>
<equa_ valeur="4">
<descr>CAPTEUR_PLUIE
</descr>
</equa_>
<equa_ valeur="5">
<descr>CAPTEUR_PLUIE
</descr>
<descr>ESSUIE_VITRE_AR
</descr>
</equa_>
<equa_ valeur="6">
<descr>ANTIBROUILLARD_AV
</descr>
<descr>CAPTEUR_PLUIE
</descr>
</equa_>
<equa_ valeur="7">
<descr>CAPTEUR_PLUIE
</descr>
<descr>ANTIBROUILLARD_AV
</descr>
<descr>ESSUIE_VITRE_AR
</descr>
</equa_>
</partcode_>
<comment>Colonne 33 = CONF BSI7 A8
</comment>
<partcode_ colonne=33>
<appl>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>A08
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>CONDAMNATION
</descr>
</equa_>
<equa_ valeur="2">
<descr>INHIB_CONDA_LATEN
</descr>
</equa_>
<equa_ valeur="3">
<descr>CONDAMNATION
</descr>
<descr>INHIB_CONDA_LATEN
</descr>
</equa_>
<equa_ valeur="5">
<descr>CONDAMNATION
</descr>
</equa_>
<equa_ valeur="6">
<descr>INHIB_CONDA_LATEN
</descr>
</equa_>
<equa_ valeur="7">
<descr>INHIB_CONDA_LATEN
</descr>
<descr>CONDAMNATION
</descr>
</equa_>
</partcode_>
<comment>Colonne 34 = Conf BSI8 T5/D9-2001
</comment>
<partcode_ colonne=34>
<appl>
<pour>
<descr>T5
</descr>
</pour>
<pour>
<descr>D9
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>MAE
</descr>
</equa_>
<equa_ valeur="2">
<descr>ECLAIRAGE_DE_SEUIL
</descr>
</equa_>
<equa_ valeur="3">
<descr>MAE
</descr>
<descr>ECLAIRAGE_DE_SEUIL
</descr>
</equa_>
<equa_ valeur="4">
<descr>CAPTEUR_PLUIE
</descr>
</equa_>
<equa_ valeur="5">
<descr>CAPTEUR_PLUIE
</descr>
<descr>MAE
</descr>
</equa_>
<equa_ valeur="6">
<descr>CAPTEUR_PLUIE
</descr>
<descr>ECLAIRAGE_DE_SEUIL
</descr>
</equa_>
<equa_ valeur="7">
<descr>CAPTEUR_PLUIE
</descr>
<descr>ECLAIRAGE_DE_SEUIL
</descr>
<descr>MAE
</descr>
</equa_>
</partcode_>
<comment>Colonne 34 = CONF BSI8 T1 MUX, A8 et T3
</comment>
<partcode_ colonne=34>
<appl>
<pour>
<descr>T1_MUX
</descr>
</pour>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>A08
</descr>
</pour>
<pour>
<descr>T3
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>MAE
</descr>
</equa_>
<equa_ valeur="2">
<descr>TEMOIN_OUBLI_CEINT
</descr>
</equa_>
<equa_ valeur="3">
<descr>MAE
</descr>
<descr>TEMOIN_OUBLI_CEINT
</descr>
</equa_>
<equa_ valeur="4">
<descr>CAPTEUR_PLUIE
</descr>
</equa_>
<equa_ valeur="5">
<descr>CAPTEUR_PLUIE
</descr>
<descr>MAE
</descr>
</equa_>
<equa_ valeur="6">
<descr>CAPTEUR_PLUIE
</descr>
<descr>TEMOIN_OUBLI_CEINT
</descr>
</equa_>
<equa_ valeur="7">
<descr>CAPTEUR_PLUIE
</descr>
<descr>TEMOIN_OUBLI_CEINT
</descr>
<descr>MAE
</descr>
</equa_>
</partcode_>
<comment>Colonne 34 = CONF BSI8 N68_MUX
</comment>
<partcode_ colonne=34>
<appl>
<pour>
<descr>N68_MUX
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>MILES
</descr>
</equa_>
<equa_ valeur="2">
<descr>A-COMPLETER
</descr>
</equa_>
<equa_ valeur="3">
<descr>MILES
</descr>
</equa_>
<equa_ valeur="4">
<descr>CAPTEUR_PLUIE
</descr>
</equa_>
<equa_ valeur="5">
<descr>MILES
</descr>
<descr>CAPTEUR_PLUIE
</descr>
</equa_>
<equa_ valeur="6">
<descr>CAPTEUR_PLUIE
</descr>
</equa_>
<equa_ valeur="7">
<descr>MILES
</descr>
<descr>CAPTEUR_PLUIE
</descr>
</equa_>
</partcode_>
<comment>Colonne 34 = CONF BSI8 M59
</comment>
<partcode_ colonne=34>
<appl>
<pour>
<descr>M59
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>MILES
</descr>
</equa_>
<equa_ valeur="2">
<descr>TEMOIN_OUBLI_CEINT
</descr>
</equa_>
<equa_ valeur="3">
<descr>MILES
</descr>
<descr>TEMOIN_OUBLI_CEINT
</descr>
</equa_>
<equa_ valeur="4">
<descr>CAPTEUR_PLUIE
</descr>
</equa_>
<equa_ valeur="5">
<descr>MILES
</descr>
<descr>CAPTEUR_PLUIE
</descr>
</equa_>
<equa_ valeur="6">
<descr>TEMOIN_OUBLI_CEINT
</descr>
<descr>CAPTEUR_PLUIE
</descr>
</equa_>
<equa_ valeur="7">
<descr>MILES
</descr>
<descr>TEMOIN_OUBLI_CEINT
</descr>
<descr>CAPTEUR_PLUIE
</descr>
</equa_>
</partcode_>
<comment>Colonne 34 = OPTION1 Z8
</comment>
<partcode_ colonne=34>
<appl>
<pour>
<descr>Z8
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>KIT_MAIN_LIBRE
</descr>
</equa_>
<equa_ valeur="2">
<descr>PRESENCE_CD
</descr>
<descr>CD
</descr>
</equa_>
<equa_ valeur="3">
<descr>KIT_MAIN_LIBRE
</descr>
<descr>PRESENCE_CD
</descr>
<descr>CD
</descr>
</equa_>
<equa_ valeur="4">
<descr>AFFICHAGE_TEMP
</descr>
</equa_>
<equa_ valeur="5">
<descr>KIT_MAIN_LIBRE
</descr>
<descr>AFFICHAGE_TEMP
</descr>
</equa_>
<equa_ valeur="6">
<descr>PRESENCE_CD
</descr>
<descr>CD
</descr>
<descr>AFFICHAGE_TEMP
</descr>
</equa_>
<equa_ valeur="7">
<descr>KIT_MAIN_LIBRE
</descr>
<descr>PRESENCE_CD
</descr>
<descr>CD
</descr>
<descr>AFFICHAGE_TEMP
</descr>
</equa_>
</partcode_>
<comment>Colonne 34 = OPTION 1 pour V
</comment>
<partcode_ colonne=34>
<appl>
<pour>
<descr>V
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>PULSEUR_ADD
</descr>
</equa_>
<equa_ valeur="3">
<descr>PULSEUR_ADD
</descr>
</equa_>
<equa_ valeur="4">
<descr>LANCIA-FIAT
</descr>
</equa_>
<equa_ valeur="5">
<descr>LANCIA-FIAT
</descr>
<descr>PULSEUR_ADD
</descr>
</equa_>
<equa_ valeur="6">
<descr>LANCIA-FIAT
</descr>
</equa_>
<equa_ valeur="7">
<descr>LANCIA-FIAT
</descr>
<descr>PULSEUR_ADD
</descr>
</equa_>
</partcode_>
<comment>Colonne 34 = OPTIONS EMF N68 M49
</comment>
<partcode_ colonne=34>
<appl>
<pour>
<descr>N68
</descr>
</pour>
<pour>
<descr>M49
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>PRESENCE_RADIO
</descr>
</equa_>
<equa_ valeur="2">
<descr>PRESENCE_CD
</descr>
</equa_>
<equa_ valeur="3">
<descr>PRESENCE_RADIO
</descr>
<descr>PRESENCE_CD
</descr>
</equa_>
<equa_ valeur="4">
<descr>PRESENCE_NAV
</descr>
</equa_>
<equa_ valeur="5">
<descr>PRESENCE_NAV
</descr>
<descr>PRESENCE_RADIO
</descr>
</equa_>
<equa_ valeur="6">
<descr>PRESENCE_NAV
</descr>
<descr>PRESENCE_CD
</descr>
</equa_>
<equa_ valeur="7">
<descr>PRESENCE_NAV
</descr>
<descr>PRESENCE_CD
</descr>
<descr>PRESENCE_RADIO
</descr>
</equa_>
</partcode_>
<comment>Colonne 34 = OPTIONS EMF M49 (special VIGO)
</comment>
<partcode_ colonne=34>
<appl>
<pour>
<descr>M49
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>SIN_EOBD
</descr>
</equa_>
<equa_ valeur="2">
<descr>BRASIL
</descr>
</equa_>
<equa_ valeur="3">
<descr>SIN_EOBD
</descr>
<descr>BRASIL
</descr>
</equa_>
</partcode_>
<comment>Colonne 34 = OPTIONS EMF N7
</comment>
<partcode_ colonne=34>
<appl>
<pour>
<descr>N7
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>T_Ext
</descr>
</equa_>
<equa_ valeur="2">
<descr>ODB
</descr>
</equa_>
<equa_ valeur="3">
<descr>ODB
</descr>
<descr>T_Ext
</descr>
</equa_>
<equa_ valeur="5">
<descr>T_Ext
</descr>
</equa_>
<equa_ valeur="6">
<descr>ODB
</descr>
</equa_>
<equa_ valeur="7">
<descr>ODB
</descr>
<descr>T_Ext
</descr>
</equa_>
</partcode_>
<comment>Colonne 35 - N68&M49 a supprimer des que possiblr
</comment>
<partcode_ colonne=35>
<appl>
<pour>
<descr>N68
</descr>
</pour>
<pour>
<descr>M49
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>CHINA
</descr>
</equa_>
</partcode_>
<comment>Colonne 35 = Conf BSI9 T5/D9-2001
</comment>
<partcode_ colonne=35>
<appl>
<pour>
<descr>T5
</descr>
</pour>
<pour>
<descr>D9
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>CUIR
</descr>
</equa_>
<equa_ valeur="2">
<descr>TEMP_HUILE
</descr>
</equa_>
<equa_ valeur="3">
<descr>CUIR
</descr>
<descr>TEMP_HUILE
</descr>
</equa_>
<equa_ valeur="4">
<descr>NIVEAU_EAU
</descr>
</equa_>
<equa_ valeur="5">
<descr>NIVEAU_EAU
</descr>
<descr>CUIR
</descr>
</equa_>
<equa_ valeur="6">
<descr>NIVEAU_EAU
</descr>
<descr>TEMP_HUILE
</descr>
</equa_>
<equa_ valeur="7">
<descr>NIVEAU_EAU
</descr>
<descr>CUIR
</descr>
<descr>TEMP_HUILE
</descr>
</equa_>
</partcode_>
<comment>Colonne 35 = CONF BSI9 T1 MUX, A8 et T3
</comment>
<partcode_ colonne=35>
<appl>
<pour>
<descr>T1_MUX
</descr>
</pour>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>A08
</descr>
</pour>
<pour>
<descr>T3
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>CUIR
</descr>
</equa_>
<equa_ valeur="2">
<descr>TEMP_HUILE
</descr>
</equa_>
<equa_ valeur="3">
<descr>CUIR
</descr>
<descr>TEMP_HUILE
</descr>
</equa_>
<equa_ valeur="4">
<descr>NIVEAU_EAU
</descr>
</equa_>
<equa_ valeur="5">
<descr>CUIR
</descr>
<descr>NIVEAU_EAU
</descr>
</equa_>
<equa_ valeur="6">
<descr>NIVEAU_EAU
</descr>
<descr>TEMP_HUILE
</descr>
</equa_>
<equa_ valeur="7">
<descr>CUIR
</descr>
<descr>NIVEAU_EAU
</descr>
<descr>TEMP_HUILE
</descr>
</equa_>
</partcode_>
<comment>Colonne 35 = CONF BSI9 N68_MUX
</comment>
<partcode_ colonne=35>
<appl>
<pour>
<descr>N68_MUX
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>CAPTEUR_LUMINOSITE
</descr>
</equa_>
<equa_ valeur="2">
<descr>A-COMPLETER
</descr>
</equa_>
<equa_ valeur="3">
<descr>CAPTEUR_LUMINOSITE
</descr>
</equa_>
<equa_ valeur="4">
<descr>PRESENCE_BRULEUR_ADDITIONNEL
</descr>
</equa_>
<equa_ valeur="5">
<descr>PRESENCE_BRULEUR_ADDITIONNEL
</descr>
<descr>CAPTEUR_LUMINOSITE
</descr>
</equa_>
<equa_ valeur="6">
<descr>PRESENCE_BRULEUR_ADDITIONNEL
</descr>
</equa_>
<equa_ valeur="7">
<descr>PRESENCE_BRULEUR_ADDITIONNEL
</descr>
<descr>CAPTEUR_LUMINOSITE
</descr>
</equa_>
</partcode_>
<comment>Colonne 35 = CONF BSI9 M59
</comment>
<partcode_ colonne=35>
<appl>
<pour>
<descr>M59
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>CAPTEUR_LUMINOSITE
</descr>
</equa_>
<equa_ valeur="2">
<descr>LIMITEUR_VITESSE
</descr>
</equa_>
<equa_ valeur="3">
<descr>LIMITEUR_VITESSE
</descr>
<descr>CAPTEUR_LUMINOSITE
</descr>
</equa_>
<equa_ valeur="4">
<descr>PRESENCE_BRULEUR_ADDITIONNEL
</descr>
</equa_>
<equa_ valeur="5">
<descr>PRESENCE_BRULEUR_ADDITIONNEL
</descr>
<descr>CAPTEUR_LUMINOSITE
</descr>
</equa_>
<equa_ valeur="6">
<descr>PRESENCE_BRULEUR_ADDITIONNEL
</descr>
<descr>LIMITEUR_VITESSE
</descr>
</equa_>
<equa_ valeur="7">
<descr>LIMITEUR_VITESSE
</descr>
<descr>PRESENCE_BRULEUR_ADDITIONNEL
</descr>
<descr>CAPTEUR_LUMINOSITE
</descr>
</equa_>
</partcode_>
<comment>Colonne 35 = OPTION2 Z8
</comment>
<partcode_ colonne=35>
<appl>
<pour>
<descr>Z8
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>PRESENCE_PDP
</descr>
</equa_>
<equa_ valeur="2">
<descr>PRESENCE_AAS
</descr>
</equa_>
<equa_ valeur="3">
<descr>PRESENCE_PDP
</descr>
<descr>PRESENCE_AAS
</descr>
</equa_>
<equa_ valeur="4">
<descr>PRESENCE_CAS
</descr>
</equa_>
<equa_ valeur="5">
<descr>PRESENCE_CAS
</descr>
<descr>PRESENCE_PDP
</descr>
</equa_>
<equa_ valeur="6">
<descr>PRESENCE_CAS
</descr>
<descr>PRESENCE_AAS
</descr>
</equa_>
<equa_ valeur="7">
<descr>PRESENCE_CAS
</descr>
<descr>PRESENCE_AAS
</descr>
<descr>PRESENCE_PDP
</descr>
</equa_>
</partcode_>
<comment>Colonne 35 = OPTION ALARME N7
</comment>
<partcode_ colonne=35>
<appl>
<pour>
<descr>N7
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>CUIR
</descr>
</equa_>
<equa_ valeur="3">
<descr>CUIR
</descr>
</equa_>
<equa_ valeur="5">
<descr>CUIR
</descr>
</equa_>
<equa_ valeur="7">
<descr>CUIR
</descr>
</equa_>
</partcode_>
<comment>Colonne 36 = Conf BSI10 Z8
</comment>
<partcode_ colonne=36>
<appl>
<pour>
<descr>Z8
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>AIRBAG_LATERAL_AR
</descr>
</equa_>
<equa_ valeur="2">
<descr>COFFRE_MOTORISE
</descr>
</equa_>
<equa_ valeur="3">
<descr>AIRBAG_LATERAL_AR
</descr>
<descr>COFFRE_MOTORISE
</descr>
</equa_>
<equa_ valeur="5">
<descr>AIRBAG_LATERAL_AR
</descr>
</equa_>
<equa_ valeur="6">
<descr>COFFRE_MOTORISE
</descr>
</equa_>
<equa_ valeur="7">
<descr>AIRBAG_LATERAL_AR
</descr>
<descr>COFFRE_MOTORISE
</descr>
</equa_>
</partcode_>
<comment>Colonne 36 = Conf BSI10 T5/D9-2001
</comment>
<partcode_ colonne=36>
<appl>
<pour>
<descr>T5
</descr>
</pour>
<pour>
<descr>D9
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>HOMOLOGATION
</descr>
</equa_>
<equa_ valeur="2">
<descr>ANTIBROUILLARD_AR
</descr>
</equa_>
<equa_ valeur="3">
<descr>HOMOLOGATION
</descr>
<descr>ANTIBROUILLARD_AR
</descr>
</equa_>
<equa_ valeur="4">
<descr>EAU_DS_GO
</descr>
</equa_>
<equa_ valeur="5">
<descr>HOMOLOGATION
</descr>
<descr>EAU_DS_GO
</descr>
</equa_>
<equa_ valeur="6">
<descr>ANTIBROUILLARD_AR
</descr>
<descr>EAU_DS_GO
</descr>
</equa_>
<equa_ valeur="7">
<descr>HOMOLOGATION
</descr>
<descr>ANTIBROUILLARD_AR
</descr>
<descr>EAU_DS_GO
</descr>
</equa_>
</partcode_>
<comment>Colonne 36 = CONF BSI10 T1 MUX, T3
</comment>
<partcode_ colonne=36>
<appl>
<pour>
<descr>T1_MUX
</descr>
</pour>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>T3
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>PARE_BRISE_ATHERMIQUE
</descr>
</equa_>
<equa_ valeur="2">
<descr>CONDA_EN_ROULANT
</descr>
</equa_>
<equa_ valeur="3">
<descr>PARE_BRISE_ATHERMIQUE
</descr>
<descr>CONDA_EN_ROULANT
</descr>
</equa_>
<equa_ valeur="4">
<descr>EAU_DS_GO
</descr>
</equa_>
<equa_ valeur="5">
<descr>PARE_BRISE_ATHERMIQUE
</descr>
<descr>EAU_DS_GO
</descr>
</equa_>
<equa_ valeur="6">
<descr>EAU_DS_GO
</descr>
<descr>CONDA_EN_ROULANT
</descr>
</equa_>
<equa_ valeur="7">
<descr>PARE_BRISE_ATHERMIQUE
</descr>
<descr>EAU_DS_GO
</descr>
<descr>CONDA_EN_ROULANT
</descr>
</equa_>
</partcode_>
<comment>Colonne 36 = CONF BSI10 N68_MUX
</comment>
<partcode_ colonne=36>
<appl>
<pour>
<descr>N68_MUX
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>A-COMPLETER
</descr>
</equa_>
<equa_ valeur="2">
<descr>MAINTENANCE_EVOLUEE
</descr>
</equa_>
<equa_ valeur="3">
<descr>MAINTENANCE_EVOLUEE
</descr>
</equa_>
<equa_ valeur="4">
<descr>EAU_DS_GO
</descr>
</equa_>
<equa_ valeur="5">
<descr>EAU_DS_GO
</descr>
</equa_>
<equa_ valeur="6">
<descr>EAU_DS_GO
</descr>
<descr>MAINTENANCE_EVOLUEE
</descr>
</equa_>
<equa_ valeur="7">
<descr>EAU_DS_GO
</descr>
<descr>MAINTENANCE_EVOLUEE
</descr>
</equa_>
</partcode_>
<comment>Colonne 36 = CONF BSI10 et M59
</comment>
<partcode_ colonne=36>
<appl>
<pour>
<descr>M59
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>PARE_BRISE_ATHERMIQUE
</descr>
</equa_>
<equa_ valeur="2">
<descr>MAINTENANCE_EVOLUEE
</descr>
</equa_>
<equa_ valeur="3">
<descr>PARE_BRISE_ATHERMIQUE
</descr>
<descr>MAINTENANCE_EVOLUEE
</descr>
</equa_>
<equa_ valeur="4">
<descr>EAU_DS_GO
</descr>
</equa_>
<equa_ valeur="5">
<descr>PARE_BRISE_ATHERMIQUE
</descr>
<descr>EAU_DS_GO
</descr>
</equa_>
<equa_ valeur="6">
<descr>EAU_DS_GO
</descr>
<descr>MAINTENANCE_EVOLUEE
</descr>
</equa_>
<equa_ valeur="7">
<descr>PARE_BRISE_ATHERMIQUE
</descr>
<descr>EAU_DS_GO
</descr>
<descr>MAINTENANCE_EVOLUEE
</descr>
</equa_>
</partcode_>
<comment>Colonne 36 = OPTION 3 pour V
</comment>
<partcode_ colonne=36>
<appl>
<pour>
<descr>V
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>PARE_BRISE_VERT
</descr>
</equa_>
<equa_ valeur="2">
<descr>PARE_BRISE_BLEU
</descr>
</equa_>
<equa_ valeur="3">
<descr>PARE_BRISE_BLEU
</descr>
<descr>PARE_BRISE_VERT
</descr>
</equa_>
<equa_ valeur="4">
<descr>PARE_BRISE_ATHERMIQUE
</descr>
</equa_>
<equa_ valeur="5">
<descr>PARE_BRISE_ATHERMIQUE
</descr>
<descr>PARE_BRISE_VERT
</descr>
</equa_>
<equa_ valeur="6">
<descr>PARE_BRISE_ATHERMIQUE
</descr>
<descr>PARE_BRISE_BLEU
</descr>
</equa_>
<equa_ valeur="7">
<descr>PARE_BRISE_ATHERMIQUE
</descr>
<descr>PARE_BRISE_BLEU
</descr>
<descr>PARE_BRISE_VERT
</descr>
</equa_>
</partcode_>
<comment>Colonne 36 = OPTION COMBINE3 N68 M49
</comment>
<partcode_ colonne=36>
<appl>
<pour>
<descr>M49
</descr>
</pour>
<pour>
<descr>N68
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>15000_Km
</descr>
</equa_>
<equa_ valeur="2">
<descr>20000_Km
</descr>
</equa_>
<equa_ valeur="3">
<descr>15000_Km
</descr>
<descr>20000_Km
</descr>
</equa_>
<equa_ valeur="4">
<descr>30000_km
</descr>
<descr>30000_Km
</descr>
</equa_>
<equa_ valeur="5">
<descr>15000_Km
</descr>
<descr>30000_km
</descr>
<descr>30000_Km
</descr>
</equa_>
<equa_ valeur="6">
<descr>DIRECTION_DROITE
</descr>
<descr>HDI
</descr>
</equa_>
<equa_ valeur="7">
<descr>15000_Km
</descr>
<descr>20000_Km
</descr>
<descr>30000_km
</descr>
<descr>30000_Km
</descr>
</equa_>
</partcode_>
<comment>Colonne 36 = CONF BSI10 A8
</comment>
<partcode_ colonne=36>
<appl>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>A08
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>PARE_BRISE_ATHERMIQUE
</descr>
</equa_>
<equa_ valeur="2">
<descr>CONDA_EN_ROULANT
</descr>
</equa_>
<equa_ valeur="3">
<descr>PARE_BRISE_ATHERMIQUE
</descr>
<descr>CONDA_EN_ROULANT
</descr>
</equa_>
<equa_ valeur="4">
<descr>EAU_DS_GO
</descr>
</equa_>
<equa_ valeur="5">
<descr>PARE_BRISE_ATHERMIQUE
</descr>
<descr>EAU_DS_GO
</descr>
</equa_>
<equa_ valeur="6">
<descr>CONDA_EN_ROULANT
</descr>
<descr>EAU_DS_GO
</descr>
</equa_>
<equa_ valeur="7">
<descr>PARE_BRISE_ATHERMIQUE
</descr>
<descr>CONDA_EN_ROULANT
</descr>
<descr>EAU_DS_GO
</descr>
</equa_>
</partcode_>
<comment>Colonne 37 = OPTION Classe inj Z8
</comment>
<partcode_ colonne=37>
<appl>
<pour>
<descr>Z8
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="2">
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="3">
<descr>FAP_inj_cl3
</descr>
</equa_>
<equa_ valeur="A">
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="B">
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="C">
<descr>FAP_inj_cl3
</descr>
</equa_>
<equa_ valeur="X">
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="Y">
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="Z">
<descr>FAP_inj_cl3
</descr>
</equa_>
</partcode_>
<comment>Colonne 37 = Conf BSI11 T5/D9-2001
</comment>
<partcode_ colonne=37>
<appl>
<pour>
<descr>T5
</descr>
</pour>
<pour>
<descr>D9
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>TOIT_RIGIDE
</descr>
</equa_>
<equa_ valeur="2">
<descr>VELUM
</descr>
</equa_>
<equa_ valeur="3">
<descr>TOIT_RIGIDE
</descr>
<descr>VELUM
</descr>
</equa_>
<equa_ valeur="4">
<descr>TO MUX
</descr>
</equa_>
<equa_ valeur="5">
<descr>TO MUX
</descr>
<descr>TOIT_RIGIDE
</descr>
</equa_>
<equa_ valeur="6">
<descr>TO MUX
</descr>
<descr>VELUM
</descr>
</equa_>
<equa_ valeur="7">
<descr>TO MUX
</descr>
<descr>TOIT_RIGIDE
</descr>
<descr>VELUM
</descr>
</equa_>
</partcode_>
<comment>Colonne 37 = Conf BSI11 T1 MUX, T3
</comment>
<partcode_ colonne=37>
<appl>
<pour>
<descr>T1_MUX
</descr>
</pour>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>A6
</descr>
</pour>
<pour>
<descr>T3
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>LUNETTE_AR_OUVRANTE
</descr>
</equa_>
<equa_ valeur="2">
<descr>ESSUIE_VITRE_AR_EN_MA
</descr>
</equa_>
<equa_ valeur="3">
<descr>LUNETTE_AR_OUVRANTE
</descr>
<descr>ESSUIE_VITRE_AR_EN_MA
</descr>
</equa_>
<equa_ valeur="5">
<descr>LUNETTE_AR_OUVRANTE
</descr>
</equa_>
<equa_ valeur="6">
<descr>ESSUIE_VITRE_AR_EN_MA
</descr>
</equa_>
<equa_ valeur="7">
<descr>LUNETTE_AR_OUVRANTE
</descr>
<descr>ESSUIE_VITRE_AR_EN_MA
</descr>
</equa_>
</partcode_>
<comment>Colonne 37 = OPTION COMBINE4 N68 M49
</comment>
<partcode_ colonne=37>
<appl>
<pour>
<descr>M49
</descr>
</pour>
<pour>
<descr>N68
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>12000_miles
</descr>
</equa_>
<equa_ valeur="2">
<descr>12500_miles
</descr>
</equa_>
<equa_ valeur="3">
<descr>12000_miles
</descr>
<descr>12500_miles
</descr>
</equa_>
<equa_ valeur="4">
<descr>20000_miles
</descr>
</equa_>
<equa_ valeur="5">
<descr>12000_miles
</descr>
<descr>20000_miles
</descr>
</equa_>
<equa_ valeur="6">
<descr>12500_miles
</descr>
<descr>20000_miles
</descr>
</equa_>
<equa_ valeur="7">
<descr>12000_miles
</descr>
<descr>12500_miles
</descr>
<descr>20000_miles
</descr>
</equa_>
</partcode_>
<comment>Colonne 37 = OPTION Classe inj X4
</comment>
<partcode_ colonne=37>
<appl>
<pour>
<descr>X4
</descr>
</pour>
<pour>
<descr>X41
</descr>
</pour>
<pour>
<descr>X42
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="2">
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="3">
<descr>FAP_inj_cl3
</descr>
</equa_>
<equa_ valeur="A">
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="B">
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="C">
<descr>FAP_inj_cl3
</descr>
</equa_>
<equa_ valeur="X">
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="Y">
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="Z">
<descr>FAP_inj_cl3
</descr>
</equa_>
</partcode_>
<comment>Colonne 37 = OPTION Classe inj V
</comment>
<partcode_ colonne=37>
<appl>
<pour>
<descr>V
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="2">
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="3">
<descr>FAP_inj_cl3
</descr>
</equa_>
<equa_ valeur="A">
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="B">
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="C">
<descr>FAP_inj_cl3
</descr>
</equa_>
<equa_ valeur="X">
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="Y">
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="Z">
<descr>FAP_inj_cl3
</descr>
</equa_>
</partcode_>
<comment>Colonne 37 = Conf BSI11 A8
</comment>
<partcode_ colonne=37>
<appl>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>A08
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>MILES
</descr>
</equa_>
<equa_ valeur="2">
<descr>TO MUX
</descr>
</equa_>
<equa_ valeur="3">
<descr>TO MUX
</descr>
<descr>MILES
</descr>
</equa_>
<equa_ valeur="4">
<descr>VERROU_PASSAGER
</descr>
</equa_>
<equa_ valeur="5">
<descr>VERROU_PASSAGER
</descr>
<descr>MILES
</descr>
</equa_>
<equa_ valeur="6">
<descr>VERROU_PASSAGER
</descr>
<descr>TO MUX
</descr>
</equa_>
<equa_ valeur="7">
<descr>VERROU_PASSAGER
</descr>
<descr>TO MUX
</descr>
<descr>MILES
</descr>
</equa_>
</partcode_>
<comment>Colonne=37 Conf CMM pour N68_Mux
</comment>
<partcode_ colonne=37>
<appl>
<pour>
<descr>N68_MUX
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>EOBD
</descr>
</equa_>
<equa_ valeur="2">
<descr>CHINA
</descr>
</equa_>
<equa_ valeur="3">
<descr>EOBD
</descr>
<descr>CHINA
</descr>
</equa_>
<equa_ valeur="4">
<descr>A-COMPLETER
</descr>
</equa_>
<equa_ valeur="5">
<descr>EOBD
</descr>
</equa_>
<equa_ valeur="6">
<descr>CHINA
</descr>
</equa_>
<equa_ valeur="7">
<descr>EOBD
</descr>
<descr>CHINA
</descr>
</equa_>
</partcode_>
<comment>Colonne=37 Conf CMM pour M59
</comment>
<partcode_ colonne=37>
<appl>
<pour>
<descr>N68_MUX
</descr>
</pour>
<pour>
<descr>M59
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>EOBD
</descr>
</equa_>
<equa_ valeur="2">
<descr>SURVITESSE
</descr>
</equa_>
<equa_ valeur="3">
<descr>EOBD
</descr>
<descr>SURVITESSE
</descr>
</equa_>
<equa_ valeur="4">
<descr>PEUGEOT
</descr>
</equa_>
<equa_ valeur="5">
<descr>EOBD
</descr>
<descr>PEUGEOT
</descr>
</equa_>
<equa_ valeur="6">
<descr>PEUGEOT
</descr>
<descr>SURVITESSE
</descr>
</equa_>
<equa_ valeur="7">
<descr>EOBD
</descr>
<descr>SURVITESSE
</descr>
<descr>PEUGEOT
</descr>
</equa_>
</partcode_>
<comment>Colonne 38 = OPTION COMBINE5 pour N68 M49
</comment>
<partcode_ colonne=38>
<appl>
<pour>
<descr>M49
</descr>
</pour>
<pour>
<descr>N68
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>10000_miles
</descr>
</equa_>
<equa_ valeur="3">
<descr>10000_miles
</descr>
</equa_>
<equa_ valeur="5">
<descr>10000_miles
</descr>
</equa_>
<equa_ valeur="7">
<descr>10000_miles
</descr>
</equa_>
</partcode_>
<comment>Colonne 38 = OPTION Classe inj T5 D9-2001 A8 A08 A6
</comment>
<partcode_ colonne=38>
<appl>
<pour>
<descr>T5
</descr>
</pour>
<pour>
<descr>D9
</descr>
</pour>
<pour>
<descr>A6
</descr>
</pour>
<pour>
<descr>A8
</descr>
</pour>
<pour>
<descr>A08
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="2">
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="3">
<descr>FAP_inj_cl3
</descr>
</equa_>
<equa_ valeur="4">
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="5">
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="6">
<descr>FAP_inj_cl3
</descr>
</equa_>
<equa_ valeur="A">
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="B">
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="C">
<descr>FAP_inj_cl3
</descr>
</equa_>
<equa_ valeur="X">
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="Y">
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="Z">
<descr>FAP_inj_cl3
</descr>
</equa_>
</partcode_>
<comment>Colonne 38 = OPTION 5 pour V
</comment>
<partcode_ colonne=38>
<appl>
<pour>
<descr>V
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>POMPE_A_AIR
</descr>
</equa_>
<equa_ valeur="2">
<descr>3_TO
</descr>
</equa_>
<equa_ valeur="3">
<descr>POMPE_A_AIR
</descr>
<descr>3_TO
</descr>
</equa_>
<equa_ valeur="4">
<descr>EAU_DS_GO
</descr>
</equa_>
<equa_ valeur="5">
<descr>POMPE_A_AIR
</descr>
<descr>EAU_DS_GO
</descr>
</equa_>
<equa_ valeur="6">
<descr>EAU_DS_GO
</descr>
<descr>3_TO
</descr>
</equa_>
<equa_ valeur="7">
<descr>POMPE_A_AIR
</descr>
<descr>EAU_DS_GO
</descr>
<descr>3_TO
</descr>
</equa_>
</partcode_>
<comment>Colonne 38 DOTE BSI N68_Mux
</comment>
<partcode_ colonne=38>
<appl>
<pour>
<descr>N68_MUX
</descr>
</pour>
</appl>
<equa_ valeur="3">
<descr>DOTE_BSI_N68_V21.3
</descr>
</equa_>
<equa_ valeur="4">
<descr>DOTE_BSI_N68_V20.66
</descr>
</equa_>
<equa_ valeur="6">
<descr>DOTE_BSI_N68_V22
</descr>
</equa_>
</partcode_>
<comment>Colonne 38 DOTE BSI M59
</comment>
<partcode_ colonne=38>
<appl>
<pour>
<descr>M59
</descr>
</pour>
</appl>
<equa_ valeur="2">
<descr>DOTE_BSI_M59_V21.21
</descr>
</equa_>
<equa_ valeur="5">
<descr>DOTE_BSI_M59_V20F
</descr>
</equa_>
<equa_ valeur="7">
<descr>DOTE_BSI_M59_V21.30
</descr>
</equa_>
</partcode_>
<comment>Colonne 38 specifique T1 MUX, T3. Conf BSI 12
</comment>
<partcode_ colonne=38>
<appl>
<pour>
<descr>T1_MUX
</descr>
</pour>
<pour>
<descr>T3
</descr>
</pour>
</appl>
<equa_ valeur="1">
<descr>SAC_GAZ_2_ETAGES
</descr>
</equa_>
<equa_ valeur="2">
<descr>SAC_GAZ_1_ETAGE
</descr>
</equa_>
<equa_ valeur="4">
<descr>SAC_GAZ_CDC_2_ETAGES_PASS_1_ETAGE
</descr>
</equa_>
</partcode_>
</code_>
<comment>Definition des codes VIN
</comment>
<code_ entete="D" long=19 checksum="Modulo39">
<comment>Colonne 1 = Entete
</comment>
<partcode_ colonne=1>
<equa_ valeur="D">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_VIN
</descr>
</equa_>
</partcode_>
</code_>
<comment>Code VIN 20 caracteres et autres
</comment>
<code_ entete="D" long=20 checksum="Modulo39">
<comment>Colonne 1 = entete
</comment>
<partcode_ colonne=1>
<equa_ valeur="D">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_VIN
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="V" long=17 checksum="Aucun">
<comment>Colonne 1 = Entete
</comment>
<partcode_ colonne=1>
<equa_ valeur="V">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_VIN
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="Z" long=17 checksum="Aucun">
<comment>Colonne 1 = Entete
</comment>
<partcode_ colonne=1>
<equa_ valeur="Z">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_VIN
</descr>
</equa_>
</partcode_>
</code_>
<comment>Definition des codes plip ou Schrader
</comment>
<code_ entete="CA" long=13 checksum="PlipHFQ185128">
<comment>nouvelle methode de reco des codes by Denis
</comment>
<partcode_ colonne=0>
<equa_ valeur="">
<descr>CODE_GENE_VALIDE
</descr>
<descr>code_schrader
</descr>
</equa_>
</partcode_>
</code_>
<comment>Definition code Plip saisie douchette
</comment>
<code_ entete="C4" long=12 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="C4">
<descr>CODE_GENE_VALIDE
</descr>
<descr>code_plip
</descr>
</equa_>
</partcode_>
</code_>
<comment>Definition code Plip saisie manuelle
</comment>
<code_ entete="C4" long=13 checksum="PlipHFQ185128">
<partcode_ colonne=1>
<equa_ valeur="C4">
<descr>CODE_GENE_VALIDE
</descr>
<descr>code_plip_manuel
</descr>
</equa_>
</partcode_>
</code_>
<comment>Definition des codes fap sur T5, D9 et Z8
</comment>
<code_ entete="6A" long=12 checksum="Aucun">
<partcode_ colonne=12>
<equa_ valeur="1">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="2">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="3">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl3
</descr>
</equa_>
<equa_ valeur="4">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="5">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="6">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl3
</descr>
</equa_>
<equa_ valeur="7">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="8">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl5
</descr>
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="9">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl3
</descr>
</equa_>
<equa_ valeur="H">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="A">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="B">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="C">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl3
</descr>
</equa_>
<equa_ valeur="M">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="X">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl1
</descr>
</equa_>
<equa_ valeur="Y">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl2
</descr>
</equa_>
<equa_ valeur="Z">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FAP
</descr>
<descr>FAP_inj_cl3
</descr>
</equa_>
</partcode_>
</code_>
<comment>Definition des codes TELECHARGEMENT SOFT BSI
</comment>
<code_ entete="F1" long=13 checksum="Modulo39">
<partcode_ colonne=1>
<equa_ valeur="F1">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_FICHIER_TELECHARGEMENT
</descr>
</equa_>
</partcode_>
</code_>
<comment>Definition code d'Acces
</comment>
<code_ entete="C9" long=13 checksum="Transpondeur">
<partcode_ colonne=1>
<equa_ valeur="C9">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_ACCES_manuel
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="C9" long=12 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="C9">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_ACCES_douchette
</descr>
</equa_>
</partcode_>
</code_>
<comment>Definitions codes Injecteurs Delphi C6 Cylindres 1 a 4
</comment>
<code_ entete="G" long=18 checksum="Modulo39">
<partcode_ colonne=1>
<equa_ valeur="G">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_CYLINDRE_1
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="H" long=18 checksum="Modulo39">
<partcode_ colonne=1>
<equa_ valeur="H">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_CYLINDRE_2
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="I" long=18 checksum="Modulo39">
<partcode_ colonne=1>
<equa_ valeur="I">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_CYLINDRE_3
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="J" long=18 checksum="Modulo39">
<partcode_ colonne=1>
<equa_ valeur="J">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_CYLINDRE_4
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="V" long=21 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="V">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_CYLINDRE_1
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="W" long=21 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="W">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_CYLINDRE_2
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="X" long=21 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="X">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_CYLINDRE_3
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="Y" long=21 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="Y">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_CYLINDRE_4
</descr>
</equa_>
</partcode_>
</code_>
<comment>Definitions codes Injecteurs Bosch DV4 Cylindres 1 a 4
</comment>
<code_ entete="K" long=20 checksum="Modulo39">
<partcode_ colonne=1>
<equa_ valeur="K">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_IMA_5_POINTS
</descr>
<descr>IMA_5_1
</descr>
<descr>CODE_INJ_CYLINDRE_1
</descr>
<descr>CODE_INJ_CYLINDRE_2
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="K" long=19 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="K">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_CYLINDRE_1
</descr>
<descr>CODE_INJ_CYLINDRE_2
</descr>
<descr>IMA_5_1
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="K" long=18 checksum="Modulo39">
<partcode_ colonne=1>
<equa_ valeur="K">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_IMA_4_POINTS
</descr>
<descr>CODE_INJ_CYLINDRE_1
</descr>
<descr>CODE_INJ_CYLINDRE_2
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="L" long=20 checksum="Modulo39">
<partcode_ colonne=1>
<equa_ valeur="L">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_IMA_5_POINTS
</descr>
<descr>IMA_5_2
</descr>
<descr>CODE_INJ_CYLINDRE_3
</descr>
<descr>CODE_INJ_CYLINDRE_4
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="L" long=19 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="L">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_CYLINDRE_3
</descr>
<descr>CODE_INJ_CYLINDRE_4
</descr>
<descr>IMA_5_2
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="L" long=18 checksum="Modulo39">
<partcode_ colonne=1>
<equa_ valeur="L">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_IMA_4_POINTS
</descr>
<descr>CODE_INJ_CYLINDRE_3
</descr>
<descr>CODE_INJ_CYLINDRE_4
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="M" long=11 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="M">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_CYLINDRE_1
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="N" long=11 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="N">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_CYLINDRE_2
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="R" long=11 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="R">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_CYLINDRE_3
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="S" long=11 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="S">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_INJ_CYLINDRE_4
</descr>
</equa_>
</partcode_>
</code_>
<comment>Definition des codes Maintenance
</comment>
<code_ entete="T" long=19 checksum="Modulo39">
<comment>Colonne 1 = Entete
</comment>
<partcode_ colonne=1>
<equa_ valeur="T">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_TEST
</descr>
<descr>SHUNT_ENVOI_SQIP
</descr>
</equa_>
</partcode_>
<partcode_ colonne=16>
<equa_ valeur="C">
<descr>TEST_COM
</descr>
</equa_>
</partcode_>
<partcode_ colonne=16>
<equa_ valeur="I">
<descr>TEST_IMPRESSION
</descr>
</equa_>
</partcode_>
<partcode_ colonne=16>
<equa_ valeur="B">
<descr>TEST_CODE_BAR
</descr>
</equa_>
</partcode_>
<partcode_ colonne=16>
<equa_ valeur="F">
<descr>REIMPRESSION_FIL
</descr>
</equa_>
</partcode_>
<partcode_ colonne=16>
<equa_ valeur="R">
<descr>REIMPRESSION_RAD
</descr>
</equa_>
</partcode_>
<partcode_ colonne=16>
<equa_ valeur="O">
<descr>TEST_MESURE
</descr>
</equa_>
</partcode_>
<partcode_ colonne=16>
<equa_ valeur="E">
<descr>TEST_OUTIL_CONTROLE
</descr>
</equa_>
</partcode_>
<partcode_ colonne=16>
<equa_ valeur="V">
<descr>REIMPRESSION_VIN
</descr>
</equa_>
</partcode_>
<partcode_ colonne=16>
<equa_ valeur="T">
<descr>CODE_BT2M
</descr>
</equa_>
</partcode_>
</code_>
<comment>MODE ETUDE
</comment>
<code_ entete="EXPERPSA" long=8 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="EXPERPSA">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_MODE_ETUDE
</descr>
<descr>MODE_ETUDES
</descr>
<descr>SHUNT_ENVOI_SQIP
</descr>
</equa_>
</partcode_>
</code_>
<comment>MODE_MODERNISATION
</comment>
<code_ entete="MODELEC" long=7 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="MODELEC">
<descr>CODE_GENE_VALIDE
</descr>
<descr>MODELEC
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="MODEMODERNISATION" long=17 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="MODEMODERNISATION">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_MODERNISATION
</descr>
<descr>MODE_MODERNISATION
</descr>
</equa_>
</partcode_>
</code_>
<comment>mode oscilo
</comment>
<code_ entete="ACTIVEOSCILLO" long=13 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="ACTIVEOSCILLO">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_OSCILLO
</descr>
<descr>MODE_OSCILLO_ACTIF
</descr>
</equa_>
</partcode_>
</code_>
<comment>Validation OUI
</comment>
<code_ entete="OUI" long=3 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="OUI">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_REPONSE_OUI
</descr>
<descr>CODE_REPONSE_VALIDE
</descr>
</equa_>
</partcode_>
</code_>
<comment>Validation NON
</comment>
<code_ entete="NON" long=3 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="NON">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_REPONSE_NON
</descr>
<descr>CODE_REPONSE_VALIDE
</descr>
</equa_>
</partcode_>
</code_>
<comment>CODE OPERATEUR
</comment>
<code_ entete="P" long=7 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="P">
<descr>CODE_OPERATEUR
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="U" long=7 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="U">
<descr>CODE_OPERATEUR
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="J" long=7 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="J">
<descr>CODE_OPERATEUR
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="E" long=7 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="E">
<descr>CODE_OPERATEUR
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="C" long=7 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="C">
<descr>CODE_OPERATEUR
</descr>
</equa_>
</partcode_>
</code_>
<code_ entete="Z" long=7 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="Z">
<descr>CODE_OPERATEUR
</descr>
</equa_>
</partcode_>
</code_>
<comment>MODE SAISIE CODE 2D EN MODE DEGRADE 1
</comment>
<code_ entete="CODE2D" long=6 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="CODE2D">
<descr>CODE_GENE_VALIDE
</descr>
<descr>SAISIE_CODE_2D_MODE_DEGRADE_1
</descr>
</equa_>
</partcode_>
</code_>
<comment>VEHICULE CAN
</comment>
<code_ entete="CAN" long=3 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="CAN">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_TYP
</descr>
<descr>VEHICULE_CAN
</descr>
</equa_>
</partcode_>
</code_>
<comment>VEHICULE VAN
</comment>
<code_ entete="VAN" long=3 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="VAN">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_TYP
</descr>
<descr>VEHICULE_VAN
</descr>
</equa_>
</partcode_>
</code_>
<comment>RETOUCHE FREINS
</comment>
<code_ entete="RETFREIN" long=8 checksum="Aucun">
<partcode_ colonne=1>
<equa_ valeur="RETFREIN">
<descr>CODE_GENE_VALIDE
</descr>
<descr>RETOUCHE_ABS_A_FAIRE
</descr>
</equa_>
</partcode_>
</code_>
<comment>Definition code test conformite C.M.M
</comment>
<code_ entete="CM" long=24 checksum="Modulo39">
<partcode_ colonne=1>
<equa_ valeur="CM">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_CMM_CONFORME
</descr>
</equa_>
</partcode_>
</code_>
<comment>Definition code test conformite B.V.A
</comment>
<code_ entete="BV" long=24 checksum="Modulo39">
<partcode_ colonne=1>
<equa_ valeur="BV">
<descr>CODE_GENE_VALIDE
</descr>
<descr>CODE_BVA_CONFORME
</descr>
</equa_>
</partcode_>
</code_>
<comment>Definition code test conformite radio/EMF
</comment>
<code_ entete="RA" long=28 checksum="Modulo39">
<partcode_ colonne=1>
<equa_ valeur="RA">
<descr>CODE_GENE_VALIDE
</descr>
<descr>code_radio_EMF_conforme
</descr>
</equa_>
</partcode_>
</code_>
</codegene>
</userserv>

