<iodissee chk="22017826">
<entete>
<ifichier>
<nomfich nom="menu0000">
</nomfich>
<modif date="13/04/2012" user="xingdong xu" site="alarme">
</modif>
</ifichier>
<ioutil nom="ime2" version="8.0.0.0" dateexe="15/04/2011">
</ioutil>
</entete>
<precel>
</precel>
<cel>
<debut poscol=7 poslig=1 destc=7 destl=2 ident=10>
</debut>
<sarbre poscol=7 poslig=2 destc=7 destl=3 ident=11 nomfichier="vin_code_entry.s">
<CheminFichier chemin="COMMUN\BARCODES">
</CheminFichier>
</sarbre>
<sarbre poscol=7 poslig=3 destc=7 destl=4 ident=12 nomfichier="PIN.s">
<CheminFichier chemin="PIN">
</CheminFichier>
</sarbre>
<act poscol=7 poslig=4 destc=7 destl=5 ident=13>
<Calcul>
<Attente val="2">
</Attente>
</Calcul>
</act>
<act poscol=7 poslig=5 destc=7 destl=4 ident=14>
</act>
</cel>
</iodissee>
